/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Hash_NonPipelined_SHA3512_topEntity_spongeFSM
    ( // Inputs
      input wire logic c$bindCsr  // clock
    , input wire logic c$bindCsr_0  // reset
    , input wire logic c$bindCsr_1  // enable
    , input wire SHA3_512_NonPipelined_types::Tuple3_0 eta1

      // Outputs
    , output SHA3_512_NonPipelined_types::Tuple2_1 result
    );
  logic [63:0] result_0;
  logic [63:0] c$case_alt;
  logic [63:0] c$case_alt_0;
  logic [63:0] c$case_alt_1;
  logic [63:0] c$case_alt_2;
  logic [63:0] c$case_alt_3;
  logic [63:0] c$case_alt_4;
  logic [1599:0] c$app_arg;
  logic [1599:0] state;
  SHA3_512_NonPipelined_types::State ds1 = {{2'b00,4'd0,3'bxxx}
,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
  SHA3_512_NonPipelined_types::Tuple2 c$ds_case_alt;
  SHA3_512_NonPipelined_types::Tuple2 result_1;
  SHA3_512_NonPipelined_types::State c$ds_app_arg;
  SHA3_512_NonPipelined_types::State c$ds_app_arg_0;
  logic [2:0] counter;
  SHA3_512_NonPipelined_types::Tuple2 c$ds_case_alt_0;
  logic tready;
  logic [1:0] seenTLAST;
  logic [4:0] counter_0;
  SHA3_512_NonPipelined_types::Tuple2 result_2;
  SHA3_512_NonPipelined_types::Tuple2 c$case_alt_5;
  SHA3_512_NonPipelined_types::Tuple2 c$case_alt_6;
  SHA3_512_NonPipelined_types::Tuple2 result_3;
  SHA3_512_NonPipelined_types::Tuple2 c$case_alt_7;
  logic c$app_arg_0;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_5;
  logic signed [63:0] c$app_arg_2;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_6;
  logic signed [63:0] c$app_arg_4;
  logic [1599:0] c$app_arg_5;
  logic [10:0] c$complementAt1_arg0;
  logic [10:0] c$complementAt1_arg0_case_alt;
  logic [10:0] c$complementAt1_arg0_case_alt_0;
  logic [10:0] c$complementAt1_arg0_case_alt_1;
  logic [10:0] c$complementAt1_arg0_case_alt_2;
  logic [10:0] c$complementAt1_arg0_case_alt_3;
  logic [10:0] c$complementAt1_arg0_case_alt_4;
  logic [10:0] c$complementAt1_arg0_case_alt_5;
  logic [10:0] c$complementAt1_arg0_case_alt_6;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn;
  logic c$complementAt1_tupIn_case_scrut;
  SHA3_512_NonPipelined_types::Tuple2_0 result_7;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_0;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_1;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_2;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_3;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_4;
  SHA3_512_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_5;
  logic [1599:0] result_8;
  logic [1599:0] c$case_alt_8;
  logic [1599:0] c$case_alt_9;
  logic [1599:0] c$case_alt_10;
  logic [1599:0] c$case_alt_11;
  logic [1599:0] c$case_alt_12;
  logic [1599:0] c$case_alt_13;
  logic [1599:0] c$case_alt_14;
  logic [1599:0] c$case_alt_15;
  logic [1599:0] c$case_alt_16;
  logic [1599:0] c$case_alt_17;
  logic [1599:0] c$case_alt_18;
  logic [1599:0] c$case_alt_19;
  logic [1599:0] c$case_alt_20;
  logic [1599:0] c$case_alt_21;
  logic [1599:0] c$case_alt_22;
  logic [1599:0] c$case_alt_23;
  logic [1599:0] c$case_alt_24;
  logic [1599:0] c$app_arg_6;
  logic c$complementAt1_tupIn_case_scrut_0;
  logic c$complementAt1_tupIn_case_scrut_1;
  logic c$complementAt1_tupIn_case_scrut_2;
  logic c$complementAt1_tupIn_case_scrut_3;
  logic c$complementAt1_tupIn_case_scrut_4;
  logic c$complementAt1_tupIn_case_scrut_5;
  logic c$complementAt1_tupIn_case_scrut_6;
  logic c$complementAt1_tupIn_case_scrut_7;
  logic flush;
  SHA3_512_NonPipelined_types::AXI4Stream \input ;
  logic [3:0] counter_1;
  logic [8:0] c$ds_case_alt_selection_1;
  logic [10:0] c$i_27;

  assign result = c$ds_case_alt.Tuple2_sel1;

  assign result_0 = (counter == 3'd0) ? (c$app_arg[1599 : 1536]) : c$case_alt;

  assign c$case_alt = (counter == 3'd1) ? (c$app_arg[1535 : 1472]) : c$case_alt_0;

  assign c$case_alt_0 = (counter == 3'd2) ? (c$app_arg[1471 : 1408]) : c$case_alt_1;

  assign c$case_alt_1 = (counter == 3'd3) ? (c$app_arg[1407 : 1344]) : c$case_alt_2;

  assign c$case_alt_2 = (counter == 3'd4) ? (c$app_arg[1343 : 1280]) : c$case_alt_3;

  assign c$case_alt_3 = (counter == 3'd5) ? (c$app_arg[1279 : 1216]) : c$case_alt_4;

  assign c$case_alt_4 = (counter == 3'd6) ? (c$app_arg[1215 : 1152]) : (c$app_arg[1151 : 1088]);

  assign c$app_arg = state;

  assign state = ds1.State_sel1;

  // register begin
  always_ff @(posedge c$bindCsr or  posedge  c$bindCsr_0) begin : ds1_register
    if ( c$bindCsr_0) begin
      ds1 <= {{2'b00,4'd0,3'bxxx}
  ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
    end else  if (c$bindCsr_1)  begin
      ds1 <= c$ds_case_alt.Tuple2_sel0;
    end
  end
  // register end

  assign c$ds_case_alt_selection_1 = ds1.State_sel0;

  always_comb begin
    case(c$ds_case_alt_selection_1[8:7])
      2'b00 : c$ds_case_alt = result_2;
      2'b01 : c$ds_case_alt = c$ds_case_alt_0;
      default : c$ds_case_alt = result_1;
    endcase
  end

  assign result_1 = (counter == 3'd7) ? {c$ds_app_arg
                                        ,{{result_0,1'b1,1'b1},1'b0}} : {c$ds_app_arg_0
                                                                        ,{{result_0,1'b1,1'b0},1'b0}};

  assign c$ds_app_arg = tready ? {{2'b00,4'd0,3'bxxx}
                                 ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000} : {{2'b10,3'd7,4'bxxxx}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,state};

  assign c$ds_app_arg_0 = tready ? {{2'b10,counter + 3'd1,4'bxxxx}
                                   ,state} : ds1;

  assign counter = ds1[1606:1604];

  Hash_NonPipelined_SHA3512_topEntity_pad Hash_NonPipelined_SHA3512_topEntity_pad_c$ds_case_alt_0
    ( .result (c$ds_case_alt_0)
    , .eta2 (counter_0)
    , .eta3 (seenTLAST)
    , .eta4 (state)
    , .eta5 (tready) );

  assign tready = eta1.Tuple3_0_sel1;

  assign seenTLAST = ds1[1601:1600];

  assign counter_0 = ds1[1606:1602];

  assign result_2 = c$complementAt1_tupIn_case_scrut ? {{{2'b01,5'd0,2'd0}
                                                        ,result_4}
                                                       ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                         ,1'b0
                                                         ,1'b0}
                                                        ,1'b0}} : c$case_alt_5;

  assign c$case_alt_5 = (~ \input .AXI4Stream_sel1) ? {{{2'b00,counter_1,3'bxxx}
                                                       ,state}
                                                      ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                        ,1'b0
                                                        ,1'b0}
                                                       ,1'b1}} : c$case_alt_6;

  assign c$case_alt_6 = (\input .AXI4Stream_sel2 & c$app_arg_0) ? {{{2'b01,5'd0,2'd0}
                                                                   ,result_4}
                                                                  ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                                    ,1'b0
                                                                    ,1'b0}
                                                                   ,1'b0}} : result_3;

  assign result_3 = \input .AXI4Stream_sel2 ? {{{2'b01,5'd0,2'd1}
                                               ,result_8}
                                              ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                ,1'b0
                                                ,1'b0}
                                               ,1'b0}} : c$case_alt_7;

  assign c$case_alt_7 = c$app_arg_0 ? {{{2'b00,counter_1 + 4'd1,3'bxxx}
                                       ,result_8}
                                      ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                        ,1'b0
                                        ,1'b0}
                                       ,1'b1}} : {{{2'b01,5'd0,2'd2},result_8}
                                                 ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                   ,1'b0
                                                   ,1'b0}
                                                  ,1'b0}};

  assign c$app_arg_0 = counter_1 < 4'd8;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_1;
    result_4[64'sd1024] = (~ (c$app_arg_1[64'sd1024]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_3;
    result_5[c$app_arg_2] = (~ (c$app_arg_3[c$app_arg_2]));
  end
  // replaceBit end

  assign c$app_arg_2 = $unsigned({{(64-11) {1'b0}},c$complementAt1_arg0});

  assign c$app_arg_3 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_5;
    result_6[c$app_arg_4] = (~ (c$app_arg_5[c$app_arg_4]));
  end
  // replaceBit end

  assign c$i_27 = c$complementAt1_tupIn.Tuple2_0_sel0;

  assign c$app_arg_4 = $unsigned({{(64-11) {1'b0}},c$i_27});

  assign c$app_arg_5 = c$complementAt1_tupIn.Tuple2_0_sel1;

  assign c$complementAt1_arg0 = c$complementAt1_tupIn_case_scrut ? 11'd1597 : c$complementAt1_arg0_case_alt;

  assign c$complementAt1_arg0_case_alt = c$complementAt1_tupIn_case_scrut_7 ? 11'd1533 : c$complementAt1_arg0_case_alt_0;

  assign c$complementAt1_arg0_case_alt_0 = c$complementAt1_tupIn_case_scrut_6 ? 11'd1469 : c$complementAt1_arg0_case_alt_1;

  assign c$complementAt1_arg0_case_alt_1 = c$complementAt1_tupIn_case_scrut_5 ? 11'd1405 : c$complementAt1_arg0_case_alt_2;

  assign c$complementAt1_arg0_case_alt_2 = c$complementAt1_tupIn_case_scrut_4 ? 11'd1341 : c$complementAt1_arg0_case_alt_3;

  assign c$complementAt1_arg0_case_alt_3 = c$complementAt1_tupIn_case_scrut_3 ? 11'd1277 : c$complementAt1_arg0_case_alt_4;

  assign c$complementAt1_arg0_case_alt_4 = c$complementAt1_tupIn_case_scrut_2 ? 11'd1213 : c$complementAt1_arg0_case_alt_5;

  assign c$complementAt1_arg0_case_alt_5 = c$complementAt1_tupIn_case_scrut_1 ? 11'd1149 : c$complementAt1_arg0_case_alt_6;

  assign c$complementAt1_arg0_case_alt_6 = c$complementAt1_tupIn_case_scrut_0 ? 11'd1085 : 11'd1597;

  assign c$complementAt1_tupIn = c$complementAt1_tupIn_case_scrut ? {11'd1598
                                                                    ,state} : result_7;

  assign c$complementAt1_tupIn_case_scrut = flush & (counter_1 == 4'd0);

  assign result_7 = c$complementAt1_tupIn_case_scrut_7 ? {11'd1534
                                                         ,result_8} : c$complementAt1_tupIn_case_alt;

  assign c$complementAt1_tupIn_case_alt = c$complementAt1_tupIn_case_scrut_6 ? {11'd1470
                                                                               ,result_8} : c$complementAt1_tupIn_case_alt_0;

  assign c$complementAt1_tupIn_case_alt_0 = c$complementAt1_tupIn_case_scrut_5 ? {11'd1406
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_1;

  assign c$complementAt1_tupIn_case_alt_1 = c$complementAt1_tupIn_case_scrut_4 ? {11'd1342
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_2;

  assign c$complementAt1_tupIn_case_alt_2 = c$complementAt1_tupIn_case_scrut_3 ? {11'd1278
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_3;

  assign c$complementAt1_tupIn_case_alt_3 = c$complementAt1_tupIn_case_scrut_2 ? {11'd1214
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_4;

  assign c$complementAt1_tupIn_case_alt_4 = c$complementAt1_tupIn_case_scrut_1 ? {11'd1150
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_5;

  assign c$complementAt1_tupIn_case_alt_5 = c$complementAt1_tupIn_case_scrut_0 ? {11'd1086
                                                                                 ,result_8} : {11'd1598,result_8};

  assign result_8 = (counter_1 == 4'd0) ? c$case_alt_8 : c$case_alt_9;

  // setSlice begin
  always_comb begin
    c$case_alt_8 = c$app_arg_6;
    c$case_alt_8[1599 : 1536] = ((c$app_arg_6[1599 : 1536]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_9 = (counter_1 == 4'd1) ? c$case_alt_10 : c$case_alt_11;

  // setSlice begin
  always_comb begin
    c$case_alt_10 = c$app_arg_6;
    c$case_alt_10[1535 : 1472] = ((c$app_arg_6[1535 : 1472]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_11 = (counter_1 == 4'd2) ? c$case_alt_12 : c$case_alt_13;

  // setSlice begin
  always_comb begin
    c$case_alt_12 = c$app_arg_6;
    c$case_alt_12[1471 : 1408] = ((c$app_arg_6[1471 : 1408]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_13 = (counter_1 == 4'd3) ? c$case_alt_14 : c$case_alt_15;

  // setSlice begin
  always_comb begin
    c$case_alt_14 = c$app_arg_6;
    c$case_alt_14[1407 : 1344] = ((c$app_arg_6[1407 : 1344]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_15 = (counter_1 == 4'd4) ? c$case_alt_16 : c$case_alt_17;

  // setSlice begin
  always_comb begin
    c$case_alt_16 = c$app_arg_6;
    c$case_alt_16[1343 : 1280] = ((c$app_arg_6[1343 : 1280]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_17 = (counter_1 == 4'd5) ? c$case_alt_18 : c$case_alt_19;

  // setSlice begin
  always_comb begin
    c$case_alt_18 = c$app_arg_6;
    c$case_alt_18[1279 : 1216] = ((c$app_arg_6[1279 : 1216]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_19 = (counter_1 == 4'd6) ? c$case_alt_20 : c$case_alt_21;

  // setSlice begin
  always_comb begin
    c$case_alt_20 = c$app_arg_6;
    c$case_alt_20[1215 : 1152] = ((c$app_arg_6[1215 : 1152]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_21 = (counter_1 == 4'd7) ? c$case_alt_22 : c$case_alt_23;

  // setSlice begin
  always_comb begin
    c$case_alt_22 = c$app_arg_6;
    c$case_alt_22[1151 : 1088] = ((c$app_arg_6[1151 : 1088]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_23 = (counter_1 == 4'd8) ? c$case_alt_24 : state;

  // setSlice begin
  always_comb begin
    c$case_alt_24 = c$app_arg_6;
    c$case_alt_24[1087 : 1024] = ((c$app_arg_6[1087 : 1024]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$app_arg_6 = state;

  assign c$complementAt1_tupIn_case_scrut_0 = counter_1 == 4'd7;

  assign c$complementAt1_tupIn_case_scrut_1 = counter_1 == 4'd6;

  assign c$complementAt1_tupIn_case_scrut_2 = counter_1 == 4'd5;

  assign c$complementAt1_tupIn_case_scrut_3 = counter_1 == 4'd4;

  assign c$complementAt1_tupIn_case_scrut_4 = counter_1 == 4'd3;

  assign c$complementAt1_tupIn_case_scrut_5 = counter_1 == 4'd2;

  assign c$complementAt1_tupIn_case_scrut_6 = counter_1 == 4'd1;

  assign c$complementAt1_tupIn_case_scrut_7 = counter_1 == 4'd0;

  assign flush = eta1.Tuple3_0_sel2;

  assign \input  = eta1.Tuple3_0_sel0;

  assign counter_1 = ds1[1606:1603];


endmodule

