/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module G_I274_O256
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic TREADY
    , input wire logic [273:0] MSG_TDATA
    , input wire logic MSG_TVALID
    , input wire logic MSG_TLAST
    , input wire logic MSG_FLUSH

      // Outputs
    , output logic [255:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    , output logic DIGEST_TLAST
    , output logic MSG_TREADY
    );
  G_I274_O256_types::Tuple2_4 ds;
  G_I274_O256_types::AXI4Stream_0 outStream;
  G_I274_O256_types::Tuple2_3 ds_fun_arg;
  G_I274_O256_types::Tuple4 result;

  assign result = {outStream.AXI4Stream_0_sel0
                  ,outStream.AXI4Stream_0_sel1
                  ,outStream.AXI4Stream_0_sel2
                  ,ds.Tuple2_4_sel1};

  assign ds_fun_arg = {{MSG_TDATA
                       ,MSG_TVALID
                       ,MSG_TLAST}
                      ,MSG_FLUSH};

  Component_G_i274o256_i274o256Stream Component_G_i274o256_i274o256Stream_ds
    ( .result (ds)
    , .clk (CLK)
    , .rst (RST)
    , .en (EN)
    , .treadySig (TREADY)
    , .inputSig (ds_fun_arg) );

  assign outStream = ds.Tuple2_4_sel0;

  assign DIGEST_TDATA = result.Tuple4_sel0;

  assign DIGEST_TVALID = result.Tuple4_sel1;

  assign DIGEST_TLAST = result.Tuple4_sel2;

  assign MSG_TREADY = result.Tuple4_sel3;


endmodule

