/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_G512_i256o256_i256o256Hidden
    ( // Inputs
      input wire logic c$bindCsr  // clock
    , input wire logic c$bindCsr_0  // reset
    , input wire logic c$bindCsr_1  // enable
    , input wire logic eta
    , input wire dut_types::AXI4Stream c$bindCsr_2

      // Outputs
    , output dut_types::Tuple2_4 result
    );
  dut_types::Tuple3_0 result_fun_arg;

  assign result_fun_arg = {c$bindCsr_2
                          ,eta
                          ,1'b0};

  Component_G512_i256o256_spongeFSM Component_G512_i256o256_spongeFSM_result
    ( .result (result)
    , .c$bindCsr (c$bindCsr)
    , .c$bindCsr_0 (c$bindCsr_0)
    , .c$bindCsr_1 (c$bindCsr_1)
    , .eta2 (result_fun_arg) );


endmodule

