/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module dut
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [255:0] MSG_TDATA
    , input wire logic MSG_TVALID
    , input wire logic MSG_TLAST
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [255:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    , output logic DIGEST_TLAST
    , output logic MSG_TREADY
    );
  dut_types::Tuple2_4 inputSig;
  logic result_fun_arg;
  dut_types::AXI4Stream result_fun_arg_0;
  dut_types::Tuple2_4 result;
  dut_types::AXI4Stream DIGEST;

  assign inputSig = {{MSG_TDATA
                     ,MSG_TVALID
                     ,MSG_TLAST}
                    ,DIGEST_TREADY};

  assign result_fun_arg = inputSig.Tuple2_4_sel1;

  assign result_fun_arg_0 = inputSig.Tuple2_4_sel0;

  Component_G512_i256o256_i256o256Hidden Component_G512_i256o256_i256o256Hidden_result
    ( .result (result)
    , .c$bindCsr (CLK)
    , .c$bindCsr_0 (RST)
    , .c$bindCsr_1 (EN)
    , .eta (result_fun_arg)
    , .c$bindCsr_2 (result_fun_arg_0) );

  assign DIGEST = result.Tuple2_4_sel0;

  assign MSG_TREADY = result.Tuple2_4_sel1;

  assign DIGEST_TDATA = DIGEST.AXI4Stream_sel0;

  assign DIGEST_TVALID = DIGEST.AXI4Stream_sel1;

  assign DIGEST_TLAST = DIGEST.AXI4Stream_sel2;


endmodule

