/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_PRF2
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [263:0] MSG_33B
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [65:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    );
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] state;
  logic [4:0] roundIdx;
  logic [1611:0] st = {2'b00,1610'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  Component_PRF2_types::Tuple2 result_0;
  logic [1599:0] result_1;
  logic [1599:0] c$app_arg;
  logic [1599:0] result_2;
  logic [1599:0] c$app_arg_0;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_4;
  logic [63:0] c$ds_app_arg;
  logic [63:0] c$ds_case_alt;
  logic [63:0] c$ds_case_alt_0;
  logic [63:0] c$ds_case_alt_1;
  logic [63:0] c$ds_case_alt_2;
  logic [63:0] c$ds_case_alt_3;
  logic [63:0] c$ds_case_alt_4;
  logic [63:0] c$ds_case_alt_5;
  logic [63:0] c$ds_case_alt_6;
  logic [63:0] c$ds_case_alt_7;
  logic [63:0] c$ds_case_alt_8;
  logic [63:0] c$ds_case_alt_9;
  logic [63:0] c$ds_case_alt_10;
  logic [63:0] c$ds_case_alt_11;
  logic [63:0] c$ds_case_alt_12;
  logic [63:0] c$ds_case_alt_13;
  logic [1599:0] c$ds_app_arg_0;
  logic [1611:0] c$ds_app_arg_1;
  logic [1611:0] c$ds_case_alt_14;
  logic lastWord;
  logic [1611:0] c$ds_case_alt_15;
  logic [1599:0] state_0;
  logic [4:0] wordIdx;
  Component_PRF2_types::Tuple2 result_7;
  logic [4:0] wordIdx_0;
  Component_PRF2_types::Tuple2_0 result;
  Component_PRF2_types::AXI4Stream DIGEST_TDATA_0;

  assign result = result_0.Tuple2_sel1;

  Component_PRF2_topEntity_keccakF1600 Component_PRF2_topEntity_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (roundIdx)
    , .x (state) );

  assign state = st[1599:0];

  assign roundIdx = st[1609:1605];

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : st_register
    if ( RST) begin
      st <= {2'b00,1610'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      st <= result_0.Tuple2_sel0;
    end
  end
  // register end

  always_comb begin
    case(st[1611:1610])
      2'b00 : result_0 = {{2'b01,5'd0,5'd0,result_1}
                         ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                           ,1'b0
                           ,1'b0}
                          ,1'b1}};
      2'b01 : result_0 = result_7;
      2'b10 : result_0 = {c$ds_app_arg_1
                         ,{{c$ds_app_arg,1'b1,lastWord},1'b0}};
      default : result_0 = {{2'b11,1610'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                           ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                             ,1'b0
                             ,1'b0}
                            ,1'b0}};
    endcase
  end

  // replaceBit start
  always_comb begin
    result_1 = c$app_arg;
    result_1[64'sd512] = (~ (c$app_arg[64'sd512]));
  end
  // replaceBit end

  assign c$app_arg = result_2;

  // replaceBit start
  always_comb begin
    result_2 = c$app_arg_0;
    result_2[64'sd1331] = (~ (c$app_arg_0[64'sd1331]));
  end
  // replaceBit end

  assign c$app_arg_0 = result_3;

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_1;
    result_3[64'sd1332] = (~ (c$app_arg_1[64'sd1332]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_4;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_2;
    result_4[64'sd1333] = (~ (c$app_arg_2[64'sd1333]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_3;
    result_5[64'sd1334] = (~ (c$app_arg_3[64'sd1334]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_4;
    result_6[64'sd1335] = (~ (c$app_arg_4[64'sd1335]));
  end
  // replaceBit end

  assign c$app_arg_4 = ({MSG_33B,1336'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000});

  assign c$ds_app_arg = (wordIdx == 5'd0) ? (c$ds_app_arg_0[1599 : 1536]) : c$ds_case_alt;

  assign c$ds_case_alt = (wordIdx == 5'd1) ? (c$ds_app_arg_0[1535 : 1472]) : c$ds_case_alt_0;

  assign c$ds_case_alt_0 = (wordIdx == 5'd2) ? (c$ds_app_arg_0[1471 : 1408]) : c$ds_case_alt_1;

  assign c$ds_case_alt_1 = (wordIdx == 5'd3) ? (c$ds_app_arg_0[1407 : 1344]) : c$ds_case_alt_2;

  assign c$ds_case_alt_2 = (wordIdx == 5'd4) ? (c$ds_app_arg_0[1343 : 1280]) : c$ds_case_alt_3;

  assign c$ds_case_alt_3 = (wordIdx == 5'd5) ? (c$ds_app_arg_0[1279 : 1216]) : c$ds_case_alt_4;

  assign c$ds_case_alt_4 = (wordIdx == 5'd6) ? (c$ds_app_arg_0[1215 : 1152]) : c$ds_case_alt_5;

  assign c$ds_case_alt_5 = (wordIdx == 5'd7) ? (c$ds_app_arg_0[1151 : 1088]) : c$ds_case_alt_6;

  assign c$ds_case_alt_6 = (wordIdx == 5'd8) ? (c$ds_app_arg_0[1087 : 1024]) : c$ds_case_alt_7;

  assign c$ds_case_alt_7 = (wordIdx == 5'd9) ? (c$ds_app_arg_0[1023 : 960]) : c$ds_case_alt_8;

  assign c$ds_case_alt_8 = (wordIdx == 5'd10) ? (c$ds_app_arg_0[959 : 896]) : c$ds_case_alt_9;

  assign c$ds_case_alt_9 = (wordIdx == 5'd11) ? (c$ds_app_arg_0[895 : 832]) : c$ds_case_alt_10;

  assign c$ds_case_alt_10 = (wordIdx == 5'd12) ? (c$ds_app_arg_0[831 : 768]) : c$ds_case_alt_11;

  assign c$ds_case_alt_11 = (wordIdx == 5'd13) ? (c$ds_app_arg_0[767 : 704]) : c$ds_case_alt_12;

  assign c$ds_case_alt_12 = (wordIdx == 5'd14) ? (c$ds_app_arg_0[703 : 640]) : c$ds_case_alt_13;

  assign c$ds_case_alt_13 = lastWord ? (c$ds_app_arg_0[639 : 576]) : (c$ds_app_arg_0[575 : 512]);

  assign c$ds_app_arg_0 = state_0;

  assign c$ds_app_arg_1 = DIGEST_TREADY ? c$ds_case_alt_14 : st;

  assign c$ds_case_alt_14 = lastWord ? {2'b11,1610'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : c$ds_case_alt_15;

  assign lastWord = wordIdx == 5'd15;

  assign c$ds_case_alt_15 = (wordIdx == 5'd16) ? {2'b01,5'd0,5'd17,state_0} : {2'b10,wordIdx + 5'd1,state_0,5'bxxxxx};

  assign state_0 = st[1604:5];

  assign wordIdx = st[1609:1605];

  assign result_7 = (roundIdx == 5'd23) ? {{2'b10,wordIdx_0,c$keccakF1600_out,5'bxxxxx}
                                          ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                            ,1'b0
                                            ,1'b0}
                                           ,1'b0}} : {{2'b01,roundIdx + 5'd1,wordIdx_0,c$keccakF1600_out}
                                                     ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                       ,1'b0
                                                       ,1'b0}
                                                      ,1'b0}};

  assign wordIdx_0 = st[1604:1600];

  assign DIGEST_TDATA_0 = result.Tuple2_0_sel0;

  assign DIGEST_TVALID = result.Tuple2_0_sel1;

  assign DIGEST_TDATA = DIGEST_TDATA_0;


endmodule

