/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_G768_i256o256_i256o256Stream
    ( // Inputs
      input wire logic clk  // clock
    , input wire logic rst  // reset
    , input wire logic en  // enable
    , input wire logic treadySig
    , input wire G768_I256_O256_types::Tuple2_4 inputSig

      // Outputs
    , output G768_I256_O256_types::Tuple2_4 result
    );
  G768_I256_O256_types::Tuple3_0 result_fun_arg;

  assign result_fun_arg = {inputSig.Tuple2_4_sel0
                          ,treadySig
                          ,inputSig.Tuple2_4_sel1};

  Component_G768_i256o256_spongeFSM Component_G768_i256o256_spongeFSM_result
    ( .result (result)
    , .c$bindCsr (clk)
    , .c$bindCsr_0 (rst)
    , .c$bindCsr_1 (en)
    , .eta2 (result_fun_arg) );


endmodule

