/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module SN512_I272_O24_B60
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [271:0] SEED_TDATA
    , input wire logic SEED_TVALID
    , input wire logic SEED_TLAST
    , input wire logic COEFF_TREADY

      // Outputs
    , output logic [23:0] COEFF_TDATA
    , output logic COEFF_TVALID
    , output logic COEFF_TLAST
    , output logic SEED_TREADY
    );
  SN512_I272_O24_B60_types::State c$ds_app_arg = {{2'b00,5'bxxxxx}
,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
  SN512_I272_O24_B60_types::Tuple2_2 result_0;
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] result_1;
  logic [1599:0] c$app_arg;
  logic [1599:0] result_2;
  logic [1599:0] c$app_arg_0;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_4;
  SN512_I272_O24_B60_types::Tuple2_3 result_7;
  SN512_I272_O24_B60_types::State c$case_alt;
  SN512_I272_O24_B60_types::State c$app_arg_5;
  logic [47:0] result_8;
  logic [47:0] c$case_alt_0;
  logic [47:0] c$case_alt_1;
  logic [47:0] c$case_alt_2;
  logic [47:0] c$case_alt_3;
  logic [47:0] c$case_alt_4;
  logic [47:0] c$case_alt_5;
  logic [47:0] c$case_alt_6;
  logic [47:0] c$case_alt_7;
  logic [47:0] c$case_alt_8;
  logic [47:0] c$case_alt_9;
  logic [47:0] c$case_alt_10;
  logic [47:0] c$case_alt_11;
  logic [47:0] c$case_alt_12;
  logic [47:0] c$case_alt_13;
  logic [47:0] c$case_alt_14;
  logic [47:0] c$case_alt_15;
  logic [47:0] c$case_alt_16;
  logic [47:0] c$case_alt_17;
  logic [47:0] c$case_alt_18;
  logic [47:0] c$case_alt_19;
  logic [47:0] c$case_alt_20;
  logic [47:0] c$case_alt_21;
  logic [47:0] c$case_alt_22;
  logic [47:0] c$case_alt_23;
  logic [47:0] c$case_alt_24;
  logic [47:0] c$case_alt_25;
  logic [47:0] c$case_alt_26;
  logic [1599:0] c$app_arg_6;
  SN512_I272_O24_B60_types::Tuple2_3 c$case_alt_27;
  SN512_I272_O24_B60_types::Tuple2_3 c$case_alt_28;
  logic [6:0] phase;
  logic [1599:0] state;
  logic tready;
  logic [273:0] inputMsg;
  logic msgValid;
  logic [4:0] counter;
  logic [4:0] counter_0;
  logic [62:0] c$ds_app_arg_0 = {3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  SN512_I272_O24_B60_types::Tuple2_4 result_9;
  SN512_I272_O24_B60_types::Tuple2_5 result_10;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_29;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_30;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_31;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_32;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_33;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_34;
  logic [11:0] b1;
  logic [11:0] b0;
  logic [11:0] b4;
  logic [11:0] b3;
  logic [11:0] b2;
  logic [11:0] b1_0;
  logic [11:0] b0_0;
  logic [11:0] b3_0;
  logic [11:0] b2_0;
  logic [11:0] b1_1;
  logic [11:0] b0_1;
  logic [11:0] b2_1;
  logic [11:0] b1_2;
  logic [11:0] b0_2;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_35;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_36;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_37;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_38;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_39;
  logic [11:0] b0_3;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_40;
  logic c$case_scrut;
  logic inValid;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_41;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_42;
  SN512_I272_O24_B60_types::Tuple2_5 c$case_alt_43;
  logic [11:0] c3;
  logic [11:0] c2;
  logic [11:0] c1;
  logic [11:0] c0;
  logic [11:0] c2_0;
  logic [11:0] c1_0;
  logic [11:0] c0_0;
  logic [11:0] c1_1;
  logic [11:0] c0_1;
  logic [11:0] c0_2;
  logic [50:0] result_11;
  logic [50:0] c$case_alt_44;
  logic [50:0] c$case_alt_45;
  logic [50:0] c$case_alt_46;
  logic [50:0] c$case_alt_47;
  logic [50:0] c$case_alt_48;
  logic [50:0] c$case_alt_49;
  logic [50:0] c$case_alt_50;
  logic [50:0] c$case_alt_51;
  logic [11:0] c0_3;
  logic [50:0] c$case_alt_52;
  logic [50:0] c$case_alt_53;
  logic c$case_scrut_0;
  logic [50:0] c$case_alt_54;
  logic [50:0] c$case_alt_55;
  logic [11:0] c1_2;
  logic [50:0] c$case_alt_56;
  logic [50:0] c$case_alt_57;
  logic c$case_scrut_1;
  logic [11:0] c2_1;
  logic c$case_scrut_2;
  logic [11:0] c3_0;
  logic [47:0] c$c0_app_arg;
  logic [47:0] chunk;
  SN512_I272_O24_B60_types::Tuple2_4 result_12;
  logic outReady;
  SN512_I272_O24_B60_types::AXI4Stream inStream;
  SN512_I272_O24_B60_types::Tuple2_6 c$arg;
  logic [273:0] c$bv;
  SN512_I272_O24_B60_types::Tuple2_7 result;
  SN512_I272_O24_B60_types::AXI4Stream_0 COEFF;

  assign c$arg = {{SEED_TDATA
                  ,SEED_TVALID
                  ,SEED_TLAST}
                 ,COEFF_TREADY};

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {{2'b00,5'bxxxxx}
  ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt_28.Tuple2_3_sel0;
    end
  end
  // register end

  assign result_0 = c$case_alt_28.Tuple2_3_sel1;

  Component_SampleNTT512B_topEntity_keccakF1600 Component_SampleNTT512B_topEntity_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (counter)
    , .x (state) );

  // replaceBit start
  always_comb begin
    result_1 = c$app_arg;
    result_1[64'sd276] = (~ (c$app_arg[64'sd276]));
  end
  // replaceBit end

  assign c$bv = (inputMsg);

  assign c$app_arg = ({1328'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,(c$bv[271 : 0])});

  // replaceBit start
  always_comb begin
    result_2 = c$app_arg_0;
    result_2[64'sd275] = (~ (c$app_arg_0[64'sd275]));
  end
  // replaceBit end

  assign c$app_arg_0 = result_1;

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_1;
    result_3[64'sd274] = (~ (c$app_arg_1[64'sd274]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_2;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_2;
    result_4[64'sd273] = (~ (c$app_arg_2[64'sd273]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_3;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_3;
    result_5[64'sd272] = (~ (c$app_arg_3[64'sd272]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_4;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_4;
    result_6[64'sd1343] = (~ (c$app_arg_4[64'sd1343]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_5;

  assign result_7 = (counter == 5'd23) ? {{{2'b10,5'd0}
                                          ,c$keccakF1600_out}
                                         ,{1'b0
                                          ,{48'b000000000000000000000000000000000000000000000000
                                           ,1'b0
                                           ,1'b0}}} : {{{2'b01,counter + 5'd1}
                                                       ,c$keccakF1600_out}
                                                      ,{1'b0
                                                       ,{48'b000000000000000000000000000000000000000000000000
                                                        ,1'b0
                                                        ,1'b0}}};

  assign c$case_alt = (counter_0 == 5'd27) ? {{2'b01,5'd0}
                                             ,state} : {{2'b10,counter_0 + 5'd1},state};

  assign c$app_arg_5 = tready ? c$case_alt : c$ds_app_arg;

  assign result_8 = (counter_0 == 5'd0) ? (c$app_arg_6[47 : 0]) : c$case_alt_0;

  assign c$case_alt_0 = (counter_0 == 5'd1) ? (c$app_arg_6[95 : 48]) : c$case_alt_1;

  assign c$case_alt_1 = (counter_0 == 5'd2) ? (c$app_arg_6[143 : 96]) : c$case_alt_2;

  assign c$case_alt_2 = (counter_0 == 5'd3) ? (c$app_arg_6[191 : 144]) : c$case_alt_3;

  assign c$case_alt_3 = (counter_0 == 5'd4) ? (c$app_arg_6[239 : 192]) : c$case_alt_4;

  assign c$case_alt_4 = (counter_0 == 5'd5) ? (c$app_arg_6[287 : 240]) : c$case_alt_5;

  assign c$case_alt_5 = (counter_0 == 5'd6) ? (c$app_arg_6[335 : 288]) : c$case_alt_6;

  assign c$case_alt_6 = (counter_0 == 5'd7) ? (c$app_arg_6[383 : 336]) : c$case_alt_7;

  assign c$case_alt_7 = (counter_0 == 5'd8) ? (c$app_arg_6[431 : 384]) : c$case_alt_8;

  assign c$case_alt_8 = (counter_0 == 5'd9) ? (c$app_arg_6[479 : 432]) : c$case_alt_9;

  assign c$case_alt_9 = (counter_0 == 5'd10) ? (c$app_arg_6[527 : 480]) : c$case_alt_10;

  assign c$case_alt_10 = (counter_0 == 5'd11) ? (c$app_arg_6[575 : 528]) : c$case_alt_11;

  assign c$case_alt_11 = (counter_0 == 5'd12) ? (c$app_arg_6[623 : 576]) : c$case_alt_12;

  assign c$case_alt_12 = (counter_0 == 5'd13) ? (c$app_arg_6[671 : 624]) : c$case_alt_13;

  assign c$case_alt_13 = (counter_0 == 5'd14) ? (c$app_arg_6[719 : 672]) : c$case_alt_14;

  assign c$case_alt_14 = (counter_0 == 5'd15) ? (c$app_arg_6[767 : 720]) : c$case_alt_15;

  assign c$case_alt_15 = (counter_0 == 5'd16) ? (c$app_arg_6[815 : 768]) : c$case_alt_16;

  assign c$case_alt_16 = (counter_0 == 5'd17) ? (c$app_arg_6[863 : 816]) : c$case_alt_17;

  assign c$case_alt_17 = (counter_0 == 5'd18) ? (c$app_arg_6[911 : 864]) : c$case_alt_18;

  assign c$case_alt_18 = (counter_0 == 5'd19) ? (c$app_arg_6[959 : 912]) : c$case_alt_19;

  assign c$case_alt_19 = (counter_0 == 5'd20) ? (c$app_arg_6[1007 : 960]) : c$case_alt_20;

  assign c$case_alt_20 = (counter_0 == 5'd21) ? (c$app_arg_6[1055 : 1008]) : c$case_alt_21;

  assign c$case_alt_21 = (counter_0 == 5'd22) ? (c$app_arg_6[1103 : 1056]) : c$case_alt_22;

  assign c$case_alt_22 = (counter_0 == 5'd23) ? (c$app_arg_6[1151 : 1104]) : c$case_alt_23;

  assign c$case_alt_23 = (counter_0 == 5'd24) ? (c$app_arg_6[1199 : 1152]) : c$case_alt_24;

  assign c$case_alt_24 = (counter_0 == 5'd25) ? (c$app_arg_6[1247 : 1200]) : c$case_alt_25;

  assign c$case_alt_25 = (counter_0 == 5'd26) ? (c$app_arg_6[1295 : 1248]) : c$case_alt_26;

  assign c$case_alt_26 = (counter_0 == 5'd27) ? (c$app_arg_6[1343 : 1296]) : ({48 {1'bx}});

  assign c$app_arg_6 = state;

  assign c$case_alt_27 = msgValid ? {{{2'b01,5'd0}
                                     ,result_6}
                                    ,{1'b0
                                     ,{48'b000000000000000000000000000000000000000000000000
                                      ,1'b0
                                      ,1'b0}}} : {c$ds_app_arg
                                                 ,{1'b1
                                                  ,{48'b000000000000000000000000000000000000000000000000
                                                   ,1'b0
                                                   ,1'b0}}};

  always_comb begin
    case(phase[6:5])
      2'b00 : c$case_alt_28 = c$case_alt_27;
      2'b01 : c$case_alt_28 = result_7;
      default : c$case_alt_28 = {c$app_arg_5
                                ,{1'b0,{result_8,1'b1,1'b0}}};
    endcase
  end

  assign phase = c$ds_app_arg.State_sel0;

  assign state = c$ds_app_arg.State_sel1;

  assign tready = result_9.Tuple2_4_sel0;

  assign inputMsg = {2'b00,inStream.AXI4Stream_sel0};

  assign msgValid = inStream.AXI4Stream_sel1;

  assign counter = phase[4:0];

  assign counter_0 = phase[4:0];

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_0_register
    if ( RST) begin
      c$ds_app_arg_0 <= {3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds_app_arg_0 <= result_10.Tuple2_5_sel0;
    end
  end
  // register end

  assign result_9 = result_10.Tuple2_5_sel1;

  always_comb begin
    case(c$ds_app_arg_0[62:60])
      3'b000 : result_10 = c$case_alt_34;
      3'b001 : result_10 = c$case_alt_33;
      3'b010 : result_10 = c$case_alt_32;
      3'b011 : result_10 = c$case_alt_31;
      3'b100 : result_10 = c$case_alt_30;
      default : result_10 = c$case_alt_29;
    endcase
  end

  assign c$case_alt_29 = inValid ? {{3'b011,b2,b3,b4,24'bxxxxxxxxxxxxxxxxxxxxxxxx}
                                   ,{1'b0,{{b1,b0},1'b1,1'b0}}} : {c$ds_app_arg_0
                                                                  ,{1'b1
                                                                   ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_30 = inValid ? {{3'b010,b2_0,b3_0,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                   ,{1'b0
                                    ,{{b1_0,b0_0},1'b1,1'b0}}} : {c$ds_app_arg_0
                                                                 ,{1'b1
                                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_31 = inValid ? {{3'b001,b2_1,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                   ,{1'b0
                                    ,{{b1_1,b0_1},1'b1,1'b0}}} : {c$ds_app_arg_0
                                                                 ,{1'b1
                                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_32 = inValid ? {{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                   ,{1'b0
                                    ,{{b1_2,b0_2},1'b1,1'b0}}} : {c$ds_app_arg_0
                                                                 ,{1'b1
                                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_33 = c$case_scrut ? {c$ds_app_arg_0
                                        ,{1'b1
                                         ,{24'b000000000000000000000000
                                          ,1'b0
                                          ,1'b0}}} : c$case_alt_35;

  assign c$case_alt_34 = c$case_scrut ? {{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                        ,{1'b1
                                         ,{24'b000000000000000000000000
                                          ,1'b0
                                          ,1'b0}}} : c$case_alt_40;

  assign b1 = c$ds_app_arg_0[47:36];

  assign b0 = c$ds_app_arg_0[59:48];

  assign b4 = c$ds_app_arg_0[11:0];

  assign b3 = c$ds_app_arg_0[23:12];

  assign b2 = c$ds_app_arg_0[35:24];

  assign b1_0 = c$ds_app_arg_0[47:36];

  assign b0_0 = c$ds_app_arg_0[59:48];

  assign b3_0 = c$ds_app_arg_0[23:12];

  assign b2_0 = c$ds_app_arg_0[35:24];

  assign b1_1 = c$ds_app_arg_0[47:36];

  assign b0_1 = c$ds_app_arg_0[59:48];

  assign b2_1 = c$ds_app_arg_0[35:24];

  assign b1_2 = c$ds_app_arg_0[47:36];

  assign b0_2 = c$ds_app_arg_0[59:48];

  always_comb begin
    case(result_11[50:48])
      3'b000 : c$case_alt_35 = {c$ds_app_arg_0
                               ,{1'b1
                                ,{24'b000000000000000000000000,1'b0,1'b0}}};
      3'b001 : c$case_alt_35 = c$case_alt_39;
      3'b010 : c$case_alt_35 = c$case_alt_38;
      3'b011 : c$case_alt_35 = c$case_alt_37;
      default : c$case_alt_35 = c$case_alt_36;
    endcase
  end

  assign c$case_alt_36 = outReady ? {{3'b011,c1,c2,c3,24'bxxxxxxxxxxxxxxxxxxxxxxxx}
                                    ,{1'b1
                                     ,{{c0,b0_3}
                                      ,1'b1
                                      ,1'b0}}} : {{3'b101,b0_3,c0,c1,c2,c3}
                                                 ,{1'b1
                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_37 = outReady ? {{3'b010,c1_0,c2_0,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                    ,{1'b1
                                     ,{{c0_0,b0_3}
                                      ,1'b1
                                      ,1'b0}}} : {{3'b100,b0_3,c0_0,c1_0,c2_0,12'bxxxxxxxxxxxx}
                                                 ,{1'b1
                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_38 = outReady ? {{3'b001,c1_1,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                    ,{1'b1
                                     ,{{c0_1,b0_3}
                                      ,1'b1
                                      ,1'b0}}} : {{3'b011,b0_3,c0_1,c1_1,24'bxxxxxxxxxxxxxxxxxxxxxxxx}
                                                 ,{1'b1
                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_39 = outReady ? {{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                    ,{1'b1
                                     ,{{c0_2,b0_3}
                                      ,1'b1
                                      ,1'b0}}} : {{3'b010,b0_3,c0_2,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                                 ,{1'b1
                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign b0_3 = c$ds_app_arg_0[59:48];

  always_comb begin
    case(result_11[50:48])
      3'b000 : c$case_alt_40 = {{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                               ,{1'b1
                                ,{24'b000000000000000000000000,1'b0,1'b0}}};
      3'b001 : c$case_alt_40 = {{3'b001,c0_2,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                               ,{1'b1
                                ,{24'b000000000000000000000000,1'b0,1'b0}}};
      3'b010 : c$case_alt_40 = c$case_alt_43;
      3'b011 : c$case_alt_40 = c$case_alt_42;
      default : c$case_alt_40 = c$case_alt_41;
    endcase
  end

  assign c$case_scrut = ~ inValid;

  assign inValid = result_0[1:1];

  assign c$case_alt_41 = outReady ? {{3'b010,c2,c3,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                    ,{1'b1
                                     ,{{c1,c0}
                                      ,1'b1
                                      ,1'b0}}} : {{3'b100,c0,c1,c2,c3,12'bxxxxxxxxxxxx}
                                                 ,{1'b1
                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_42 = outReady ? {{3'b001,c2_0,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                    ,{1'b1
                                     ,{{c1_0,c0_0}
                                      ,1'b1
                                      ,1'b0}}} : {{3'b011,c0_0,c1_0,c2_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx}
                                                 ,{1'b1
                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c$case_alt_43 = outReady ? {{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                    ,{1'b1
                                     ,{{c1_1,c0_1}
                                      ,1'b1
                                      ,1'b0}}} : {{3'b010,c0_1,c1_1,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                                 ,{1'b1
                                                  ,{24'b000000000000000000000000,1'b0,1'b0}}};

  assign c3 = result_11[11:0];

  assign c2 = result_11[23:12];

  assign c1 = result_11[35:24];

  assign c0 = result_11[47:36];

  assign c2_0 = result_11[23:12];

  assign c1_0 = result_11[35:24];

  assign c0_0 = result_11[47:36];

  assign c1_1 = result_11[35:24];

  assign c0_1 = result_11[47:36];

  assign c0_2 = result_11[47:36];

  assign result_11 = (c0_3 < 12'b110100000001) ? c$case_alt_44 : c$case_alt_45;

  assign c$case_alt_44 = c$case_scrut_0 ? c$case_alt_46 : c$case_alt_47;

  assign c$case_alt_45 = c$case_scrut_0 ? c$case_alt_52 : c$case_alt_53;

  assign c$case_alt_46 = c$case_scrut_1 ? c$case_alt_48 : c$case_alt_49;

  assign c$case_alt_47 = c$case_scrut_1 ? c$case_alt_50 : c$case_alt_51;

  assign c$case_alt_48 = c$case_scrut_2 ? {3'b100,c0_3,c1_2,c2_1,c3_0} : {3'b011,c0_3,c1_2,c2_1,12'bxxxxxxxxxxxx};

  assign c$case_alt_49 = c$case_scrut_2 ? {3'b011,c0_3,c1_2,c3_0,12'bxxxxxxxxxxxx} : {3'b010,c0_3,c1_2,24'bxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_50 = c$case_scrut_2 ? {3'b011,c0_3,c2_1,c3_0,12'bxxxxxxxxxxxx} : {3'b010,c0_3,c2_1,24'bxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_51 = c$case_scrut_2 ? {3'b010,c0_3,c3_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b001,c0_3,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c0_3 = c$c0_app_arg[11 : 0];

  assign c$case_alt_52 = c$case_scrut_1 ? c$case_alt_54 : c$case_alt_55;

  assign c$case_alt_53 = c$case_scrut_1 ? c$case_alt_56 : c$case_alt_57;

  assign c$case_scrut_0 = c1_2 < 12'b110100000001;

  assign c$case_alt_54 = c$case_scrut_2 ? {3'b011,c1_2,c2_1,c3_0,12'bxxxxxxxxxxxx} : {3'b010,c1_2,c2_1,24'bxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_55 = c$case_scrut_2 ? {3'b010,c1_2,c3_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b001,c1_2,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c1_2 = c$c0_app_arg[23 : 12];

  assign c$case_alt_56 = c$case_scrut_2 ? {3'b010,c2_1,c3_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b001,c2_1,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_57 = c$case_scrut_2 ? {3'b001,c3_0,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b000,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_scrut_1 = c2_1 < 12'b110100000001;

  assign c2_1 = c$c0_app_arg[35 : 24];

  assign c$case_scrut_2 = c3_0 < 12'b110100000001;

  assign c3_0 = c$c0_app_arg[47 : 36];

  assign c$c0_app_arg = chunk;

  assign chunk = result_0[49:2];

  assign result_12 = {result_0.Tuple2_2_sel0
                     ,result_9.Tuple2_4_sel1};

  assign outReady = c$arg.Tuple2_6_sel1;

  assign inStream = c$arg.Tuple2_6_sel0;

  assign result = {result_12.Tuple2_4_sel1
                  ,result_12.Tuple2_4_sel0};

  assign COEFF = result.Tuple2_7_sel0;

  assign SEED_TREADY = result.Tuple2_7_sel1;

  assign COEFF_TDATA = COEFF.AXI4Stream_0_sel0;

  assign COEFF_TVALID = COEFF.AXI4Stream_0_sel1;

  assign COEFF_TLAST = COEFF.AXI4Stream_0_sel2;


endmodule

