/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Hash_NonPipelined_SHAKE128_topEntity_spongeFSM
    ( // Inputs
      input wire logic c$bindCsr  // clock
    , input wire logic c$bindCsr_0  // reset
    , input wire logic c$bindCsr_1  // enable
    , input wire SHAKE_128_NonPipelined_types::Tuple3_0 eta1

      // Outputs
    , output SHAKE_128_NonPipelined_types::Tuple2_1 result
    );
  logic [63:0] result_0;
  logic [63:0] c$case_alt;
  logic [63:0] c$case_alt_0;
  logic [63:0] c$case_alt_1;
  logic [63:0] c$case_alt_2;
  logic [63:0] c$case_alt_3;
  logic [63:0] c$case_alt_4;
  logic [63:0] c$case_alt_5;
  logic [63:0] c$case_alt_6;
  logic [63:0] c$case_alt_7;
  logic [63:0] c$case_alt_8;
  logic [63:0] c$case_alt_9;
  logic [63:0] c$case_alt_10;
  logic [63:0] c$case_alt_11;
  logic [63:0] c$case_alt_12;
  logic [63:0] c$case_alt_13;
  logic [63:0] c$case_alt_14;
  logic [63:0] c$case_alt_15;
  logic [63:0] c$case_alt_16;
  logic [63:0] c$case_alt_17;
  logic [1599:0] c$app_arg;
  logic [1599:0] state;
  SHAKE_128_NonPipelined_types::State ds1 = {{2'b00,5'd0,2'bxx}
,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
  SHAKE_128_NonPipelined_types::Tuple2 c$ds_case_alt;
  SHAKE_128_NonPipelined_types::Tuple2 result_1;
  SHAKE_128_NonPipelined_types::State c$ds_app_arg;
  SHAKE_128_NonPipelined_types::State c$ds_app_arg_0;
  logic [4:0] counter;
  SHAKE_128_NonPipelined_types::Tuple2 c$ds_case_alt_0;
  logic tready;
  logic [1:0] seenTLAST;
  logic [4:0] counter_0;
  SHAKE_128_NonPipelined_types::Tuple2 result_2;
  SHAKE_128_NonPipelined_types::Tuple2 c$case_alt_18;
  SHAKE_128_NonPipelined_types::Tuple2 c$case_alt_19;
  SHAKE_128_NonPipelined_types::Tuple2 result_3;
  SHAKE_128_NonPipelined_types::Tuple2 c$case_alt_20;
  logic c$app_arg_0;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_5;
  logic signed [63:0] c$app_arg_2;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_6;
  logic signed [63:0] c$app_arg_4;
  logic [1599:0] c$app_arg_5;
  logic [1599:0] result_7;
  logic signed [63:0] c$app_arg_6;
  logic [1599:0] c$app_arg_7;
  logic [1599:0] result_8;
  logic signed [63:0] c$app_arg_8;
  logic [1599:0] c$app_arg_9;
  logic [1599:0] result_9;
  logic signed [63:0] c$app_arg_10;
  logic [1599:0] c$app_arg_11;
  logic [10:0] c$complementAt1_arg0;
  logic [10:0] c$complementAt1_arg0_case_alt;
  logic [10:0] c$complementAt1_arg0_case_alt_0;
  logic [10:0] c$complementAt1_arg0_case_alt_1;
  logic [10:0] c$complementAt1_arg0_case_alt_2;
  logic [10:0] c$complementAt1_arg0_case_alt_3;
  logic [10:0] c$complementAt1_arg0_case_alt_4;
  logic [10:0] c$complementAt1_arg0_case_alt_5;
  logic [10:0] c$complementAt1_arg0_case_alt_6;
  logic [10:0] c$complementAt1_arg0_case_alt_7;
  logic [10:0] c$complementAt1_arg0_case_alt_8;
  logic [10:0] c$complementAt1_arg0_case_alt_9;
  logic [10:0] c$complementAt1_arg0_case_alt_10;
  logic [10:0] c$complementAt1_arg0_case_alt_11;
  logic [10:0] c$complementAt1_arg0_case_alt_12;
  logic [10:0] c$complementAt1_arg0_case_alt_13;
  logic [10:0] c$complementAt1_arg0_case_alt_14;
  logic [10:0] c$complementAt1_arg0_case_alt_15;
  logic [10:0] c$complementAt1_arg0_case_alt_16;
  logic [10:0] c$complementAt1_arg0_case_alt_17;
  logic [10:0] c$complementAt1_arg0_case_alt_18;
  logic [10:0] c$complementAt1_arg0_0;
  logic [10:0] c$complementAt1_arg0_case_alt_19;
  logic [10:0] c$complementAt1_arg0_case_alt_20;
  logic [10:0] c$complementAt1_arg0_case_alt_21;
  logic [10:0] c$complementAt1_arg0_case_alt_22;
  logic [10:0] c$complementAt1_arg0_case_alt_23;
  logic [10:0] c$complementAt1_arg0_case_alt_24;
  logic [10:0] c$complementAt1_arg0_case_alt_25;
  logic [10:0] c$complementAt1_arg0_case_alt_26;
  logic [10:0] c$complementAt1_arg0_case_alt_27;
  logic [10:0] c$complementAt1_arg0_case_alt_28;
  logic [10:0] c$complementAt1_arg0_case_alt_29;
  logic [10:0] c$complementAt1_arg0_case_alt_30;
  logic [10:0] c$complementAt1_arg0_case_alt_31;
  logic [10:0] c$complementAt1_arg0_case_alt_32;
  logic [10:0] c$complementAt1_arg0_case_alt_33;
  logic [10:0] c$complementAt1_arg0_case_alt_34;
  logic [10:0] c$complementAt1_arg0_case_alt_35;
  logic [10:0] c$complementAt1_arg0_case_alt_36;
  logic [10:0] c$complementAt1_arg0_case_alt_37;
  logic [10:0] c$complementAt1_arg0_case_alt_38;
  logic [10:0] c$complementAt1_arg0_1;
  logic [10:0] c$complementAt1_arg0_case_alt_39;
  logic [10:0] c$complementAt1_arg0_case_alt_40;
  logic [10:0] c$complementAt1_arg0_case_alt_41;
  logic [10:0] c$complementAt1_arg0_case_alt_42;
  logic [10:0] c$complementAt1_arg0_case_alt_43;
  logic [10:0] c$complementAt1_arg0_case_alt_44;
  logic [10:0] c$complementAt1_arg0_case_alt_45;
  logic [10:0] c$complementAt1_arg0_case_alt_46;
  logic [10:0] c$complementAt1_arg0_case_alt_47;
  logic [10:0] c$complementAt1_arg0_case_alt_48;
  logic [10:0] c$complementAt1_arg0_case_alt_49;
  logic [10:0] c$complementAt1_arg0_case_alt_50;
  logic [10:0] c$complementAt1_arg0_case_alt_51;
  logic [10:0] c$complementAt1_arg0_case_alt_52;
  logic [10:0] c$complementAt1_arg0_case_alt_53;
  logic [10:0] c$complementAt1_arg0_case_alt_54;
  logic [10:0] c$complementAt1_arg0_case_alt_55;
  logic [10:0] c$complementAt1_arg0_case_alt_56;
  logic [10:0] c$complementAt1_arg0_case_alt_57;
  logic [10:0] c$complementAt1_arg0_case_alt_58;
  logic [10:0] c$complementAt1_arg0_2;
  logic [10:0] c$complementAt1_arg0_case_alt_59;
  logic [10:0] c$complementAt1_arg0_case_alt_60;
  logic [10:0] c$complementAt1_arg0_case_alt_61;
  logic [10:0] c$complementAt1_arg0_case_alt_62;
  logic [10:0] c$complementAt1_arg0_case_alt_63;
  logic [10:0] c$complementAt1_arg0_case_alt_64;
  logic [10:0] c$complementAt1_arg0_case_alt_65;
  logic [10:0] c$complementAt1_arg0_case_alt_66;
  logic [10:0] c$complementAt1_arg0_case_alt_67;
  logic [10:0] c$complementAt1_arg0_case_alt_68;
  logic [10:0] c$complementAt1_arg0_case_alt_69;
  logic [10:0] c$complementAt1_arg0_case_alt_70;
  logic [10:0] c$complementAt1_arg0_case_alt_71;
  logic [10:0] c$complementAt1_arg0_case_alt_72;
  logic [10:0] c$complementAt1_arg0_case_alt_73;
  logic [10:0] c$complementAt1_arg0_case_alt_74;
  logic [10:0] c$complementAt1_arg0_case_alt_75;
  logic [10:0] c$complementAt1_arg0_case_alt_76;
  logic [10:0] c$complementAt1_arg0_case_alt_77;
  logic [10:0] c$complementAt1_arg0_case_alt_78;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn;
  logic c$complementAt1_tupIn_case_scrut;
  SHAKE_128_NonPipelined_types::Tuple2_0 result_10;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_0;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_1;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_2;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_3;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_4;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_5;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_6;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_7;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_8;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_9;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_10;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_11;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_12;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_13;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_14;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_15;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_16;
  SHAKE_128_NonPipelined_types::Tuple2_0 c$complementAt1_tupIn_case_alt_17;
  logic c$complementAt1_tupIn_case_scrut_0;
  logic c$complementAt1_tupIn_case_scrut_1;
  logic c$complementAt1_tupIn_case_scrut_2;
  logic c$complementAt1_tupIn_case_scrut_3;
  logic c$complementAt1_tupIn_case_scrut_4;
  logic c$complementAt1_tupIn_case_scrut_5;
  logic c$complementAt1_tupIn_case_scrut_6;
  logic c$complementAt1_tupIn_case_scrut_7;
  logic c$complementAt1_tupIn_case_scrut_8;
  logic c$complementAt1_tupIn_case_scrut_9;
  logic c$complementAt1_tupIn_case_scrut_10;
  logic c$complementAt1_tupIn_case_scrut_11;
  logic c$complementAt1_tupIn_case_scrut_12;
  logic c$complementAt1_tupIn_case_scrut_13;
  logic c$complementAt1_tupIn_case_scrut_14;
  logic c$complementAt1_tupIn_case_scrut_15;
  logic c$complementAt1_tupIn_case_scrut_16;
  logic c$complementAt1_tupIn_case_scrut_17;
  logic c$complementAt1_tupIn_case_scrut_18;
  logic c$complementAt1_tupIn_case_scrut_19;
  logic [1599:0] result_11;
  logic [1599:0] c$case_alt_21;
  logic [1599:0] c$case_alt_22;
  logic [1599:0] c$case_alt_23;
  logic [1599:0] c$case_alt_24;
  logic [1599:0] c$case_alt_25;
  logic [1599:0] c$case_alt_26;
  logic [1599:0] c$case_alt_27;
  logic [1599:0] c$case_alt_28;
  logic [1599:0] c$case_alt_29;
  logic [1599:0] c$case_alt_30;
  logic [1599:0] c$case_alt_31;
  logic [1599:0] c$case_alt_32;
  logic [1599:0] c$case_alt_33;
  logic [1599:0] c$case_alt_34;
  logic [1599:0] c$case_alt_35;
  logic [1599:0] c$case_alt_36;
  logic [1599:0] c$case_alt_37;
  logic [1599:0] c$case_alt_38;
  logic [1599:0] c$case_alt_39;
  logic [1599:0] c$case_alt_40;
  logic [1599:0] c$case_alt_41;
  logic [1599:0] c$case_alt_42;
  logic [1599:0] c$case_alt_43;
  logic [1599:0] c$case_alt_44;
  logic [1599:0] c$case_alt_45;
  logic [1599:0] c$case_alt_46;
  logic [1599:0] c$case_alt_47;
  logic [1599:0] c$case_alt_48;
  logic [1599:0] c$case_alt_49;
  logic [1599:0] c$case_alt_50;
  logic [1599:0] c$case_alt_51;
  logic [1599:0] c$case_alt_52;
  logic [1599:0] c$case_alt_53;
  logic [1599:0] c$case_alt_54;
  logic [1599:0] c$case_alt_55;
  logic [1599:0] c$case_alt_56;
  logic [1599:0] c$case_alt_57;
  logic [1599:0] c$case_alt_58;
  logic [1599:0] c$case_alt_59;
  logic [1599:0] c$case_alt_60;
  logic [1599:0] c$case_alt_61;
  logic [1599:0] c$app_arg_12;
  logic flush;
  SHAKE_128_NonPipelined_types::AXI4Stream \input ;
  logic [4:0] counter_1;
  logic [8:0] c$ds_case_alt_selection_1;
  logic [10:0] c$i_39;

  assign result = c$ds_case_alt.Tuple2_sel1;

  assign result_0 = (counter == 5'd0) ? (c$app_arg[1599 : 1536]) : c$case_alt;

  assign c$case_alt = (counter == 5'd1) ? (c$app_arg[1535 : 1472]) : c$case_alt_0;

  assign c$case_alt_0 = (counter == 5'd2) ? (c$app_arg[1471 : 1408]) : c$case_alt_1;

  assign c$case_alt_1 = (counter == 5'd3) ? (c$app_arg[1407 : 1344]) : c$case_alt_2;

  assign c$case_alt_2 = (counter == 5'd4) ? (c$app_arg[1343 : 1280]) : c$case_alt_3;

  assign c$case_alt_3 = (counter == 5'd5) ? (c$app_arg[1279 : 1216]) : c$case_alt_4;

  assign c$case_alt_4 = (counter == 5'd6) ? (c$app_arg[1215 : 1152]) : c$case_alt_5;

  assign c$case_alt_5 = (counter == 5'd7) ? (c$app_arg[1151 : 1088]) : c$case_alt_6;

  assign c$case_alt_6 = (counter == 5'd8) ? (c$app_arg[1087 : 1024]) : c$case_alt_7;

  assign c$case_alt_7 = (counter == 5'd9) ? (c$app_arg[1023 : 960]) : c$case_alt_8;

  assign c$case_alt_8 = (counter == 5'd10) ? (c$app_arg[959 : 896]) : c$case_alt_9;

  assign c$case_alt_9 = (counter == 5'd11) ? (c$app_arg[895 : 832]) : c$case_alt_10;

  assign c$case_alt_10 = (counter == 5'd12) ? (c$app_arg[831 : 768]) : c$case_alt_11;

  assign c$case_alt_11 = (counter == 5'd13) ? (c$app_arg[767 : 704]) : c$case_alt_12;

  assign c$case_alt_12 = (counter == 5'd14) ? (c$app_arg[703 : 640]) : c$case_alt_13;

  assign c$case_alt_13 = (counter == 5'd15) ? (c$app_arg[639 : 576]) : c$case_alt_14;

  assign c$case_alt_14 = (counter == 5'd16) ? (c$app_arg[575 : 512]) : c$case_alt_15;

  assign c$case_alt_15 = (counter == 5'd17) ? (c$app_arg[511 : 448]) : c$case_alt_16;

  assign c$case_alt_16 = (counter == 5'd18) ? (c$app_arg[447 : 384]) : c$case_alt_17;

  assign c$case_alt_17 = (counter == 5'd19) ? (c$app_arg[383 : 320]) : (c$app_arg[319 : 256]);

  assign c$app_arg = state;

  assign state = ds1.State_sel1;

  // register begin
  always_ff @(posedge c$bindCsr or  posedge  c$bindCsr_0) begin : ds1_register
    if ( c$bindCsr_0) begin
      ds1 <= {{2'b00,5'd0,2'bxx}
  ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
    end else  if (c$bindCsr_1)  begin
      ds1 <= c$ds_case_alt.Tuple2_sel0;
    end
  end
  // register end

  assign c$ds_case_alt_selection_1 = ds1.State_sel0;

  always_comb begin
    case(c$ds_case_alt_selection_1[8:7])
      2'b00 : c$ds_case_alt = result_2;
      2'b01 : c$ds_case_alt = c$ds_case_alt_0;
      default : c$ds_case_alt = result_1;
    endcase
  end

  assign result_1 = (counter == 5'd20) ? {c$ds_app_arg
                                         ,{{result_0,1'b1,1'b0},1'b0}} : {c$ds_app_arg_0
                                                                         ,{{result_0,1'b1,1'b0},1'b0}};

  assign c$ds_app_arg = tready ? {{2'b01,5'd0,2'd0}
                                 ,state} : {{2'b10,5'd20,2'bxx},state};

  assign c$ds_app_arg_0 = tready ? {{2'b10,counter + 5'd1,2'bxx}
                                   ,state} : ds1;

  assign counter = ds1[1606:1602];

  Hash_NonPipelined_SHAKE128_topEntity_pad Hash_NonPipelined_SHAKE128_topEntity_pad_c$ds_case_alt_0
    ( .result (c$ds_case_alt_0)
    , .eta2 (counter_0)
    , .eta3 (seenTLAST)
    , .eta4 (state)
    , .eta5 (tready) );

  assign tready = eta1.Tuple3_0_sel1;

  assign seenTLAST = ds1[1601:1600];

  assign counter_0 = ds1[1606:1602];

  assign result_2 = c$complementAt1_tupIn_case_scrut ? {{{2'b01,5'd0,2'd0}
                                                        ,result_4}
                                                       ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                         ,1'b0
                                                         ,1'b0}
                                                        ,1'b0}} : c$case_alt_18;

  assign c$case_alt_18 = (~ \input .AXI4Stream_sel1) ? {{{2'b00,counter_1,2'bxx}
                                                        ,state}
                                                       ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                         ,1'b0
                                                         ,1'b0}
                                                        ,1'b1}} : c$case_alt_19;

  assign c$case_alt_19 = (\input .AXI4Stream_sel2 & c$app_arg_0) ? {{{2'b01,5'd0,2'd0}
                                                                    ,result_4}
                                                                   ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                                     ,1'b0
                                                                     ,1'b0}
                                                                    ,1'b0}} : result_3;

  assign result_3 = \input .AXI4Stream_sel2 ? {{{2'b01,5'd0,2'd1}
                                               ,result_11}
                                              ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                ,1'b0
                                                ,1'b0}
                                               ,1'b0}} : c$case_alt_20;

  assign c$case_alt_20 = c$app_arg_0 ? {{{2'b00,counter_1 + 5'd1,2'bxx}
                                        ,result_11}
                                       ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                         ,1'b0
                                         ,1'b0}
                                        ,1'b1}} : {{{2'b01,5'd0,2'd2},result_11}
                                                  ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                    ,1'b0
                                                    ,1'b0}
                                                   ,1'b0}};

  assign c$app_arg_0 = counter_1 < 5'd20;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_1;
    result_4[64'sd256] = (~ (c$app_arg_1[64'sd256]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_3;
    result_5[c$app_arg_2] = (~ (c$app_arg_3[c$app_arg_2]));
  end
  // replaceBit end

  assign c$app_arg_2 = $unsigned({{(64-11) {1'b0}},c$complementAt1_arg0});

  assign c$app_arg_3 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_5;
    result_6[c$app_arg_4] = (~ (c$app_arg_5[c$app_arg_4]));
  end
  // replaceBit end

  assign c$app_arg_4 = $unsigned({{(64-11) {1'b0}},c$complementAt1_arg0_0});

  assign c$app_arg_5 = result_7;

  // replaceBit start
  always_comb begin
    result_7 = c$app_arg_7;
    result_7[c$app_arg_6] = (~ (c$app_arg_7[c$app_arg_6]));
  end
  // replaceBit end

  assign c$app_arg_6 = $unsigned({{(64-11) {1'b0}},c$complementAt1_arg0_1});

  assign c$app_arg_7 = result_8;

  // replaceBit start
  always_comb begin
    result_8 = c$app_arg_9;
    result_8[c$app_arg_8] = (~ (c$app_arg_9[c$app_arg_8]));
  end
  // replaceBit end

  assign c$app_arg_8 = $unsigned({{(64-11) {1'b0}},c$complementAt1_arg0_2});

  assign c$app_arg_9 = result_9;

  // replaceBit start
  always_comb begin
    result_9 = c$app_arg_11;
    result_9[c$app_arg_10] = (~ (c$app_arg_11[c$app_arg_10]));
  end
  // replaceBit end

  assign c$i_39 = c$complementAt1_tupIn.Tuple2_0_sel0;

  assign c$app_arg_10 = $unsigned({{(64-11) {1'b0}},c$i_39});

  assign c$app_arg_11 = c$complementAt1_tupIn.Tuple2_0_sel1;

  assign c$complementAt1_arg0 = c$complementAt1_tupIn_case_scrut ? 11'd1595 : c$complementAt1_arg0_case_alt;

  assign c$complementAt1_arg0_case_alt = c$complementAt1_tupIn_case_scrut_19 ? 11'd1531 : c$complementAt1_arg0_case_alt_0;

  assign c$complementAt1_arg0_case_alt_0 = c$complementAt1_tupIn_case_scrut_18 ? 11'd1467 : c$complementAt1_arg0_case_alt_1;

  assign c$complementAt1_arg0_case_alt_1 = c$complementAt1_tupIn_case_scrut_17 ? 11'd1403 : c$complementAt1_arg0_case_alt_2;

  assign c$complementAt1_arg0_case_alt_2 = c$complementAt1_tupIn_case_scrut_16 ? 11'd1339 : c$complementAt1_arg0_case_alt_3;

  assign c$complementAt1_arg0_case_alt_3 = c$complementAt1_tupIn_case_scrut_15 ? 11'd1275 : c$complementAt1_arg0_case_alt_4;

  assign c$complementAt1_arg0_case_alt_4 = c$complementAt1_tupIn_case_scrut_14 ? 11'd1211 : c$complementAt1_arg0_case_alt_5;

  assign c$complementAt1_arg0_case_alt_5 = c$complementAt1_tupIn_case_scrut_13 ? 11'd1147 : c$complementAt1_arg0_case_alt_6;

  assign c$complementAt1_arg0_case_alt_6 = c$complementAt1_tupIn_case_scrut_12 ? 11'd1083 : c$complementAt1_arg0_case_alt_7;

  assign c$complementAt1_arg0_case_alt_7 = c$complementAt1_tupIn_case_scrut_11 ? 11'd1019 : c$complementAt1_arg0_case_alt_8;

  assign c$complementAt1_arg0_case_alt_8 = c$complementAt1_tupIn_case_scrut_10 ? 11'd955 : c$complementAt1_arg0_case_alt_9;

  assign c$complementAt1_arg0_case_alt_9 = c$complementAt1_tupIn_case_scrut_9 ? 11'd891 : c$complementAt1_arg0_case_alt_10;

  assign c$complementAt1_arg0_case_alt_10 = c$complementAt1_tupIn_case_scrut_8 ? 11'd827 : c$complementAt1_arg0_case_alt_11;

  assign c$complementAt1_arg0_case_alt_11 = c$complementAt1_tupIn_case_scrut_7 ? 11'd763 : c$complementAt1_arg0_case_alt_12;

  assign c$complementAt1_arg0_case_alt_12 = c$complementAt1_tupIn_case_scrut_6 ? 11'd699 : c$complementAt1_arg0_case_alt_13;

  assign c$complementAt1_arg0_case_alt_13 = c$complementAt1_tupIn_case_scrut_5 ? 11'd635 : c$complementAt1_arg0_case_alt_14;

  assign c$complementAt1_arg0_case_alt_14 = c$complementAt1_tupIn_case_scrut_4 ? 11'd571 : c$complementAt1_arg0_case_alt_15;

  assign c$complementAt1_arg0_case_alt_15 = c$complementAt1_tupIn_case_scrut_3 ? 11'd507 : c$complementAt1_arg0_case_alt_16;

  assign c$complementAt1_arg0_case_alt_16 = c$complementAt1_tupIn_case_scrut_2 ? 11'd443 : c$complementAt1_arg0_case_alt_17;

  assign c$complementAt1_arg0_case_alt_17 = c$complementAt1_tupIn_case_scrut_1 ? 11'd379 : c$complementAt1_arg0_case_alt_18;

  assign c$complementAt1_arg0_case_alt_18 = c$complementAt1_tupIn_case_scrut_0 ? 11'd315 : 11'd1595;

  assign c$complementAt1_arg0_0 = c$complementAt1_tupIn_case_scrut ? 11'd1596 : c$complementAt1_arg0_case_alt_19;

  assign c$complementAt1_arg0_case_alt_19 = c$complementAt1_tupIn_case_scrut_19 ? 11'd1532 : c$complementAt1_arg0_case_alt_20;

  assign c$complementAt1_arg0_case_alt_20 = c$complementAt1_tupIn_case_scrut_18 ? 11'd1468 : c$complementAt1_arg0_case_alt_21;

  assign c$complementAt1_arg0_case_alt_21 = c$complementAt1_tupIn_case_scrut_17 ? 11'd1404 : c$complementAt1_arg0_case_alt_22;

  assign c$complementAt1_arg0_case_alt_22 = c$complementAt1_tupIn_case_scrut_16 ? 11'd1340 : c$complementAt1_arg0_case_alt_23;

  assign c$complementAt1_arg0_case_alt_23 = c$complementAt1_tupIn_case_scrut_15 ? 11'd1276 : c$complementAt1_arg0_case_alt_24;

  assign c$complementAt1_arg0_case_alt_24 = c$complementAt1_tupIn_case_scrut_14 ? 11'd1212 : c$complementAt1_arg0_case_alt_25;

  assign c$complementAt1_arg0_case_alt_25 = c$complementAt1_tupIn_case_scrut_13 ? 11'd1148 : c$complementAt1_arg0_case_alt_26;

  assign c$complementAt1_arg0_case_alt_26 = c$complementAt1_tupIn_case_scrut_12 ? 11'd1084 : c$complementAt1_arg0_case_alt_27;

  assign c$complementAt1_arg0_case_alt_27 = c$complementAt1_tupIn_case_scrut_11 ? 11'd1020 : c$complementAt1_arg0_case_alt_28;

  assign c$complementAt1_arg0_case_alt_28 = c$complementAt1_tupIn_case_scrut_10 ? 11'd956 : c$complementAt1_arg0_case_alt_29;

  assign c$complementAt1_arg0_case_alt_29 = c$complementAt1_tupIn_case_scrut_9 ? 11'd892 : c$complementAt1_arg0_case_alt_30;

  assign c$complementAt1_arg0_case_alt_30 = c$complementAt1_tupIn_case_scrut_8 ? 11'd828 : c$complementAt1_arg0_case_alt_31;

  assign c$complementAt1_arg0_case_alt_31 = c$complementAt1_tupIn_case_scrut_7 ? 11'd764 : c$complementAt1_arg0_case_alt_32;

  assign c$complementAt1_arg0_case_alt_32 = c$complementAt1_tupIn_case_scrut_6 ? 11'd700 : c$complementAt1_arg0_case_alt_33;

  assign c$complementAt1_arg0_case_alt_33 = c$complementAt1_tupIn_case_scrut_5 ? 11'd636 : c$complementAt1_arg0_case_alt_34;

  assign c$complementAt1_arg0_case_alt_34 = c$complementAt1_tupIn_case_scrut_4 ? 11'd572 : c$complementAt1_arg0_case_alt_35;

  assign c$complementAt1_arg0_case_alt_35 = c$complementAt1_tupIn_case_scrut_3 ? 11'd508 : c$complementAt1_arg0_case_alt_36;

  assign c$complementAt1_arg0_case_alt_36 = c$complementAt1_tupIn_case_scrut_2 ? 11'd444 : c$complementAt1_arg0_case_alt_37;

  assign c$complementAt1_arg0_case_alt_37 = c$complementAt1_tupIn_case_scrut_1 ? 11'd380 : c$complementAt1_arg0_case_alt_38;

  assign c$complementAt1_arg0_case_alt_38 = c$complementAt1_tupIn_case_scrut_0 ? 11'd316 : 11'd1596;

  assign c$complementAt1_arg0_1 = c$complementAt1_tupIn_case_scrut ? 11'd1597 : c$complementAt1_arg0_case_alt_39;

  assign c$complementAt1_arg0_case_alt_39 = c$complementAt1_tupIn_case_scrut_19 ? 11'd1533 : c$complementAt1_arg0_case_alt_40;

  assign c$complementAt1_arg0_case_alt_40 = c$complementAt1_tupIn_case_scrut_18 ? 11'd1469 : c$complementAt1_arg0_case_alt_41;

  assign c$complementAt1_arg0_case_alt_41 = c$complementAt1_tupIn_case_scrut_17 ? 11'd1405 : c$complementAt1_arg0_case_alt_42;

  assign c$complementAt1_arg0_case_alt_42 = c$complementAt1_tupIn_case_scrut_16 ? 11'd1341 : c$complementAt1_arg0_case_alt_43;

  assign c$complementAt1_arg0_case_alt_43 = c$complementAt1_tupIn_case_scrut_15 ? 11'd1277 : c$complementAt1_arg0_case_alt_44;

  assign c$complementAt1_arg0_case_alt_44 = c$complementAt1_tupIn_case_scrut_14 ? 11'd1213 : c$complementAt1_arg0_case_alt_45;

  assign c$complementAt1_arg0_case_alt_45 = c$complementAt1_tupIn_case_scrut_13 ? 11'd1149 : c$complementAt1_arg0_case_alt_46;

  assign c$complementAt1_arg0_case_alt_46 = c$complementAt1_tupIn_case_scrut_12 ? 11'd1085 : c$complementAt1_arg0_case_alt_47;

  assign c$complementAt1_arg0_case_alt_47 = c$complementAt1_tupIn_case_scrut_11 ? 11'd1021 : c$complementAt1_arg0_case_alt_48;

  assign c$complementAt1_arg0_case_alt_48 = c$complementAt1_tupIn_case_scrut_10 ? 11'd957 : c$complementAt1_arg0_case_alt_49;

  assign c$complementAt1_arg0_case_alt_49 = c$complementAt1_tupIn_case_scrut_9 ? 11'd893 : c$complementAt1_arg0_case_alt_50;

  assign c$complementAt1_arg0_case_alt_50 = c$complementAt1_tupIn_case_scrut_8 ? 11'd829 : c$complementAt1_arg0_case_alt_51;

  assign c$complementAt1_arg0_case_alt_51 = c$complementAt1_tupIn_case_scrut_7 ? 11'd765 : c$complementAt1_arg0_case_alt_52;

  assign c$complementAt1_arg0_case_alt_52 = c$complementAt1_tupIn_case_scrut_6 ? 11'd701 : c$complementAt1_arg0_case_alt_53;

  assign c$complementAt1_arg0_case_alt_53 = c$complementAt1_tupIn_case_scrut_5 ? 11'd637 : c$complementAt1_arg0_case_alt_54;

  assign c$complementAt1_arg0_case_alt_54 = c$complementAt1_tupIn_case_scrut_4 ? 11'd573 : c$complementAt1_arg0_case_alt_55;

  assign c$complementAt1_arg0_case_alt_55 = c$complementAt1_tupIn_case_scrut_3 ? 11'd509 : c$complementAt1_arg0_case_alt_56;

  assign c$complementAt1_arg0_case_alt_56 = c$complementAt1_tupIn_case_scrut_2 ? 11'd445 : c$complementAt1_arg0_case_alt_57;

  assign c$complementAt1_arg0_case_alt_57 = c$complementAt1_tupIn_case_scrut_1 ? 11'd381 : c$complementAt1_arg0_case_alt_58;

  assign c$complementAt1_arg0_case_alt_58 = c$complementAt1_tupIn_case_scrut_0 ? 11'd317 : 11'd1597;

  assign c$complementAt1_arg0_2 = c$complementAt1_tupIn_case_scrut ? 11'd1598 : c$complementAt1_arg0_case_alt_59;

  assign c$complementAt1_arg0_case_alt_59 = c$complementAt1_tupIn_case_scrut_19 ? 11'd1534 : c$complementAt1_arg0_case_alt_60;

  assign c$complementAt1_arg0_case_alt_60 = c$complementAt1_tupIn_case_scrut_18 ? 11'd1470 : c$complementAt1_arg0_case_alt_61;

  assign c$complementAt1_arg0_case_alt_61 = c$complementAt1_tupIn_case_scrut_17 ? 11'd1406 : c$complementAt1_arg0_case_alt_62;

  assign c$complementAt1_arg0_case_alt_62 = c$complementAt1_tupIn_case_scrut_16 ? 11'd1342 : c$complementAt1_arg0_case_alt_63;

  assign c$complementAt1_arg0_case_alt_63 = c$complementAt1_tupIn_case_scrut_15 ? 11'd1278 : c$complementAt1_arg0_case_alt_64;

  assign c$complementAt1_arg0_case_alt_64 = c$complementAt1_tupIn_case_scrut_14 ? 11'd1214 : c$complementAt1_arg0_case_alt_65;

  assign c$complementAt1_arg0_case_alt_65 = c$complementAt1_tupIn_case_scrut_13 ? 11'd1150 : c$complementAt1_arg0_case_alt_66;

  assign c$complementAt1_arg0_case_alt_66 = c$complementAt1_tupIn_case_scrut_12 ? 11'd1086 : c$complementAt1_arg0_case_alt_67;

  assign c$complementAt1_arg0_case_alt_67 = c$complementAt1_tupIn_case_scrut_11 ? 11'd1022 : c$complementAt1_arg0_case_alt_68;

  assign c$complementAt1_arg0_case_alt_68 = c$complementAt1_tupIn_case_scrut_10 ? 11'd958 : c$complementAt1_arg0_case_alt_69;

  assign c$complementAt1_arg0_case_alt_69 = c$complementAt1_tupIn_case_scrut_9 ? 11'd894 : c$complementAt1_arg0_case_alt_70;

  assign c$complementAt1_arg0_case_alt_70 = c$complementAt1_tupIn_case_scrut_8 ? 11'd830 : c$complementAt1_arg0_case_alt_71;

  assign c$complementAt1_arg0_case_alt_71 = c$complementAt1_tupIn_case_scrut_7 ? 11'd766 : c$complementAt1_arg0_case_alt_72;

  assign c$complementAt1_arg0_case_alt_72 = c$complementAt1_tupIn_case_scrut_6 ? 11'd702 : c$complementAt1_arg0_case_alt_73;

  assign c$complementAt1_arg0_case_alt_73 = c$complementAt1_tupIn_case_scrut_5 ? 11'd638 : c$complementAt1_arg0_case_alt_74;

  assign c$complementAt1_arg0_case_alt_74 = c$complementAt1_tupIn_case_scrut_4 ? 11'd574 : c$complementAt1_arg0_case_alt_75;

  assign c$complementAt1_arg0_case_alt_75 = c$complementAt1_tupIn_case_scrut_3 ? 11'd510 : c$complementAt1_arg0_case_alt_76;

  assign c$complementAt1_arg0_case_alt_76 = c$complementAt1_tupIn_case_scrut_2 ? 11'd446 : c$complementAt1_arg0_case_alt_77;

  assign c$complementAt1_arg0_case_alt_77 = c$complementAt1_tupIn_case_scrut_1 ? 11'd382 : c$complementAt1_arg0_case_alt_78;

  assign c$complementAt1_arg0_case_alt_78 = c$complementAt1_tupIn_case_scrut_0 ? 11'd318 : 11'd1598;

  assign c$complementAt1_tupIn = c$complementAt1_tupIn_case_scrut ? {11'd1599
                                                                    ,state} : result_10;

  assign c$complementAt1_tupIn_case_scrut = flush & (counter_1 == 5'd0);

  assign result_10 = c$complementAt1_tupIn_case_scrut_19 ? {11'd1535
                                                           ,result_11} : c$complementAt1_tupIn_case_alt;

  assign c$complementAt1_tupIn_case_alt = c$complementAt1_tupIn_case_scrut_18 ? {11'd1471
                                                                                ,result_11} : c$complementAt1_tupIn_case_alt_0;

  assign c$complementAt1_tupIn_case_alt_0 = c$complementAt1_tupIn_case_scrut_17 ? {11'd1407
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_1;

  assign c$complementAt1_tupIn_case_alt_1 = c$complementAt1_tupIn_case_scrut_16 ? {11'd1343
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_2;

  assign c$complementAt1_tupIn_case_alt_2 = c$complementAt1_tupIn_case_scrut_15 ? {11'd1279
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_3;

  assign c$complementAt1_tupIn_case_alt_3 = c$complementAt1_tupIn_case_scrut_14 ? {11'd1215
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_4;

  assign c$complementAt1_tupIn_case_alt_4 = c$complementAt1_tupIn_case_scrut_13 ? {11'd1151
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_5;

  assign c$complementAt1_tupIn_case_alt_5 = c$complementAt1_tupIn_case_scrut_12 ? {11'd1087
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_6;

  assign c$complementAt1_tupIn_case_alt_6 = c$complementAt1_tupIn_case_scrut_11 ? {11'd1023
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_7;

  assign c$complementAt1_tupIn_case_alt_7 = c$complementAt1_tupIn_case_scrut_10 ? {11'd959
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_8;

  assign c$complementAt1_tupIn_case_alt_8 = c$complementAt1_tupIn_case_scrut_9 ? {11'd895
                                                                                 ,result_11} : c$complementAt1_tupIn_case_alt_9;

  assign c$complementAt1_tupIn_case_alt_9 = c$complementAt1_tupIn_case_scrut_8 ? {11'd831
                                                                                 ,result_11} : c$complementAt1_tupIn_case_alt_10;

  assign c$complementAt1_tupIn_case_alt_10 = c$complementAt1_tupIn_case_scrut_7 ? {11'd767
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_11;

  assign c$complementAt1_tupIn_case_alt_11 = c$complementAt1_tupIn_case_scrut_6 ? {11'd703
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_12;

  assign c$complementAt1_tupIn_case_alt_12 = c$complementAt1_tupIn_case_scrut_5 ? {11'd639
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_13;

  assign c$complementAt1_tupIn_case_alt_13 = c$complementAt1_tupIn_case_scrut_4 ? {11'd575
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_14;

  assign c$complementAt1_tupIn_case_alt_14 = c$complementAt1_tupIn_case_scrut_3 ? {11'd511
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_15;

  assign c$complementAt1_tupIn_case_alt_15 = c$complementAt1_tupIn_case_scrut_2 ? {11'd447
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_16;

  assign c$complementAt1_tupIn_case_alt_16 = c$complementAt1_tupIn_case_scrut_1 ? {11'd383
                                                                                  ,result_11} : c$complementAt1_tupIn_case_alt_17;

  assign c$complementAt1_tupIn_case_alt_17 = c$complementAt1_tupIn_case_scrut_0 ? {11'd319
                                                                                  ,result_11} : {11'd1599,result_11};

  assign c$complementAt1_tupIn_case_scrut_0 = counter_1 == 5'd19;

  assign c$complementAt1_tupIn_case_scrut_1 = counter_1 == 5'd18;

  assign c$complementAt1_tupIn_case_scrut_2 = counter_1 == 5'd17;

  assign c$complementAt1_tupIn_case_scrut_3 = counter_1 == 5'd16;

  assign c$complementAt1_tupIn_case_scrut_4 = counter_1 == 5'd15;

  assign c$complementAt1_tupIn_case_scrut_5 = counter_1 == 5'd14;

  assign c$complementAt1_tupIn_case_scrut_6 = counter_1 == 5'd13;

  assign c$complementAt1_tupIn_case_scrut_7 = counter_1 == 5'd12;

  assign c$complementAt1_tupIn_case_scrut_8 = counter_1 == 5'd11;

  assign c$complementAt1_tupIn_case_scrut_9 = counter_1 == 5'd10;

  assign c$complementAt1_tupIn_case_scrut_10 = counter_1 == 5'd9;

  assign c$complementAt1_tupIn_case_scrut_11 = counter_1 == 5'd8;

  assign c$complementAt1_tupIn_case_scrut_12 = counter_1 == 5'd7;

  assign c$complementAt1_tupIn_case_scrut_13 = counter_1 == 5'd6;

  assign c$complementAt1_tupIn_case_scrut_14 = counter_1 == 5'd5;

  assign c$complementAt1_tupIn_case_scrut_15 = counter_1 == 5'd4;

  assign c$complementAt1_tupIn_case_scrut_16 = counter_1 == 5'd3;

  assign c$complementAt1_tupIn_case_scrut_17 = counter_1 == 5'd2;

  assign c$complementAt1_tupIn_case_scrut_18 = counter_1 == 5'd1;

  assign c$complementAt1_tupIn_case_scrut_19 = counter_1 == 5'd0;

  assign result_11 = (counter_1 == 5'd0) ? c$case_alt_21 : c$case_alt_22;

  // setSlice begin
  always_comb begin
    c$case_alt_21 = c$app_arg_12;
    c$case_alt_21[1599 : 1536] = ((c$app_arg_12[1599 : 1536]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_22 = (counter_1 == 5'd1) ? c$case_alt_23 : c$case_alt_24;

  // setSlice begin
  always_comb begin
    c$case_alt_23 = c$app_arg_12;
    c$case_alt_23[1535 : 1472] = ((c$app_arg_12[1535 : 1472]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_24 = (counter_1 == 5'd2) ? c$case_alt_25 : c$case_alt_26;

  // setSlice begin
  always_comb begin
    c$case_alt_25 = c$app_arg_12;
    c$case_alt_25[1471 : 1408] = ((c$app_arg_12[1471 : 1408]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_26 = (counter_1 == 5'd3) ? c$case_alt_27 : c$case_alt_28;

  // setSlice begin
  always_comb begin
    c$case_alt_27 = c$app_arg_12;
    c$case_alt_27[1407 : 1344] = ((c$app_arg_12[1407 : 1344]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_28 = (counter_1 == 5'd4) ? c$case_alt_29 : c$case_alt_30;

  // setSlice begin
  always_comb begin
    c$case_alt_29 = c$app_arg_12;
    c$case_alt_29[1343 : 1280] = ((c$app_arg_12[1343 : 1280]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_30 = (counter_1 == 5'd5) ? c$case_alt_31 : c$case_alt_32;

  // setSlice begin
  always_comb begin
    c$case_alt_31 = c$app_arg_12;
    c$case_alt_31[1279 : 1216] = ((c$app_arg_12[1279 : 1216]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_32 = (counter_1 == 5'd6) ? c$case_alt_33 : c$case_alt_34;

  // setSlice begin
  always_comb begin
    c$case_alt_33 = c$app_arg_12;
    c$case_alt_33[1215 : 1152] = ((c$app_arg_12[1215 : 1152]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_34 = (counter_1 == 5'd7) ? c$case_alt_35 : c$case_alt_36;

  // setSlice begin
  always_comb begin
    c$case_alt_35 = c$app_arg_12;
    c$case_alt_35[1151 : 1088] = ((c$app_arg_12[1151 : 1088]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_36 = (counter_1 == 5'd8) ? c$case_alt_37 : c$case_alt_38;

  // setSlice begin
  always_comb begin
    c$case_alt_37 = c$app_arg_12;
    c$case_alt_37[1087 : 1024] = ((c$app_arg_12[1087 : 1024]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_38 = (counter_1 == 5'd9) ? c$case_alt_39 : c$case_alt_40;

  // setSlice begin
  always_comb begin
    c$case_alt_39 = c$app_arg_12;
    c$case_alt_39[1023 : 960] = ((c$app_arg_12[1023 : 960]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_40 = (counter_1 == 5'd10) ? c$case_alt_41 : c$case_alt_42;

  // setSlice begin
  always_comb begin
    c$case_alt_41 = c$app_arg_12;
    c$case_alt_41[959 : 896] = ((c$app_arg_12[959 : 896]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_42 = (counter_1 == 5'd11) ? c$case_alt_43 : c$case_alt_44;

  // setSlice begin
  always_comb begin
    c$case_alt_43 = c$app_arg_12;
    c$case_alt_43[895 : 832] = ((c$app_arg_12[895 : 832]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_44 = (counter_1 == 5'd12) ? c$case_alt_45 : c$case_alt_46;

  // setSlice begin
  always_comb begin
    c$case_alt_45 = c$app_arg_12;
    c$case_alt_45[831 : 768] = ((c$app_arg_12[831 : 768]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_46 = (counter_1 == 5'd13) ? c$case_alt_47 : c$case_alt_48;

  // setSlice begin
  always_comb begin
    c$case_alt_47 = c$app_arg_12;
    c$case_alt_47[767 : 704] = ((c$app_arg_12[767 : 704]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_48 = (counter_1 == 5'd14) ? c$case_alt_49 : c$case_alt_50;

  // setSlice begin
  always_comb begin
    c$case_alt_49 = c$app_arg_12;
    c$case_alt_49[703 : 640] = ((c$app_arg_12[703 : 640]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_50 = (counter_1 == 5'd15) ? c$case_alt_51 : c$case_alt_52;

  // setSlice begin
  always_comb begin
    c$case_alt_51 = c$app_arg_12;
    c$case_alt_51[639 : 576] = ((c$app_arg_12[639 : 576]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_52 = (counter_1 == 5'd16) ? c$case_alt_53 : c$case_alt_54;

  // setSlice begin
  always_comb begin
    c$case_alt_53 = c$app_arg_12;
    c$case_alt_53[575 : 512] = ((c$app_arg_12[575 : 512]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_54 = (counter_1 == 5'd17) ? c$case_alt_55 : c$case_alt_56;

  // setSlice begin
  always_comb begin
    c$case_alt_55 = c$app_arg_12;
    c$case_alt_55[511 : 448] = ((c$app_arg_12[511 : 448]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_56 = (counter_1 == 5'd18) ? c$case_alt_57 : c$case_alt_58;

  // setSlice begin
  always_comb begin
    c$case_alt_57 = c$app_arg_12;
    c$case_alt_57[447 : 384] = ((c$app_arg_12[447 : 384]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_58 = (counter_1 == 5'd19) ? c$case_alt_59 : c$case_alt_60;

  // setSlice begin
  always_comb begin
    c$case_alt_59 = c$app_arg_12;
    c$case_alt_59[383 : 320] = ((c$app_arg_12[383 : 320]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_60 = (counter_1 == 5'd20) ? c$case_alt_61 : state;

  // setSlice begin
  always_comb begin
    c$case_alt_61 = c$app_arg_12;
    c$case_alt_61[319 : 256] = ((c$app_arg_12[319 : 256]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$app_arg_12 = state;

  assign flush = eta1.Tuple3_0_sel2;

  assign \input  = eta1.Tuple3_0_sel0;

  assign counter_1 = ds1[1606:1602];


endmodule

