/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module dut
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [263:0] MSG_TDATA
    , input wire logic MSG_TVALID
    , input wire logic MSG_TLAST
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [11:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    , output logic DIGEST_TLAST
    , output logic MSG_TREADY
    );
  logic [1609:0] c$ds_app_arg = {2'b00,1608'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  dut_types::Tuple2_2 result_0;
  dut_types::Tuple2_3 c$case_alt;
  logic [11:0] result_1;
  logic [1:0] a;
  logic [1:0] b;
  logic [3:0] c$b_app_arg;
  logic [3:0] result_2;
  logic [3:0] c$case_alt_0;
  logic [3:0] c$case_alt_1;
  logic [3:0] c$case_alt_2;
  logic [3:0] c$case_alt_3;
  logic [3:0] c$case_alt_4;
  logic [3:0] c$case_alt_5;
  logic [3:0] c$case_alt_6;
  logic [3:0] c$case_alt_7;
  logic [3:0] c$case_alt_8;
  logic [3:0] c$case_alt_9;
  logic [3:0] c$case_alt_10;
  logic [3:0] c$case_alt_11;
  logic [3:0] c$case_alt_12;
  logic [3:0] c$case_alt_13;
  logic [63:0] c$app_arg;
  logic [63:0] result_3;
  logic [63:0] c$case_alt_14;
  logic [63:0] c$case_alt_15;
  logic [63:0] c$case_alt_16;
  logic [63:0] c$case_alt_17;
  logic [63:0] c$case_alt_18;
  logic [63:0] c$case_alt_19;
  logic [63:0] c$case_alt_20;
  logic [63:0] c$case_alt_21;
  logic [63:0] c$case_alt_22;
  logic [63:0] c$case_alt_23;
  logic [63:0] c$case_alt_24;
  logic [63:0] c$case_alt_25;
  logic [63:0] c$case_alt_26;
  logic [63:0] c$case_alt_27;
  logic [63:0] c$case_alt_28;
  logic [1599:0] c$app_arg_0;
  logic [1609:0] c$app_arg_1;
  logic tready;
  logic [1609:0] c$case_alt_29;
  logic isLast;
  logic [1609:0] c$case_alt_30;
  logic [1599:0] state;
  logic c$isLast_app_arg;
  logic [3:0] coeffIdx;
  logic [3:0] wordIdx;
  dut_types::Tuple2_3 result_4;
  dut_types::Tuple2_3 c$case_alt_31;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_7;
  logic [1599:0] c$app_arg_4;
  logic [1599:0] result_8;
  logic [1599:0] c$app_arg_5;
  logic [1599:0] result_9;
  logic [1599:0] c$app_arg_6;
  logic [1599:0] result_10;
  logic [1599:0] c$app_arg_7;
  dut_types::AXI4Stream inBeat;
  logic [1599:0] c$keccakF1600Reversed_out;
  logic [1599:0] state_0;
  logic [4:0] roundIdx;
  dut_types::Tuple2_4 c$arg;
  logic [0:0] c$bv;
  logic [0:0] c$bv_0;
  logic [0:0] c$bv_1;
  logic [0:0] c$bv_2;
  dut_types::Tuple2_5 result;
  dut_types::AXI4Stream_0 DIGEST;

  assign c$arg = {{MSG_TDATA
                  ,MSG_TVALID
                  ,MSG_TLAST}
                 ,DIGEST_TREADY};

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {2'b00,1608'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt.Tuple2_3_sel0;
    end
  end
  // register end

  assign result_0 = c$case_alt.Tuple2_3_sel1;

  always_comb begin
    case(c$ds_app_arg[1609:1608])
      2'b00 : c$case_alt = c$case_alt_31;
      2'b01 : c$case_alt = result_4;
      2'b10 : c$case_alt = {c$app_arg_1
                           ,{1'b0,{result_1,1'b1,isLast}}};
      default : c$case_alt = {{2'b11,1608'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                             ,{1'b0,{12'b000000000000,1'b0,1'b0}}};
    endcase
  end

  assign result_1 = (a >= b) ? ({10'b0000000000,(((a - b)))}) : (12'b110100000001 - ({10'b0000000000,(((b - a)))}));

  assign c$bv = ((c$b_app_arg[3 : 3]));

  assign c$bv_0 = ((c$b_app_arg[2 : 2]));

  assign a = ({{(2-1) {1'b0}},((c$b_app_arg[3 : 3]))}) + ({{(2-1) {1'b0}},((c$b_app_arg[2 : 2]))});

  assign c$bv_1 = ((c$b_app_arg[1 : 1]));

  assign c$bv_2 = ((c$b_app_arg[0 : 0]));

  assign b = ({{(2-1) {1'b0}},((c$b_app_arg[1 : 1]))}) + ({{(2-1) {1'b0}},((c$b_app_arg[0 : 0]))});

  assign c$b_app_arg = result_2;

  assign result_2 = (coeffIdx == 4'd0) ? (c$app_arg[63 : 60]) : c$case_alt_0;

  assign c$case_alt_0 = (coeffIdx == 4'd1) ? (c$app_arg[59 : 56]) : c$case_alt_1;

  assign c$case_alt_1 = (coeffIdx == 4'd2) ? (c$app_arg[55 : 52]) : c$case_alt_2;

  assign c$case_alt_2 = (coeffIdx == 4'd3) ? (c$app_arg[51 : 48]) : c$case_alt_3;

  assign c$case_alt_3 = (coeffIdx == 4'd4) ? (c$app_arg[47 : 44]) : c$case_alt_4;

  assign c$case_alt_4 = (coeffIdx == 4'd5) ? (c$app_arg[43 : 40]) : c$case_alt_5;

  assign c$case_alt_5 = (coeffIdx == 4'd6) ? (c$app_arg[39 : 36]) : c$case_alt_6;

  assign c$case_alt_6 = (coeffIdx == 4'd7) ? (c$app_arg[35 : 32]) : c$case_alt_7;

  assign c$case_alt_7 = (coeffIdx == 4'd8) ? (c$app_arg[31 : 28]) : c$case_alt_8;

  assign c$case_alt_8 = (coeffIdx == 4'd9) ? (c$app_arg[27 : 24]) : c$case_alt_9;

  assign c$case_alt_9 = (coeffIdx == 4'd10) ? (c$app_arg[23 : 20]) : c$case_alt_10;

  assign c$case_alt_10 = (coeffIdx == 4'd11) ? (c$app_arg[19 : 16]) : c$case_alt_11;

  assign c$case_alt_11 = (coeffIdx == 4'd12) ? (c$app_arg[15 : 12]) : c$case_alt_12;

  assign c$case_alt_12 = (coeffIdx == 4'd13) ? (c$app_arg[11 : 8]) : c$case_alt_13;

  assign c$case_alt_13 = (coeffIdx == 4'd14) ? (c$app_arg[7 : 4]) : (c$app_arg[3 : 0]);

  assign c$app_arg = result_3;

  assign result_3 = (({{(5-4) {1'b0}},wordIdx}) == 5'd0) ? (c$app_arg_0[1599 : 1536]) : c$case_alt_14;

  assign c$case_alt_14 = (({{(5-4) {1'b0}},wordIdx}) == 5'd1) ? (c$app_arg_0[1535 : 1472]) : c$case_alt_15;

  assign c$case_alt_15 = (({{(5-4) {1'b0}},wordIdx}) == 5'd2) ? (c$app_arg_0[1471 : 1408]) : c$case_alt_16;

  assign c$case_alt_16 = (({{(5-4) {1'b0}},wordIdx}) == 5'd3) ? (c$app_arg_0[1407 : 1344]) : c$case_alt_17;

  assign c$case_alt_17 = (({{(5-4) {1'b0}},wordIdx}) == 5'd4) ? (c$app_arg_0[1343 : 1280]) : c$case_alt_18;

  assign c$case_alt_18 = (({{(5-4) {1'b0}},wordIdx}) == 5'd5) ? (c$app_arg_0[1279 : 1216]) : c$case_alt_19;

  assign c$case_alt_19 = (({{(5-4) {1'b0}},wordIdx}) == 5'd6) ? (c$app_arg_0[1215 : 1152]) : c$case_alt_20;

  assign c$case_alt_20 = (({{(5-4) {1'b0}},wordIdx}) == 5'd7) ? (c$app_arg_0[1151 : 1088]) : c$case_alt_21;

  assign c$case_alt_21 = (({{(5-4) {1'b0}},wordIdx}) == 5'd8) ? (c$app_arg_0[1087 : 1024]) : c$case_alt_22;

  assign c$case_alt_22 = (({{(5-4) {1'b0}},wordIdx}) == 5'd9) ? (c$app_arg_0[1023 : 960]) : c$case_alt_23;

  assign c$case_alt_23 = (({{(5-4) {1'b0}},wordIdx}) == 5'd10) ? (c$app_arg_0[959 : 896]) : c$case_alt_24;

  assign c$case_alt_24 = (({{(5-4) {1'b0}},wordIdx}) == 5'd11) ? (c$app_arg_0[895 : 832]) : c$case_alt_25;

  assign c$case_alt_25 = (({{(5-4) {1'b0}},wordIdx}) == 5'd12) ? (c$app_arg_0[831 : 768]) : c$case_alt_26;

  assign c$case_alt_26 = (({{(5-4) {1'b0}},wordIdx}) == 5'd13) ? (c$app_arg_0[767 : 704]) : c$case_alt_27;

  assign c$case_alt_27 = (({{(5-4) {1'b0}},wordIdx}) == 5'd14) ? (c$app_arg_0[703 : 640]) : c$case_alt_28;

  assign c$case_alt_28 = (({{(5-4) {1'b0}},wordIdx}) == 5'd15) ? (c$app_arg_0[639 : 576]) : (c$app_arg_0[575 : 512]);

  assign c$app_arg_0 = state;

  assign c$app_arg_1 = tready ? c$case_alt_29 : c$ds_app_arg;

  assign tready = c$arg.Tuple2_4_sel1;

  assign c$case_alt_29 = isLast ? {2'b11,1608'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : c$case_alt_30;

  assign isLast = (wordIdx == 4'd15) & c$isLast_app_arg;

  assign c$case_alt_30 = c$isLast_app_arg ? {2'b10,wordIdx + 4'd1,4'd0,state} : {2'b10,wordIdx,coeffIdx + 4'd1,state};

  assign state = c$ds_app_arg[1599:0];

  assign c$isLast_app_arg = coeffIdx == 4'd15;

  assign coeffIdx = c$ds_app_arg[1603:1600];

  assign wordIdx = c$ds_app_arg[1607:1604];

  assign result_4 = (roundIdx == 5'd23) ? {{2'b10,4'd0,4'd0,c$keccakF1600Reversed_out}
                                          ,{1'b0
                                           ,{12'b000000000000
                                            ,1'b0
                                            ,1'b0}}} : {{2'b01,roundIdx + 5'd1,c$keccakF1600Reversed_out,3'bxxx}
                                                       ,{1'b0,{12'b000000000000,1'b0,1'b0}}};

  assign c$case_alt_31 = inBeat.AXI4Stream_sel1 ? {{2'b01,5'd0,result_10,3'bxxx}
                                                  ,{1'b0
                                                   ,{12'b000000000000
                                                    ,1'b0
                                                    ,1'b0}}} : {{2'b00,1608'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                                               ,{1'b1,{12'b000000000000,1'b0,1'b0}}};

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_2;
    result_5[64'sd1331] = (~ (c$app_arg_2[64'sd1331]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_3;
    result_6[64'sd1332] = (~ (c$app_arg_3[64'sd1332]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_7;

  // replaceBit start
  always_comb begin
    result_7 = c$app_arg_4;
    result_7[64'sd1333] = (~ (c$app_arg_4[64'sd1333]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_8;

  // replaceBit start
  always_comb begin
    result_8 = c$app_arg_5;
    result_8[64'sd1334] = (~ (c$app_arg_5[64'sd1334]));
  end
  // replaceBit end

  assign c$app_arg_5 = result_9;

  // replaceBit start
  always_comb begin
    result_9 = c$app_arg_6;
    result_9[64'sd1335] = (~ (c$app_arg_6[64'sd1335]));
  end
  // replaceBit end

  assign c$app_arg_6 = ({inBeat.AXI4Stream_sel0,1336'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000});

  // replaceBit start
  always_comb begin
    result_10 = c$app_arg_7;
    result_10[64'sd512] = (~ (c$app_arg_7[64'sd512]));
  end
  // replaceBit end

  assign c$app_arg_7 = result_5;

  assign inBeat = c$arg.Tuple2_4_sel0;

  Component_SamplePolyCBD2_i264o12_keccakF1600Reversed Component_SamplePolyCBD2_i264o12_keccakF1600Reversed_c$keccakF1600Reversed_out
    ( .result (c$keccakF1600Reversed_out)
    , .roundIdx (roundIdx)
    , .x (state_0) );

  assign state_0 = c$ds_app_arg[1602:3];

  assign roundIdx = c$ds_app_arg[1607:1603];

  assign result = {result_0.Tuple2_2_sel1
                  ,result_0.Tuple2_2_sel0};

  assign DIGEST = result.Tuple2_5_sel0;

  assign MSG_TREADY = result.Tuple2_5_sel1;

  assign DIGEST_TDATA = DIGEST.AXI4Stream_0_sel0;

  assign DIGEST_TVALID = DIGEST.AXI4Stream_0_sel1;

  assign DIGEST_TLAST = DIGEST.AXI4Stream_0_sel2;


endmodule

