/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module SampleNTT512_I272_O24
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [271:0] SEED_TDATA
    , input wire logic SEED_TVALID
    , input wire logic SEED_TLAST
    , input wire logic COEFF_TREADY

      // Outputs
    , output logic [23:0] COEFF_TDATA
    , output logic COEFF_TVALID
    , output logic COEFF_TLAST
    , output logic SEED_TREADY
    );
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] state;
  logic [4:0] roundIdx;
  logic [1621:0] st = {2'b00,1620'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  SampleNTT512_I272_O24_types::Tuple2_2 c$ds_case_alt;
  SampleNTT512_I272_O24_types::Tuple2_2 c$ds_case_alt_0;
  logic msgValid;
  logic [1599:0] result_0;
  logic [1599:0] c$app_arg;
  logic [1599:0] result_1;
  logic [1599:0] c$app_arg_0;
  logic [1599:0] result_2;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_4;
  logic [271:0] inputMsg;
  logic [1621:0] c$ds_app_arg;
  logic tready;
  logic [1621:0] c$ds_case_alt_1;
  SampleNTT512_I272_O24_types::Tuple3_0 result_6;
  SampleNTT512_I272_O24_types::Tuple3_0 c$ds4_case_alt;
  SampleNTT512_I272_O24_types::Tuple3_0 c$ds4_case_alt_0;
  logic [23:0] c$ds4_app_arg;
  SampleNTT512_I272_O24_types::Tuple3_0 c$ds4_case_alt_1;
  logic [11:0] b;
  logic [12:0] buffer;
  SampleNTT512_I272_O24_types::Tuple3_0 c$ds4_case_alt_2;
  SampleNTT512_I272_O24_types::Tuple3_0 c$ds4_case_alt_3;
  SampleNTT512_I272_O24_types::Tuple3_0 c$ds4_case_alt_4;
  logic c$ds4_case_scrut;
  logic [11:0] c1;
  logic c$ds4_case_scrut_0;
  logic [11:0] c0;
  logic [23:0] c$c0_app_arg;
  logic [23:0] result_7;
  logic [23:0] c$pair_case_alt;
  logic [23:0] c$pair_case_alt_0;
  logic [23:0] c$pair_case_alt_1;
  logic [23:0] c$pair_case_alt_2;
  logic [23:0] c$pair_case_alt_3;
  logic [23:0] c$pair_case_alt_4;
  logic [23:0] c$pair_case_alt_5;
  logic [23:0] c$pair_case_alt_6;
  logic [23:0] c$pair_case_alt_7;
  logic [23:0] c$pair_case_alt_8;
  logic [23:0] c$pair_case_alt_9;
  logic [23:0] c$pair_case_alt_10;
  logic [23:0] c$pair_case_alt_11;
  logic [23:0] c$pair_case_alt_12;
  logic [23:0] c$pair_case_alt_13;
  logic [23:0] c$pair_case_alt_14;
  logic [23:0] c$pair_case_alt_15;
  logic [23:0] c$pair_case_alt_16;
  logic [23:0] c$pair_case_alt_17;
  logic [23:0] c$pair_case_alt_18;
  logic [23:0] c$pair_case_alt_19;
  logic [23:0] c$pair_case_alt_20;
  logic [23:0] c$pair_case_alt_21;
  logic [23:0] c$pair_case_alt_22;
  logic [23:0] c$pair_case_alt_23;
  logic [23:0] c$pair_case_alt_24;
  logic [23:0] c$pair_case_alt_25;
  logic [23:0] c$pair_case_alt_26;
  logic [23:0] c$pair_case_alt_27;
  logic [23:0] c$pair_case_alt_28;
  logic [23:0] c$pair_case_alt_29;
  logic [23:0] c$pair_case_alt_30;
  logic [23:0] c$pair_case_alt_31;
  logic [23:0] c$pair_case_alt_32;
  logic [23:0] c$pair_case_alt_33;
  logic [23:0] c$pair_case_alt_34;
  logic [23:0] c$pair_case_alt_35;
  logic [23:0] c$pair_case_alt_36;
  logic [23:0] c$pair_case_alt_37;
  logic [23:0] c$pair_case_alt_38;
  logic [23:0] c$pair_case_alt_39;
  logic [23:0] c$pair_case_alt_40;
  logic [23:0] c$pair_case_alt_41;
  logic [23:0] c$pair_case_alt_42;
  logic [23:0] c$pair_case_alt_43;
  logic [23:0] c$pair_case_alt_44;
  logic [23:0] c$pair_case_alt_45;
  logic [23:0] c$pair_case_alt_46;
  logic [23:0] c$pair_case_alt_47;
  logic [23:0] c$pair_case_alt_48;
  logic [23:0] c$pair_case_alt_49;
  logic [23:0] c$pair_case_alt_50;
  logic [23:0] c$pair_case_alt_51;
  logic [23:0] c$pair_case_alt_52;
  logic [23:0] c$pair_case_alt_53;
  logic [1599:0] c$pair_app_arg;
  logic [1599:0] state_0;
  logic [5:0] ds5;
  logic signed [63:0] c$ds5_case_alt;
  logic signed [63:0] c$ds_app_arg_0;
  logic signed [63:0] x;
  logic signed [63:0] idxInt;
  logic [6:0] index;
  SampleNTT512_I272_O24_types::Tuple2_2 result_8;
  logic [12:0] buffer_0;
  SampleNTT512_I272_O24_types::Tuple2_3 inputSig;
  logic signed [63:0] c$ds_case_alt_selection_res;
  SampleNTT512_I272_O24_types::Tuple2_4 result;
  SampleNTT512_I272_O24_types::AXI4Stream COEFF;

  assign inputSig = {{SEED_TDATA
                     ,SEED_TVALID
                     ,SEED_TLAST}
                    ,COEFF_TREADY};

  assign result = c$ds_case_alt.Tuple2_2_sel1;

  Component_SampleNTT512_i272o24l0_keccakF1600 Component_SampleNTT512_i272o24l0_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (roundIdx)
    , .x (state) );

  assign state = st[1614:15];

  assign roundIdx = st[1619:1615];

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : st_register
    if ( RST) begin
      st <= {2'b00,1620'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      st <= c$ds_case_alt.Tuple2_2_sel0;
    end
  end
  // register end

  always_comb begin
    case(st[1621:1620])
      2'b00 : c$ds_case_alt = c$ds_case_alt_0;
      2'b01 : c$ds_case_alt = result_8;
      default : c$ds_case_alt = {c$ds_app_arg
                                ,{{result_6.Tuple3_0_sel1
                                  ,result_6.Tuple3_0_sel0
                                  ,1'b0}
                                 ,1'b0}};
    endcase
  end

  assign c$ds_case_alt_0 = msgValid ? {{2'b01,5'd0,result_0,{1'b0,12'bxxxxxxxxxxxx},2'bxx}
                                      ,{{24'b000000000000000000000000,1'b0,1'b0}
                                       ,1'b0}} : {{2'b00,1620'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                                 ,{{24'b000000000000000000000000,1'b0,1'b0}
                                                  ,1'b1}};

  assign msgValid = inputSig[2:2];

  // replaceBit start
  always_comb begin
    result_0 = c$app_arg;
    result_0[64'sd1343] = (~ (c$app_arg[64'sd1343]));
  end
  // replaceBit end

  assign c$app_arg = result_1;

  // replaceBit start
  always_comb begin
    result_1 = c$app_arg_0;
    result_1[64'sd272] = (~ (c$app_arg_0[64'sd272]));
  end
  // replaceBit end

  assign c$app_arg_0 = result_2;

  // replaceBit start
  always_comb begin
    result_2 = c$app_arg_1;
    result_2[64'sd273] = (~ (c$app_arg_1[64'sd273]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_3;

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_2;
    result_3[64'sd274] = (~ (c$app_arg_2[64'sd274]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_4;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_3;
    result_4[64'sd275] = (~ (c$app_arg_3[64'sd275]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_4;
    result_5[64'sd276] = (~ (c$app_arg_4[64'sd276]));
  end
  // replaceBit end

  assign c$app_arg_4 = ({1328'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,inputMsg});

  assign inputMsg = inputSig[274:3];

  assign c$ds_app_arg = tready ? c$ds_case_alt_1 : st;

  assign tready = inputSig.Tuple2_3_sel1;

  assign c$ds_case_alt_selection_res = (x >= 64'sd110) ? 64'sd1 : 64'sd0;

  always_comb begin
    case(c$ds_case_alt_selection_res)
      64'sd1 : c$ds_case_alt_1 = {2'b01,5'd0,state_0,result_6.Tuple3_0_sel2,2'bxx};
      default : c$ds_case_alt_1 = {2'b10,$unsigned(c$ds_app_arg_0[0+:7]),state_0,result_6.Tuple3_0_sel2};
    endcase
  end

  assign result_6 = buffer[12:12] ? c$ds4_case_alt : c$ds4_case_alt_2;

  assign c$ds4_case_alt = c$ds4_case_scrut_0 ? c$ds4_case_alt_0 : c$ds4_case_alt_1;

  assign c$ds4_case_alt_0 = c$ds4_case_scrut ? {1'b1
                                               ,c$ds4_app_arg
                                               ,{1'b1,c1}} : {1'b1
                                                             ,c$ds4_app_arg
                                                             ,{1'b0,12'bxxxxxxxxxxxx}};

  assign c$ds4_app_arg = {c0,b};

  assign c$ds4_case_alt_1 = c$ds4_case_scrut ? {1'b1
                                               ,{c1,b}
                                               ,{1'b0,12'bxxxxxxxxxxxx}} : {1'b0
                                                                           ,24'b000000000000000000000000
                                                                           ,buffer};

  assign b = buffer[11:0];

  assign buffer = st[12:0];

  assign c$ds4_case_alt_2 = c$ds4_case_scrut_0 ? c$ds4_case_alt_3 : c$ds4_case_alt_4;

  assign c$ds4_case_alt_3 = c$ds4_case_scrut ? {1'b1
                                               ,{c1,c0}
                                               ,{1'b0,12'bxxxxxxxxxxxx}} : {1'b0
                                                                           ,24'b000000000000000000000000
                                                                           ,{1'b1,c0}};

  assign c$ds4_case_alt_4 = c$ds4_case_scrut ? {1'b0
                                               ,24'b000000000000000000000000
                                               ,{1'b1,c1}} : {1'b0
                                                             ,24'b000000000000000000000000
                                                             ,{1'b0,12'bxxxxxxxxxxxx}};

  assign c$ds4_case_scrut = (c1) < 12'd3329;

  assign c1 = c$c0_app_arg[23 : 12];

  assign c$ds4_case_scrut_0 = (c0) < 12'd3329;

  assign c0 = c$c0_app_arg[11 : 0];

  assign c$c0_app_arg = result_7;

  assign result_7 = (ds5 == 6'd0) ? (c$pair_app_arg[23 : 0]) : c$pair_case_alt;

  assign c$pair_case_alt = (ds5 == 6'd1) ? (c$pair_app_arg[47 : 24]) : c$pair_case_alt_0;

  assign c$pair_case_alt_0 = (ds5 == 6'd2) ? (c$pair_app_arg[71 : 48]) : c$pair_case_alt_1;

  assign c$pair_case_alt_1 = (ds5 == 6'd3) ? (c$pair_app_arg[95 : 72]) : c$pair_case_alt_2;

  assign c$pair_case_alt_2 = (ds5 == 6'd4) ? (c$pair_app_arg[119 : 96]) : c$pair_case_alt_3;

  assign c$pair_case_alt_3 = (ds5 == 6'd5) ? (c$pair_app_arg[143 : 120]) : c$pair_case_alt_4;

  assign c$pair_case_alt_4 = (ds5 == 6'd6) ? (c$pair_app_arg[167 : 144]) : c$pair_case_alt_5;

  assign c$pair_case_alt_5 = (ds5 == 6'd7) ? (c$pair_app_arg[191 : 168]) : c$pair_case_alt_6;

  assign c$pair_case_alt_6 = (ds5 == 6'd8) ? (c$pair_app_arg[215 : 192]) : c$pair_case_alt_7;

  assign c$pair_case_alt_7 = (ds5 == 6'd9) ? (c$pair_app_arg[239 : 216]) : c$pair_case_alt_8;

  assign c$pair_case_alt_8 = (ds5 == 6'd10) ? (c$pair_app_arg[263 : 240]) : c$pair_case_alt_9;

  assign c$pair_case_alt_9 = (ds5 == 6'd11) ? (c$pair_app_arg[287 : 264]) : c$pair_case_alt_10;

  assign c$pair_case_alt_10 = (ds5 == 6'd12) ? (c$pair_app_arg[311 : 288]) : c$pair_case_alt_11;

  assign c$pair_case_alt_11 = (ds5 == 6'd13) ? (c$pair_app_arg[335 : 312]) : c$pair_case_alt_12;

  assign c$pair_case_alt_12 = (ds5 == 6'd14) ? (c$pair_app_arg[359 : 336]) : c$pair_case_alt_13;

  assign c$pair_case_alt_13 = (ds5 == 6'd15) ? (c$pair_app_arg[383 : 360]) : c$pair_case_alt_14;

  assign c$pair_case_alt_14 = (ds5 == 6'd16) ? (c$pair_app_arg[407 : 384]) : c$pair_case_alt_15;

  assign c$pair_case_alt_15 = (ds5 == 6'd17) ? (c$pair_app_arg[431 : 408]) : c$pair_case_alt_16;

  assign c$pair_case_alt_16 = (ds5 == 6'd18) ? (c$pair_app_arg[455 : 432]) : c$pair_case_alt_17;

  assign c$pair_case_alt_17 = (ds5 == 6'd19) ? (c$pair_app_arg[479 : 456]) : c$pair_case_alt_18;

  assign c$pair_case_alt_18 = (ds5 == 6'd20) ? (c$pair_app_arg[503 : 480]) : c$pair_case_alt_19;

  assign c$pair_case_alt_19 = (ds5 == 6'd21) ? (c$pair_app_arg[527 : 504]) : c$pair_case_alt_20;

  assign c$pair_case_alt_20 = (ds5 == 6'd22) ? (c$pair_app_arg[551 : 528]) : c$pair_case_alt_21;

  assign c$pair_case_alt_21 = (ds5 == 6'd23) ? (c$pair_app_arg[575 : 552]) : c$pair_case_alt_22;

  assign c$pair_case_alt_22 = (ds5 == 6'd24) ? (c$pair_app_arg[599 : 576]) : c$pair_case_alt_23;

  assign c$pair_case_alt_23 = (ds5 == 6'd25) ? (c$pair_app_arg[623 : 600]) : c$pair_case_alt_24;

  assign c$pair_case_alt_24 = (ds5 == 6'd26) ? (c$pair_app_arg[647 : 624]) : c$pair_case_alt_25;

  assign c$pair_case_alt_25 = (ds5 == 6'd27) ? (c$pair_app_arg[671 : 648]) : c$pair_case_alt_26;

  assign c$pair_case_alt_26 = (ds5 == 6'd28) ? (c$pair_app_arg[695 : 672]) : c$pair_case_alt_27;

  assign c$pair_case_alt_27 = (ds5 == 6'd29) ? (c$pair_app_arg[719 : 696]) : c$pair_case_alt_28;

  assign c$pair_case_alt_28 = (ds5 == 6'd30) ? (c$pair_app_arg[743 : 720]) : c$pair_case_alt_29;

  assign c$pair_case_alt_29 = (ds5 == 6'd31) ? (c$pair_app_arg[767 : 744]) : c$pair_case_alt_30;

  assign c$pair_case_alt_30 = (ds5 == 6'd32) ? (c$pair_app_arg[791 : 768]) : c$pair_case_alt_31;

  assign c$pair_case_alt_31 = (ds5 == 6'd33) ? (c$pair_app_arg[815 : 792]) : c$pair_case_alt_32;

  assign c$pair_case_alt_32 = (ds5 == 6'd34) ? (c$pair_app_arg[839 : 816]) : c$pair_case_alt_33;

  assign c$pair_case_alt_33 = (ds5 == 6'd35) ? (c$pair_app_arg[863 : 840]) : c$pair_case_alt_34;

  assign c$pair_case_alt_34 = (ds5 == 6'd36) ? (c$pair_app_arg[887 : 864]) : c$pair_case_alt_35;

  assign c$pair_case_alt_35 = (ds5 == 6'd37) ? (c$pair_app_arg[911 : 888]) : c$pair_case_alt_36;

  assign c$pair_case_alt_36 = (ds5 == 6'd38) ? (c$pair_app_arg[935 : 912]) : c$pair_case_alt_37;

  assign c$pair_case_alt_37 = (ds5 == 6'd39) ? (c$pair_app_arg[959 : 936]) : c$pair_case_alt_38;

  assign c$pair_case_alt_38 = (ds5 == 6'd40) ? (c$pair_app_arg[983 : 960]) : c$pair_case_alt_39;

  assign c$pair_case_alt_39 = (ds5 == 6'd41) ? (c$pair_app_arg[1007 : 984]) : c$pair_case_alt_40;

  assign c$pair_case_alt_40 = (ds5 == 6'd42) ? (c$pair_app_arg[1031 : 1008]) : c$pair_case_alt_41;

  assign c$pair_case_alt_41 = (ds5 == 6'd43) ? (c$pair_app_arg[1055 : 1032]) : c$pair_case_alt_42;

  assign c$pair_case_alt_42 = (ds5 == 6'd44) ? (c$pair_app_arg[1079 : 1056]) : c$pair_case_alt_43;

  assign c$pair_case_alt_43 = (ds5 == 6'd45) ? (c$pair_app_arg[1103 : 1080]) : c$pair_case_alt_44;

  assign c$pair_case_alt_44 = (ds5 == 6'd46) ? (c$pair_app_arg[1127 : 1104]) : c$pair_case_alt_45;

  assign c$pair_case_alt_45 = (ds5 == 6'd47) ? (c$pair_app_arg[1151 : 1128]) : c$pair_case_alt_46;

  assign c$pair_case_alt_46 = (ds5 == 6'd48) ? (c$pair_app_arg[1175 : 1152]) : c$pair_case_alt_47;

  assign c$pair_case_alt_47 = (ds5 == 6'd49) ? (c$pair_app_arg[1199 : 1176]) : c$pair_case_alt_48;

  assign c$pair_case_alt_48 = (ds5 == 6'd50) ? (c$pair_app_arg[1223 : 1200]) : c$pair_case_alt_49;

  assign c$pair_case_alt_49 = (ds5 == 6'd51) ? (c$pair_app_arg[1247 : 1224]) : c$pair_case_alt_50;

  assign c$pair_case_alt_50 = (ds5 == 6'd52) ? (c$pair_app_arg[1271 : 1248]) : c$pair_case_alt_51;

  assign c$pair_case_alt_51 = (ds5 == 6'd53) ? (c$pair_app_arg[1295 : 1272]) : c$pair_case_alt_52;

  assign c$pair_case_alt_52 = (ds5 == 6'd54) ? (c$pair_app_arg[1319 : 1296]) : c$pair_case_alt_53;

  assign c$pair_case_alt_53 = (ds5 == 6'd55) ? (c$pair_app_arg[1343 : 1320]) : ({24 {1'bx}});

  assign c$pair_app_arg = state_0;

  assign state_0 = st[1612:13];

  assign ds5 = $unsigned(c$ds5_case_alt[0+:6]);

  assign c$ds5_case_alt = x >>> 64'sd1;

  assign c$ds_app_arg_0 = x + 64'sd2;

  assign x = idxInt;

  assign idxInt = $unsigned({{(64-7) {1'b0}},index});

  assign index = st[1619:1613];

  assign result_8 = (roundIdx == 5'd23) ? {{2'b10,7'd0,c$keccakF1600_out,buffer_0}
                                          ,{{24'b000000000000000000000000,1'b0,1'b0}
                                           ,1'b0}} : {{2'b01,roundIdx + 5'd1,c$keccakF1600_out,buffer_0,2'bxx}
                                                     ,{{24'b000000000000000000000000,1'b0,1'b0}
                                                      ,1'b0}};

  assign buffer_0 = st[14:2];

  assign COEFF = result.Tuple2_4_sel0;

  assign SEED_TREADY = result.Tuple2_4_sel1;

  assign COEFF_TDATA = COEFF.AXI4Stream_sel0;

  assign COEFF_TVALID = COEFF.AXI4Stream_sel1;

  assign COEFF_TLAST = COEFF.AXI4Stream_sel2;


endmodule

