/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.10.0. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module NTT
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire [22:0] input_a
    , input wire [22:0] input_b
    , input wire [22:0] input_zeta

      // Outputs
    , output wire [22:0] output_outA
    , output wire [22:0] output_outB
    );
  wire [22:0] a;
  wire [22:0] b;
  wire [22:0] zeta;
  wire [22:0] t;
  wire [22:0] c$app_arg;
  wire [23:0] sumWide;
  wire [23:0] result;
  wire [68:0] r_input;
  wire [45:0] c$bv;
  wire [45:0] r_output;

  assign r_input = {input_a,   input_b,
                    input_zeta};

  assign a = r_input[68:46];

  assign b = r_input[45:23];

  assign zeta = r_input[22:0];

  assign c$bv = ((({{(46-23) {1'b0}},zeta}) * ({{(46-23) {1'b0}},b})) % 46'd8380417);

  assign t = c$bv[0+:23];

  assign r_output = {result[0+:23],   c$app_arg};

  assign c$app_arg = (a >= t) ? (a - t) : (23'd8380417 - (t - a));

  assign sumWide = ({{(24-23) {1'b0}},a}) + ({{(24-23) {1'b0}},t});

  assign result = (sumWide >= 24'd8380417) ? (sumWide - 24'd8380417) : sumWide;

  assign output_outA = r_output[45:23];

  assign output_outB = r_output[22:0];


endmodule
`default_nettype wire

