/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module SN512_I272_O24_L2
    ( // Inputs
      input wire logic LOOKAHEAD  // clock
    , input wire logic CLK  // reset
    , input wire logic RST  // enable
    , input wire logic [274:0] EN

      // Outputs
    , output logic [23:0] COEFF_TDATA
    , output logic COEFF_TVALID
    , output logic COEFF_TLAST
    , output logic SEED_TREADY
    );
  SN512_I272_O24_L2_types::State c$ds_app_arg = {{2'b00,5'bxxxxx}
,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
,{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_0;
  logic msgValid;
  SN512_I272_O24_L2_types::Tuple2_2 result_0;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_1;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_2;
  logic [11:0] b1;
  logic [11:0] b0;
  logic [11:0] b4;
  logic [11:0] b3;
  logic [11:0] b2;
  logic [11:0] b1_0;
  logic [11:0] b0_0;
  logic [11:0] b3_0;
  logic [11:0] b2_0;
  logic [11:0] b1_1;
  logic [11:0] b0_1;
  logic [11:0] b2_1;
  logic [11:0] b1_2;
  logic [11:0] b0_2;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_3;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_4;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_5;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_6;
  logic [11:0] b0_3;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_7;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_8;
  SN512_I272_O24_L2_types::Tuple2_2 c$case_alt_9;
  logic tready;
  logic [11:0] c1;
  logic [11:0] c0;
  logic [11:0] c3;
  logic [11:0] c2;
  logic [11:0] c2_0;
  logic [11:0] c1_0;
  logic [11:0] c0_0;
  logic [11:0] c1_1;
  logic [11:0] c0_1;
  logic [11:0] c0_2;
  SN512_I272_O24_L2_types::Tuple2_2 result_1;
  logic [62:0] buffer;
  logic [1599:0] result_2;
  logic [1599:0] c$app_arg;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_0;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_7;
  logic [1599:0] c$app_arg_4;
  logic [271:0] inputMsg;
  logic [50:0] result_8;
  logic [50:0] c$case_alt_10;
  logic [50:0] c$case_alt_11;
  logic [50:0] c$case_alt_12;
  logic [50:0] c$case_alt_13;
  logic [50:0] c$case_alt_14;
  logic [50:0] c$case_alt_15;
  logic [50:0] c$case_alt_16;
  logic [50:0] c$case_alt_17;
  logic [11:0] c0_3;
  logic [50:0] c$case_alt_18;
  logic [50:0] c$case_alt_19;
  logic c$case_scrut;
  logic [50:0] c$case_alt_20;
  logic [50:0] c$case_alt_21;
  logic [11:0] c1_2;
  logic [50:0] c$case_alt_22;
  logic [50:0] c$case_alt_23;
  logic c$case_scrut_0;
  logic [11:0] c2_1;
  logic c$case_scrut_1;
  logic [11:0] c3_0;
  logic [47:0] c$c0_app_arg;
  logic [47:0] result_9;
  logic [47:0] c$case_alt_24;
  logic [47:0] c$case_alt_25;
  logic [47:0] c$case_alt_26;
  logic [47:0] c$case_alt_27;
  logic [47:0] c$case_alt_28;
  logic [47:0] c$case_alt_29;
  logic [47:0] c$case_alt_30;
  logic [47:0] c$case_alt_31;
  logic [47:0] c$case_alt_32;
  logic [47:0] c$case_alt_33;
  logic [47:0] c$case_alt_34;
  logic [47:0] c$case_alt_35;
  logic [47:0] c$case_alt_36;
  logic [47:0] c$case_alt_37;
  logic [47:0] c$case_alt_38;
  logic [47:0] c$case_alt_39;
  logic [47:0] c$case_alt_40;
  logic [47:0] c$case_alt_41;
  logic [47:0] c$case_alt_42;
  logic [47:0] c$case_alt_43;
  logic [47:0] c$case_alt_44;
  logic [47:0] c$case_alt_45;
  logic [47:0] c$case_alt_46;
  logic [47:0] c$case_alt_47;
  logic [47:0] c$case_alt_48;
  logic [47:0] c$case_alt_49;
  logic [47:0] c$case_alt_50;
  logic [1599:0] c$app_arg_5;
  logic [4:0] counter;
  logic [1599:0] c$keccakF1600_out;
  logic [4:0] counter_0;
  logic [6:0] phase;
  logic [1599:0] state;
  SN512_I272_O24_L2_types::Tuple2_3 EN_0;
  SN512_I272_O24_L2_types::Tuple2_4 result;
  SN512_I272_O24_L2_types::AXI4Stream COEFF;

  assign EN_0 = EN;

  // register begin
  always_ff @(posedge LOOKAHEAD or  posedge  CLK) begin : c$ds_app_arg_register
    if ( CLK) begin
      c$ds_app_arg <= {{2'b00,5'bxxxxx}
  ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  ,{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
    end else  if (RST)  begin
      c$ds_app_arg <= c$case_alt.Tuple2_2_sel0;
    end
  end
  // register end

  assign result = c$case_alt.Tuple2_2_sel1;

  always_comb begin
    case(phase[6:5])
      2'b00 : c$case_alt = c$case_alt_0;
      2'b01 : c$case_alt = result_1;
      default : c$case_alt = result_0;
    endcase
  end

  assign c$case_alt_0 = msgValid ? {{{2'b01,5'd0}
                                    ,result_2
                                    ,{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                   ,{{24'b000000000000000000000000,1'b0,1'b0}
                                    ,1'b0}} : {c$ds_app_arg
                                              ,{{24'b000000000000000000000000,1'b0,1'b0}
                                               ,1'b1}};

  assign msgValid = EN_0[2:2];

  always_comb begin
    case(buffer[62:60])
      3'b000 : result_0 = c$case_alt_2;
      3'b001 : result_0 = c$case_alt_1;
      3'b010 : result_0 = {{phase
                           ,state
                           ,{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                          ,{{{b0_2,b1_2},1'b1,1'b0},1'b0}};
      3'b011 : result_0 = {{phase
                           ,state
                           ,{3'b001,b2_1,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                          ,{{{b0_1,b1_1},1'b1,1'b0},1'b0}};
      3'b100 : result_0 = {{phase
                           ,state
                           ,{3'b010,b2_0,b3_0,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                          ,{{{b0_0,b1_0},1'b1,1'b0},1'b0}};
      default : result_0 = {{phase
                            ,state
                            ,{3'b011,b2,b3,b4,24'bxxxxxxxxxxxxxxxxxxxxxxxx}}
                           ,{{{b0,b1},1'b1,1'b0},1'b0}};
    endcase
  end

  always_comb begin
    case(result_8[50:48])
      3'b000 : c$case_alt_1 = {{{2'b10,counter + 5'd1}
                               ,state
                               ,buffer}
                              ,{{24'b000000000000000000000000,1'b0,1'b0}
                               ,1'b0}};
      3'b001 : c$case_alt_1 = c$case_alt_6;
      3'b010 : c$case_alt_1 = c$case_alt_5;
      3'b011 : c$case_alt_1 = c$case_alt_4;
      default : c$case_alt_1 = c$case_alt_3;
    endcase
  end

  always_comb begin
    case(result_8[50:48])
      3'b000 : c$case_alt_2 = {{{2'b10,counter + 5'd1}
                               ,state
                               ,{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                              ,{{24'b000000000000000000000000,1'b0,1'b0}
                               ,1'b0}};
      3'b001 : c$case_alt_2 = {{{2'b10,counter + 5'd1}
                               ,state
                               ,{3'b001,c0_2,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                              ,{{24'b000000000000000000000000,1'b0,1'b0}
                               ,1'b0}};
      3'b010 : c$case_alt_2 = c$case_alt_9;
      3'b011 : c$case_alt_2 = c$case_alt_8;
      default : c$case_alt_2 = c$case_alt_7;
    endcase
  end

  assign b1 = buffer[47:36];

  assign b0 = buffer[59:48];

  assign b4 = buffer[11:0];

  assign b3 = buffer[23:12];

  assign b2 = buffer[35:24];

  assign b1_0 = buffer[47:36];

  assign b0_0 = buffer[59:48];

  assign b3_0 = buffer[23:12];

  assign b2_0 = buffer[35:24];

  assign b1_1 = buffer[47:36];

  assign b0_1 = buffer[59:48];

  assign b2_1 = buffer[35:24];

  assign b1_2 = buffer[47:36];

  assign b0_2 = buffer[59:48];

  assign c$case_alt_3 = tready ? {{{2'b10,counter + 5'd1}
                                  ,state
                                  ,{3'b011,c1,c2,c3,24'bxxxxxxxxxxxxxxxxxxxxxxxx}}
                                 ,{{{b0_3,c0},1'b1,1'b0}
                                  ,1'b0}} : {{{2'b10,counter + 5'd1}
                                             ,state
                                             ,{3'b101,b0_3,c0,c1,c2,c3}}
                                            ,{{24'b000000000000000000000000,1'b0,1'b0}
                                             ,1'b0}};

  assign c$case_alt_4 = tready ? {{{2'b10,counter + 5'd1}
                                  ,state
                                  ,{3'b010,c1_0,c2_0,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                 ,{{{b0_3,c0_0},1'b1,1'b0}
                                  ,1'b0}} : {{{2'b10,counter + 5'd1}
                                             ,state
                                             ,{3'b100,b0_3,c0_0,c1_0,c2_0,12'bxxxxxxxxxxxx}}
                                            ,{{24'b000000000000000000000000,1'b0,1'b0}
                                             ,1'b0}};

  assign c$case_alt_5 = tready ? {{{2'b10,counter + 5'd1}
                                  ,state
                                  ,{3'b001,c1_1,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                 ,{{{b0_3,c0_1},1'b1,1'b0}
                                  ,1'b0}} : {{{2'b10,counter + 5'd1}
                                             ,state
                                             ,{3'b011,b0_3,c0_1,c1_1,24'bxxxxxxxxxxxxxxxxxxxxxxxx}}
                                            ,{{24'b000000000000000000000000,1'b0,1'b0}
                                             ,1'b0}};

  assign c$case_alt_6 = tready ? {{{2'b10,counter + 5'd1}
                                  ,state
                                  ,{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                 ,{{{b0_3,c0_2},1'b1,1'b0}
                                  ,1'b0}} : {{{2'b10,counter + 5'd1}
                                             ,state
                                             ,{3'b010,b0_3,c0_2,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                            ,{{24'b000000000000000000000000,1'b0,1'b0}
                                             ,1'b0}};

  assign b0_3 = buffer[59:48];

  assign c$case_alt_7 = tready ? {{{2'b10,counter + 5'd1}
                                  ,state
                                  ,{3'b010,c2,c3,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                 ,{{{c0,c1},1'b1,1'b0},1'b0}} : {c$ds_app_arg
                                                                ,{{24'b000000000000000000000000,1'b0,1'b0}
                                                                 ,1'b0}};

  assign c$case_alt_8 = tready ? {{{2'b10,counter + 5'd1}
                                  ,state
                                  ,{3'b001,c2_0,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                 ,{{{c0_0,c1_0},1'b1,1'b0}
                                  ,1'b0}} : {{{2'b10,counter + 5'd1}
                                             ,state
                                             ,{3'b011,c0_0,c1_0,c2_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx}}
                                            ,{{24'b000000000000000000000000,1'b0,1'b0}
                                             ,1'b0}};

  assign c$case_alt_9 = tready ? {{{2'b10,counter + 5'd1}
                                  ,state
                                  ,{3'b000,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                 ,{{{c0_1,c1_1},1'b1,1'b0}
                                  ,1'b0}} : {{{2'b10,counter + 5'd1}
                                             ,state
                                             ,{3'b010,c0_1,c1_1,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}
                                            ,{{24'b000000000000000000000000,1'b0,1'b0}
                                             ,1'b0}};

  assign tready = EN_0.Tuple2_3_sel1;

  assign c1 = result_8[35:24];

  assign c0 = result_8[47:36];

  assign c3 = result_8[11:0];

  assign c2 = result_8[23:12];

  assign c2_0 = result_8[23:12];

  assign c1_0 = result_8[35:24];

  assign c0_0 = result_8[47:36];

  assign c1_1 = result_8[35:24];

  assign c0_1 = result_8[47:36];

  assign c0_2 = result_8[47:36];

  assign result_1 = (counter_0 == 5'd23) ? {{{2'b10,5'd0}
                                            ,c$keccakF1600_out
                                            ,buffer}
                                           ,{{24'b000000000000000000000000,1'b0,1'b0}
                                            ,1'b0}} : {{{2'b01,counter_0 + 5'd1}
                                                       ,c$keccakF1600_out
                                                       ,buffer}
                                                      ,{{24'b000000000000000000000000,1'b0,1'b0}
                                                       ,1'b0}};

  assign buffer = c$ds_app_arg.State_sel2;

  // replaceBit start
  always_comb begin
    result_2 = c$app_arg;
    result_2[64'sd1343] = (~ (c$app_arg[64'sd1343]));
  end
  // replaceBit end

  assign c$app_arg = result_3;

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_0;
    result_3[64'sd272] = (~ (c$app_arg_0[64'sd272]));
  end
  // replaceBit end

  assign c$app_arg_0 = result_4;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_1;
    result_4[64'sd273] = (~ (c$app_arg_1[64'sd273]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_2;
    result_5[64'sd274] = (~ (c$app_arg_2[64'sd274]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_3;
    result_6[64'sd275] = (~ (c$app_arg_3[64'sd275]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_7;

  // replaceBit start
  always_comb begin
    result_7 = c$app_arg_4;
    result_7[64'sd276] = (~ (c$app_arg_4[64'sd276]));
  end
  // replaceBit end

  assign c$app_arg_4 = ({1328'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,inputMsg});

  assign inputMsg = EN_0[274:3];

  assign result_8 = (c0_3 < 12'b110100000001) ? c$case_alt_10 : c$case_alt_11;

  assign c$case_alt_10 = c$case_scrut ? c$case_alt_12 : c$case_alt_13;

  assign c$case_alt_11 = c$case_scrut ? c$case_alt_18 : c$case_alt_19;

  assign c$case_alt_12 = c$case_scrut_0 ? c$case_alt_14 : c$case_alt_15;

  assign c$case_alt_13 = c$case_scrut_0 ? c$case_alt_16 : c$case_alt_17;

  assign c$case_alt_14 = c$case_scrut_1 ? {3'b100,c0_3,c1_2,c2_1,c3_0} : {3'b011,c0_3,c1_2,c2_1,12'bxxxxxxxxxxxx};

  assign c$case_alt_15 = c$case_scrut_1 ? {3'b011,c0_3,c1_2,c3_0,12'bxxxxxxxxxxxx} : {3'b010,c0_3,c1_2,24'bxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_16 = c$case_scrut_1 ? {3'b011,c0_3,c2_1,c3_0,12'bxxxxxxxxxxxx} : {3'b010,c0_3,c2_1,24'bxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_17 = c$case_scrut_1 ? {3'b010,c0_3,c3_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b001,c0_3,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c0_3 = c$c0_app_arg[11 : 0];

  assign c$case_alt_18 = c$case_scrut_0 ? c$case_alt_20 : c$case_alt_21;

  assign c$case_alt_19 = c$case_scrut_0 ? c$case_alt_22 : c$case_alt_23;

  assign c$case_scrut = c1_2 < 12'b110100000001;

  assign c$case_alt_20 = c$case_scrut_1 ? {3'b011,c1_2,c2_1,c3_0,12'bxxxxxxxxxxxx} : {3'b010,c1_2,c2_1,24'bxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_21 = c$case_scrut_1 ? {3'b010,c1_2,c3_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b001,c1_2,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c1_2 = c$c0_app_arg[23 : 12];

  assign c$case_alt_22 = c$case_scrut_1 ? {3'b010,c2_1,c3_0,24'bxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b001,c2_1,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt_23 = c$case_scrut_1 ? {3'b001,c3_0,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {3'b000,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_scrut_0 = c2_1 < 12'b110100000001;

  assign c2_1 = c$c0_app_arg[35 : 24];

  assign c$case_scrut_1 = c3_0 < 12'b110100000001;

  assign c3_0 = c$c0_app_arg[47 : 36];

  assign c$c0_app_arg = result_9;

  assign result_9 = (counter == 5'd0) ? (c$app_arg_5[47 : 0]) : c$case_alt_24;

  assign c$case_alt_24 = (counter == 5'd1) ? (c$app_arg_5[95 : 48]) : c$case_alt_25;

  assign c$case_alt_25 = (counter == 5'd2) ? (c$app_arg_5[143 : 96]) : c$case_alt_26;

  assign c$case_alt_26 = (counter == 5'd3) ? (c$app_arg_5[191 : 144]) : c$case_alt_27;

  assign c$case_alt_27 = (counter == 5'd4) ? (c$app_arg_5[239 : 192]) : c$case_alt_28;

  assign c$case_alt_28 = (counter == 5'd5) ? (c$app_arg_5[287 : 240]) : c$case_alt_29;

  assign c$case_alt_29 = (counter == 5'd6) ? (c$app_arg_5[335 : 288]) : c$case_alt_30;

  assign c$case_alt_30 = (counter == 5'd7) ? (c$app_arg_5[383 : 336]) : c$case_alt_31;

  assign c$case_alt_31 = (counter == 5'd8) ? (c$app_arg_5[431 : 384]) : c$case_alt_32;

  assign c$case_alt_32 = (counter == 5'd9) ? (c$app_arg_5[479 : 432]) : c$case_alt_33;

  assign c$case_alt_33 = (counter == 5'd10) ? (c$app_arg_5[527 : 480]) : c$case_alt_34;

  assign c$case_alt_34 = (counter == 5'd11) ? (c$app_arg_5[575 : 528]) : c$case_alt_35;

  assign c$case_alt_35 = (counter == 5'd12) ? (c$app_arg_5[623 : 576]) : c$case_alt_36;

  assign c$case_alt_36 = (counter == 5'd13) ? (c$app_arg_5[671 : 624]) : c$case_alt_37;

  assign c$case_alt_37 = (counter == 5'd14) ? (c$app_arg_5[719 : 672]) : c$case_alt_38;

  assign c$case_alt_38 = (counter == 5'd15) ? (c$app_arg_5[767 : 720]) : c$case_alt_39;

  assign c$case_alt_39 = (counter == 5'd16) ? (c$app_arg_5[815 : 768]) : c$case_alt_40;

  assign c$case_alt_40 = (counter == 5'd17) ? (c$app_arg_5[863 : 816]) : c$case_alt_41;

  assign c$case_alt_41 = (counter == 5'd18) ? (c$app_arg_5[911 : 864]) : c$case_alt_42;

  assign c$case_alt_42 = (counter == 5'd19) ? (c$app_arg_5[959 : 912]) : c$case_alt_43;

  assign c$case_alt_43 = (counter == 5'd20) ? (c$app_arg_5[1007 : 960]) : c$case_alt_44;

  assign c$case_alt_44 = (counter == 5'd21) ? (c$app_arg_5[1055 : 1008]) : c$case_alt_45;

  assign c$case_alt_45 = (counter == 5'd22) ? (c$app_arg_5[1103 : 1056]) : c$case_alt_46;

  assign c$case_alt_46 = (counter == 5'd23) ? (c$app_arg_5[1151 : 1104]) : c$case_alt_47;

  assign c$case_alt_47 = (counter == 5'd24) ? (c$app_arg_5[1199 : 1152]) : c$case_alt_48;

  assign c$case_alt_48 = (counter == 5'd25) ? (c$app_arg_5[1247 : 1200]) : c$case_alt_49;

  assign c$case_alt_49 = (counter == 5'd26) ? (c$app_arg_5[1295 : 1248]) : c$case_alt_50;

  assign c$case_alt_50 = (counter == 5'd27) ? (c$app_arg_5[1343 : 1296]) : ({48 {1'bx}});

  assign c$app_arg_5 = state;

  assign counter = phase[4:0];

  Component_SampleNTT512N_i272o24l2_keccakF1600 Component_SampleNTT512N_i272o24l2_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (counter_0)
    , .x (state) );

  assign counter_0 = phase[4:0];

  assign phase = c$ds_app_arg.State_sel0;

  assign state = c$ds_app_arg.State_sel1;

  assign COEFF = result.Tuple2_4_sel0;

  assign SEED_TREADY = result.Tuple2_4_sel1;

  assign COEFF_TDATA = COEFF.AXI4Stream_sel0;

  assign COEFF_TVALID = COEFF.AXI4Stream_sel1;

  assign COEFF_TLAST = COEFF.AXI4Stream_sel2;


endmodule

