/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_PRF
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [1:0] ETA
    , input wire logic [263:0] MSG_33B
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [65:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    );
  logic [1616:0] c$ds_app_arg = {2'b00,1615'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  Component_PRF_types::Tuple2 c$case_alt;
  logic [63:0] c$app_arg;
  logic [63:0] c$case_alt_0;
  logic [63:0] c$case_alt_1;
  logic [63:0] c$case_alt_2;
  logic [63:0] c$case_alt_3;
  logic [63:0] c$case_alt_4;
  logic [63:0] c$case_alt_5;
  logic [63:0] c$case_alt_6;
  logic [63:0] c$case_alt_7;
  logic [63:0] c$case_alt_8;
  logic [63:0] c$case_alt_9;
  logic [63:0] c$case_alt_10;
  logic [63:0] c$case_alt_11;
  logic [63:0] c$case_alt_12;
  logic [63:0] c$case_alt_13;
  logic [63:0] c$case_alt_14;
  logic [1599:0] c$app_arg_0;
  logic [1616:0] c$app_arg_1;
  logic [1616:0] c$case_alt_15;
  logic [1616:0] c$case_alt_16;
  logic c$case_scrut;
  logic [1599:0] state;
  logic [4:0] inBlockIdx;
  logic [4:0] c$app_arg_2;
  logic [4:0] totalWords;
  logic signed [63:0] c$inBlockIdx_app_arg;
  logic [4:0] wordIdx;
  Component_PRF_types::Tuple2 result_0;
  logic [4:0] totalWords_0;
  logic [4:0] wordIdx_0;
  logic [1599:0] result_1;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_2;
  logic [1599:0] c$app_arg_4;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_5;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_6;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_7;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_8;
  logic [4:0] c$app_arg_9;
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] state_0;
  logic [4:0] roundIdx;
  logic [4:0] c$i_24;
  Component_PRF_types::Tuple2_0 result;
  Component_PRF_types::AXI4Stream DIGEST_TDATA_0;

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {2'b00,1615'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt.Tuple2_sel0;
    end
  end
  // register end

  assign result = c$case_alt.Tuple2_sel1;

  always_comb begin
    case(c$ds_app_arg[1616:1615])
      2'b00 : c$case_alt = {{2'b01,5'd0,5'd0,c$app_arg_9,result_1}
                           ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                             ,1'b0
                             ,1'b0}
                            ,1'b1}};
      2'b01 : c$case_alt = result_0;
      2'b10 : c$case_alt = {c$app_arg_1
                           ,{{c$app_arg,1'b1,c$case_scrut},1'b0}};
      default : c$case_alt = {{2'b11,1615'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                             ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                               ,1'b0
                               ,1'b0}
                              ,1'b0}};
    endcase
  end

  assign c$app_arg = (inBlockIdx == 5'd0) ? (c$app_arg_0[1599 : 1536]) : c$case_alt_0;

  assign c$case_alt_0 = (inBlockIdx == 5'd1) ? (c$app_arg_0[1535 : 1472]) : c$case_alt_1;

  assign c$case_alt_1 = (inBlockIdx == 5'd2) ? (c$app_arg_0[1471 : 1408]) : c$case_alt_2;

  assign c$case_alt_2 = (inBlockIdx == 5'd3) ? (c$app_arg_0[1407 : 1344]) : c$case_alt_3;

  assign c$case_alt_3 = (inBlockIdx == 5'd4) ? (c$app_arg_0[1343 : 1280]) : c$case_alt_4;

  assign c$case_alt_4 = (inBlockIdx == 5'd5) ? (c$app_arg_0[1279 : 1216]) : c$case_alt_5;

  assign c$case_alt_5 = (inBlockIdx == 5'd6) ? (c$app_arg_0[1215 : 1152]) : c$case_alt_6;

  assign c$case_alt_6 = (inBlockIdx == 5'd7) ? (c$app_arg_0[1151 : 1088]) : c$case_alt_7;

  assign c$case_alt_7 = (inBlockIdx == 5'd8) ? (c$app_arg_0[1087 : 1024]) : c$case_alt_8;

  assign c$case_alt_8 = (inBlockIdx == 5'd9) ? (c$app_arg_0[1023 : 960]) : c$case_alt_9;

  assign c$case_alt_9 = (inBlockIdx == 5'd10) ? (c$app_arg_0[959 : 896]) : c$case_alt_10;

  assign c$case_alt_10 = (inBlockIdx == 5'd11) ? (c$app_arg_0[895 : 832]) : c$case_alt_11;

  assign c$case_alt_11 = (inBlockIdx == 5'd12) ? (c$app_arg_0[831 : 768]) : c$case_alt_12;

  assign c$case_alt_12 = (inBlockIdx == 5'd13) ? (c$app_arg_0[767 : 704]) : c$case_alt_13;

  assign c$case_alt_13 = (inBlockIdx == 5'd14) ? (c$app_arg_0[703 : 640]) : c$case_alt_14;

  assign c$case_alt_14 = (inBlockIdx == 5'd15) ? (c$app_arg_0[639 : 576]) : (c$app_arg_0[575 : 512]);

  assign c$app_arg_0 = state;

  assign c$app_arg_1 = DIGEST_TREADY ? c$case_alt_15 : c$ds_app_arg;

  assign c$case_alt_15 = c$case_scrut ? {2'b11,1615'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : c$case_alt_16;

  assign c$case_alt_16 = (inBlockIdx == 5'd16) ? {2'b01,5'd0,c$app_arg_2,totalWords,state} : {2'b10,c$app_arg_2,totalWords,state,5'bxxxxx};

  assign c$case_scrut = wordIdx == (totalWords - 5'd1);

  assign state = c$ds_app_arg[1604:5];

  assign inBlockIdx = $unsigned(c$inBlockIdx_app_arg[0+:5]);

  assign c$app_arg_2 = wordIdx + 5'd1;

  assign totalWords = c$ds_app_arg[1609:1605];

  assign c$i_24 = (wordIdx % 5'd17);

  assign c$inBlockIdx_app_arg = $unsigned({{(64-5) {1'b0}},c$i_24});

  assign wordIdx = c$ds_app_arg[1614:1610];

  assign result_0 = (roundIdx == 5'd23) ? {{2'b10,wordIdx_0,totalWords_0,c$keccakF1600_out,5'bxxxxx}
                                          ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                            ,1'b0
                                            ,1'b0}
                                           ,1'b0}} : {{2'b01,roundIdx + 5'd1,wordIdx_0,totalWords_0,c$keccakF1600_out}
                                                     ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                       ,1'b0
                                                       ,1'b0}
                                                      ,1'b0}};

  assign totalWords_0 = c$ds_app_arg[1604:1600];

  assign wordIdx_0 = c$ds_app_arg[1609:1605];

  // replaceBit start
  always_comb begin
    result_1 = c$app_arg_3;
    result_1[64'sd512] = (~ (c$app_arg_3[64'sd512]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_2;

  // replaceBit start
  always_comb begin
    result_2 = c$app_arg_4;
    result_2[64'sd1331] = (~ (c$app_arg_4[64'sd1331]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_3;

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_5;
    result_3[64'sd1332] = (~ (c$app_arg_5[64'sd1332]));
  end
  // replaceBit end

  assign c$app_arg_5 = result_4;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_6;
    result_4[64'sd1333] = (~ (c$app_arg_6[64'sd1333]));
  end
  // replaceBit end

  assign c$app_arg_6 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_7;
    result_5[64'sd1334] = (~ (c$app_arg_7[64'sd1334]));
  end
  // replaceBit end

  assign c$app_arg_7 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_8;
    result_6[64'sd1335] = (~ (c$app_arg_8[64'sd1335]));
  end
  // replaceBit end

  assign c$app_arg_8 = ({MSG_33B,1336'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000});

  assign c$app_arg_9 = (ETA == 2'd3) ? 5'd24 : 5'd16;

  Component_PRF_topEntity_keccakF1600 Component_PRF_topEntity_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (roundIdx)
    , .x (state_0) );

  assign state_0 = c$ds_app_arg[1599:0];

  assign roundIdx = c$ds_app_arg[1614:1610];

  assign DIGEST_TDATA_0 = result.Tuple2_0_sel0;

  assign DIGEST_TVALID = result.Tuple2_0_sel1;

  assign DIGEST_TDATA = DIGEST_TDATA_0;


endmodule

