/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module dut
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [22:0] A
    , input wire logic [22:0] B

      // Outputs
    , output logic [22:0] SUM
    );
  logic [23:0] result;
  // src/Component/NTT.hs:65:1-9
  logic [22:0] x;
  // src/Component/NTT.hs:65:1-9
  logic [22:0] y;
  // src/Component/NTT.hs:65:1-9
  logic [23:0] s;
  dut_types::Tuple2 eta;
  logic [22:0] c$bv;
  logic [22:0] c$bv_0;

  assign eta = {A,B};

  assign result = (s >= 24'd8380417) ? (s - 24'd8380417) : s;

  assign x = eta.Tuple2_sel0;

  assign y = eta.Tuple2_sel1;

  assign c$bv = (x);

  assign c$bv_0 = (y);

  assign s = ({{(24-23) {1'b0}},(x)}) + ({{(24-23) {1'b0}},(y)});

  assign SUM = ((result[0+:23]));


endmodule

