name:                 ml-dsa
version:              0.1.0.0
visibility:           public
id:                   ml-dsa-0.1.0.0-AhLEacyvZIBLevhQusHjWX
key:                  ml-dsa-0.1.0.0-AhLEacyvZIBLevhQusHjWX
license:              MIT
author:               Jason
synopsis:             ML-DSA implementation in Haskell
abi:                  023b600f98524118cb602147edc7dc09
exposed:              True
exposed-modules:
    Component.NTT MLDSA MLDSA.Auxiliary MLDSA.KeyGen MLDSA.NTT
    MLDSA.Polynomial

import-dirs:
    /Users/jason/Desktop/ML-DSA/.stack-work/install/aarch64-osx/022492403c0f831abcac5570a990ea27c267c1fe67cf350e647d3fb5731b7856/9.12.4/lib/aarch64-osx-ghc-9.12.4-6f4d/ml-dsa-0.1.0.0-AhLEacyvZIBLevhQusHjWX

library-dirs:
    /Users/jason/Desktop/ML-DSA/.stack-work/install/aarch64-osx/022492403c0f831abcac5570a990ea27c267c1fe67cf350e647d3fb5731b7856/9.12.4/lib/aarch64-osx-ghc-9.12.4-6f4d/ml-dsa-0.1.0.0-AhLEacyvZIBLevhQusHjWX

library-dirs-static:
    /Users/jason/Desktop/ML-DSA/.stack-work/install/aarch64-osx/022492403c0f831abcac5570a990ea27c267c1fe67cf350e647d3fb5731b7856/9.12.4/lib/aarch64-osx-ghc-9.12.4-6f4d/ml-dsa-0.1.0.0-AhLEacyvZIBLevhQusHjWX

dynamic-library-dirs:
    /Users/jason/Desktop/ML-DSA/.stack-work/install/aarch64-osx/022492403c0f831abcac5570a990ea27c267c1fe67cf350e647d3fb5731b7856/9.12.4/lib/aarch64-osx-ghc-9.12.4-6f4d

data-dir:
    /Users/jason/Desktop/ML-DSA/.stack-work/install/aarch64-osx/022492403c0f831abcac5570a990ea27c267c1fe67cf350e647d3fb5731b7856/9.12.4/share/aarch64-osx-ghc-9.12.4-6f4d/ml-dsa-0.1.0.0

hs-libraries:         HSml-dsa-0.1.0.0-AhLEacyvZIBLevhQusHjWX
depends:
    base-4.21.2.0-fc24 bytestring-0.12.2.0-53dd
    clash-prelude-1.10.0-D4ddKott1a74EYZemly8aC
    crypton-1.1.4-6IWMcMZyOdI7nSLUBs6rED
    ghc-typelits-extra-0.5.4-2jVAFqjI0cw8rfJO4EBmx
    ghc-typelits-knownnat-0.8.4-E36C8Y9DYXz90dbRsrhI5h
    ghc-typelits-natnormalise-0.9.6-I8dSj9ElgfqH6sQCEMbQVg
    ram-0.22.0-3h64r6e6zxJ8InrEhaeMS
    vector-0.13.2.0-7pQu0DajM8Y7U02fAK2Zxp

haddock-interfaces:
    /Users/jason/Desktop/ML-DSA/.stack-work/install/aarch64-osx/022492403c0f831abcac5570a990ea27c267c1fe67cf350e647d3fb5731b7856/9.12.4/doc/ml-dsa-0.1.0.0/ml-dsa.haddock

haddock-html:
    /Users/jason/Desktop/ML-DSA/.stack-work/install/aarch64-osx/022492403c0f831abcac5570a990ea27c267c1fe67cf350e647d3fb5731b7856/9.12.4/doc/ml-dsa-0.1.0.0
