/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_SamplePolyCBD512
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [263:0] MSG_33B
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [13:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    );
  logic [1617:0] c$ds_app_arg = {2'b00,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  Component_SamplePolyCBD512_types::Tuple2_2 c$case_alt;
  Component_SamplePolyCBD512_types::Tuple2_2 result_0;
  Component_SamplePolyCBD512_types::Tuple2_2 c$case_alt_0;
  logic [1617:0] c$app_arg;
  logic [1617:0] c$case_alt_1;
  logic [1617:0] c$app_arg_0;
  logic [1617:0] c$case_alt_2;
  logic c$case_scrut;
  logic isLast;
  logic [7:0] c$app_arg_1;
  logic [11:0] result_1;
  logic [2:0] a;
  logic [2:0] b;
  logic [5:0] c$b_app_arg;
  Component_SamplePolyCBD512_types::Tuple2_2 result_2;
  logic [2:0] whichBlock;
  logic [7:0] coeffIdx;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_4;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_5;
  logic [1599:0] result_7;
  logic [1599:0] c$app_arg_6;
  logic [1599:0] result_8;
  logic [1599:0] c$app_arg_7;
  Component_SamplePolyCBD512_types::array_of_6_logic_vector_1 result_9;
  Component_SamplePolyCBD512_types::array_of_6_logic c$map_arg4;
  Component_SamplePolyCBD512_types::array_of_6_logic c$map_arg4_case_alt;
  Component_SamplePolyCBD512_types::array_of_6_logic c$map_arg4_app_arg;
  logic [5:0] c$map_arg4_app_arg_0;
  logic [1:0] tail2;
  logic [2:0] whichBlock_0;
  logic [5:0] result_10;
  logic [5:0] c$map_arg4_case_alt_0;
  logic [5:0] c$map_arg4_case_alt_1;
  logic [5:0] c$map_arg4_case_alt_2;
  logic [5:0] c$map_arg4_case_alt_3;
  logic [5:0] c$map_arg4_case_alt_4;
  logic [5:0] c$map_arg4_case_alt_5;
  logic [5:0] c$map_arg4_case_alt_6;
  logic [5:0] c$map_arg4_case_alt_7;
  logic [5:0] c$map_arg4_case_alt_8;
  logic [5:0] c$map_arg4_case_alt_9;
  logic [5:0] c$map_arg4_case_alt_10;
  logic [5:0] c$map_arg4_case_alt_11;
  logic [5:0] c$map_arg4_case_alt_12;
  logic [5:0] c$map_arg4_case_alt_13;
  logic [5:0] c$map_arg4_case_alt_14;
  logic [5:0] c$map_arg4_case_alt_15;
  logic [5:0] c$map_arg4_case_alt_16;
  logic [5:0] c$map_arg4_case_alt_17;
  logic [5:0] c$map_arg4_case_alt_18;
  logic [5:0] c$map_arg4_case_alt_19;
  logic [5:0] c$map_arg4_case_alt_20;
  logic [5:0] c$map_arg4_case_alt_21;
  logic [5:0] c$map_arg4_case_alt_22;
  logic [5:0] c$map_arg4_case_alt_23;
  logic [5:0] c$map_arg4_case_alt_24;
  logic [5:0] c$map_arg4_case_alt_25;
  logic [5:0] c$map_arg4_case_alt_26;
  logic [5:0] c$map_arg4_case_alt_27;
  logic [5:0] c$map_arg4_case_alt_28;
  logic [5:0] c$map_arg4_case_alt_29;
  logic [5:0] c$map_arg4_case_alt_30;
  logic [5:0] c$map_arg4_case_alt_31;
  logic [5:0] c$map_arg4_case_alt_32;
  logic [5:0] c$map_arg4_case_alt_33;
  logic [5:0] c$map_arg4_case_alt_34;
  logic [5:0] c$map_arg4_case_alt_35;
  logic [5:0] c$map_arg4_case_alt_36;
  logic [5:0] c$map_arg4_case_alt_37;
  logic [5:0] c$map_arg4_case_alt_38;
  logic [5:0] c$map_arg4_case_alt_39;
  logic [5:0] c$map_arg4_case_alt_40;
  logic [5:0] c$map_arg4_case_alt_41;
  logic [5:0] c$map_arg4_case_alt_42;
  logic [5:0] c$map_arg4_case_alt_43;
  logic [5:0] c$map_arg4_case_alt_44;
  logic [5:0] c$map_arg4_case_alt_45;
  logic [5:0] c$map_arg4_case_alt_46;
  logic [5:0] c$map_arg4_case_alt_47;
  logic [5:0] c$map_arg4_case_alt_48;
  logic [5:0] c$map_arg4_case_alt_49;
  logic [5:0] c$map_arg4_case_alt_50;
  logic [5:0] c$map_arg4_case_alt_51;
  logic [5:0] c$map_arg4_case_alt_52;
  logic [5:0] c$map_arg4_case_alt_53;
  logic [5:0] c$map_arg4_case_alt_54;
  logic [5:0] c$map_arg4_case_alt_55;
  logic [5:0] c$map_arg4_case_alt_56;
  logic [5:0] c$map_arg4_case_alt_57;
  logic [5:0] c$map_arg4_case_alt_58;
  logic [5:0] c$map_arg4_case_alt_59;
  logic [5:0] c$map_arg4_case_alt_60;
  logic [5:0] c$map_arg4_case_alt_61;
  logic [5:0] c$map_arg4_case_alt_62;
  logic [5:0] c$map_arg4_case_alt_63;
  logic [5:0] c$map_arg4_case_alt_64;
  logic [5:0] c$map_arg4_case_alt_65;
  logic [5:0] c$map_arg4_case_alt_66;
  logic [5:0] c$map_arg4_case_alt_67;
  logic [5:0] c$map_arg4_case_alt_68;
  logic [5:0] c$map_arg4_case_alt_69;
  logic [5:0] c$map_arg4_case_alt_70;
  logic [5:0] c$map_arg4_case_alt_71;
  logic [5:0] c$map_arg4_case_alt_72;
  logic [6:0] ds1;
  logic signed [63:0] c$ds1_app_arg;
  Component_SamplePolyCBD512_types::array_of_6_logic c$map_arg4_case_alt_73;
  Component_SamplePolyCBD512_types::array_of_6_logic c$map_arg4_app_arg_1;
  logic [5:0] result_11;
  logic [5:0] c$map_arg4_case_alt_74;
  logic [5:0] c$map_arg4_case_alt_75;
  logic [5:0] c$map_arg4_case_alt_76;
  logic [5:0] c$map_arg4_case_alt_77;
  logic [5:0] c$map_arg4_case_alt_78;
  logic [5:0] c$map_arg4_case_alt_79;
  logic [5:0] c$map_arg4_case_alt_80;
  logic [5:0] c$map_arg4_case_alt_81;
  logic [5:0] c$map_arg4_case_alt_82;
  logic [5:0] c$map_arg4_case_alt_83;
  logic [5:0] c$map_arg4_case_alt_84;
  logic [5:0] c$map_arg4_case_alt_85;
  logic [5:0] c$map_arg4_case_alt_86;
  logic [5:0] c$map_arg4_case_alt_87;
  logic [5:0] c$map_arg4_case_alt_88;
  logic [5:0] c$map_arg4_case_alt_89;
  logic [5:0] c$map_arg4_case_alt_90;
  logic [5:0] c$map_arg4_case_alt_91;
  logic [5:0] c$map_arg4_case_alt_92;
  logic [5:0] c$map_arg4_case_alt_93;
  logic [5:0] c$map_arg4_case_alt_94;
  logic [5:0] c$map_arg4_case_alt_95;
  logic [5:0] c$map_arg4_case_alt_96;
  logic [5:0] c$map_arg4_case_alt_97;
  logic [5:0] c$map_arg4_case_alt_98;
  logic [5:0] c$map_arg4_case_alt_99;
  logic [5:0] c$map_arg4_case_alt_100;
  logic [5:0] c$map_arg4_case_alt_101;
  logic [5:0] c$map_arg4_case_alt_102;
  logic [5:0] c$map_arg4_case_alt_103;
  logic [5:0] c$map_arg4_case_alt_104;
  logic [5:0] c$map_arg4_case_alt_105;
  logic [5:0] c$map_arg4_case_alt_106;
  logic [5:0] c$map_arg4_case_alt_107;
  logic [5:0] c$map_arg4_case_alt_108;
  logic [5:0] c$map_arg4_case_alt_109;
  logic [5:0] c$map_arg4_case_alt_110;
  logic [5:0] c$map_arg4_case_alt_111;
  logic [5:0] c$map_arg4_case_alt_112;
  logic [5:0] c$map_arg4_case_alt_113;
  logic [5:0] c$map_arg4_case_alt_114;
  logic [5:0] c$map_arg4_case_alt_115;
  logic [5:0] c$map_arg4_case_alt_116;
  logic [5:0] c$map_arg4_case_alt_117;
  logic [5:0] c$map_arg4_case_alt_118;
  logic [5:0] c$map_arg4_case_alt_119;
  logic [5:0] c$map_arg4_case_alt_120;
  logic [5:0] c$map_arg4_case_alt_121;
  logic [5:0] c$map_arg4_case_alt_122;
  logic [5:0] c$map_arg4_case_alt_123;
  logic [5:0] c$map_arg4_case_alt_124;
  logic [5:0] c$map_arg4_case_alt_125;
  logic [5:0] c$map_arg4_case_alt_126;
  logic [5:0] c$map_arg4_case_alt_127;
  logic [5:0] c$map_arg4_case_alt_128;
  logic [5:0] c$map_arg4_case_alt_129;
  logic [5:0] c$map_arg4_case_alt_130;
  logic [5:0] c$map_arg4_case_alt_131;
  logic [5:0] c$map_arg4_case_alt_132;
  logic [5:0] c$map_arg4_case_alt_133;
  logic [5:0] c$map_arg4_case_alt_134;
  logic [5:0] c$map_arg4_case_alt_135;
  logic [5:0] c$map_arg4_case_alt_136;
  logic [5:0] c$map_arg4_case_alt_137;
  logic [5:0] c$map_arg4_case_alt_138;
  logic [5:0] c$map_arg4_case_alt_139;
  logic [5:0] c$map_arg4_case_alt_140;
  logic [5:0] c$map_arg4_case_alt_141;
  logic [5:0] c$map_arg4_case_alt_142;
  logic [5:0] c$map_arg4_case_alt_143;
  logic [5:0] c$map_arg4_case_alt_144;
  logic [5:0] c$map_arg4_case_alt_145;
  logic [5:0] c$map_arg4_case_alt_146;
  logic [5:0] c$map_arg4_case_alt_147;
  logic [5:0] c$map_arg4_case_alt_148;
  logic [5:0] c$map_arg4_case_alt_149;
  logic [5:0] c$map_arg4_case_alt_150;
  logic [5:0] c$map_arg4_case_alt_151;
  logic [5:0] c$map_arg4_case_alt_152;
  logic [5:0] c$map_arg4_case_alt_153;
  logic [5:0] c$map_arg4_case_alt_154;
  logic [5:0] c$map_arg4_case_alt_155;
  logic [5:0] c$map_arg4_case_alt_156;
  logic [5:0] c$map_arg4_case_alt_157;
  logic [5:0] c$map_arg4_case_alt_158;
  logic [5:0] c$map_arg4_case_alt_159;
  logic [5:0] c$map_arg4_case_alt_160;
  logic [5:0] c$map_arg4_case_alt_161;
  logic [5:0] c$map_arg4_case_alt_162;
  logic [5:0] c$map_arg4_case_alt_163;
  logic [5:0] c$map_arg4_case_alt_164;
  logic [5:0] c$map_arg4_case_alt_165;
  logic [5:0] c$map_arg4_case_alt_166;
  logic [5:0] c$map_arg4_case_alt_167;
  logic [5:0] c$map_arg4_case_alt_168;
  logic [5:0] c$map_arg4_case_alt_169;
  logic [5:0] c$map_arg4_case_alt_170;
  logic [5:0] c$map_arg4_case_alt_171;
  logic [5:0] c$map_arg4_case_alt_172;
  logic [5:0] c$map_arg4_case_alt_173;
  logic [5:0] c$map_arg4_case_alt_174;
  logic [5:0] c$map_arg4_case_alt_175;
  logic [5:0] c$map_arg4_case_alt_176;
  logic [5:0] c$map_arg4_case_alt_177;
  logic [5:0] c$map_arg4_case_alt_178;
  logic [5:0] c$map_arg4_case_alt_179;
  logic [5:0] c$map_arg4_case_alt_180;
  logic [5:0] c$map_arg4_case_alt_181;
  logic [5:0] c$map_arg4_case_alt_182;
  logic [5:0] c$map_arg4_case_alt_183;
  logic [5:0] c$map_arg4_case_alt_184;
  logic [5:0] c$map_arg4_case_alt_185;
  logic [5:0] c$map_arg4_case_alt_186;
  logic [5:0] c$map_arg4_case_alt_187;
  logic [5:0] c$map_arg4_case_alt_188;
  logic [5:0] c$map_arg4_case_alt_189;
  logic [5:0] c$map_arg4_case_alt_190;
  logic [5:0] c$map_arg4_case_alt_191;
  logic [5:0] c$map_arg4_case_alt_192;
  logic [5:0] c$map_arg4_case_alt_193;
  logic [5:0] c$map_arg4_case_alt_194;
  logic [5:0] c$map_arg4_case_alt_195;
  logic [5:0] c$map_arg4_case_alt_196;
  logic [5:0] c$map_arg4_case_alt_197;
  logic [5:0] c$map_arg4_case_alt_198;
  logic [5:0] c$map_arg4_case_alt_199;
  logic [5:0] c$map_arg4_case_alt_200;
  logic [5:0] c$map_arg4_case_alt_201;
  logic [5:0] c$map_arg4_case_alt_202;
  logic [5:0] c$map_arg4_case_alt_203;
  logic [5:0] c$map_arg4_case_alt_204;
  logic [5:0] c$map_arg4_case_alt_205;
  logic [5:0] c$map_arg4_case_alt_206;
  logic [5:0] c$map_arg4_case_alt_207;
  logic [5:0] c$map_arg4_case_alt_208;
  logic [5:0] c$map_arg4_case_alt_209;
  logic [5:0] c$map_arg4_case_alt_210;
  logic [5:0] c$map_arg4_case_alt_211;
  logic [5:0] c$map_arg4_case_alt_212;
  logic [5:0] c$map_arg4_case_alt_213;
  logic [5:0] c$map_arg4_case_alt_214;
  logic [5:0] c$map_arg4_case_alt_215;
  logic [5:0] c$map_arg4_case_alt_216;
  logic [5:0] c$map_arg4_case_alt_217;
  logic [5:0] c$map_arg4_case_alt_218;
  logic [5:0] c$map_arg4_case_alt_219;
  logic [5:0] c$map_arg4_case_alt_220;
  logic [5:0] c$map_arg4_case_alt_221;
  logic [5:0] c$map_arg4_case_alt_222;
  logic [5:0] c$map_arg4_case_alt_223;
  logic [5:0] c$map_arg4_case_alt_224;
  logic [5:0] c$map_arg4_case_alt_225;
  logic [5:0] c$map_arg4_case_alt_226;
  logic [5:0] c$map_arg4_case_alt_227;
  logic [5:0] c$map_arg4_case_alt_228;
  logic [5:0] c$map_arg4_case_alt_229;
  logic [5:0] c$map_arg4_case_alt_230;
  logic [5:0] c$map_arg4_case_alt_231;
  logic [5:0] c$map_arg4_case_alt_232;
  logic [5:0] c$map_arg4_case_alt_233;
  logic [5:0] c$map_arg4_case_alt_234;
  logic [5:0] c$map_arg4_case_alt_235;
  logic [5:0] c$map_arg4_case_alt_236;
  logic [5:0] c$map_arg4_case_alt_237;
  logic [5:0] c$map_arg4_case_alt_238;
  logic [5:0] c$map_arg4_case_alt_239;
  logic [5:0] c$map_arg4_case_alt_240;
  logic [5:0] c$map_arg4_case_alt_241;
  logic [5:0] c$map_arg4_case_alt_242;
  logic [5:0] c$map_arg4_case_alt_243;
  logic [5:0] c$map_arg4_case_alt_244;
  logic [5:0] c$map_arg4_case_alt_245;
  logic [5:0] c$map_arg4_case_alt_246;
  logic [5:0] c$map_arg4_case_alt_247;
  logic [5:0] c$map_arg4_case_alt_248;
  logic [5:0] c$map_arg4_case_alt_249;
  logic [5:0] c$map_arg4_case_alt_250;
  logic [5:0] c$map_arg4_case_alt_251;
  logic [5:0] c$map_arg4_case_alt_252;
  logic [5:0] c$map_arg4_case_alt_253;
  logic [1599:0] c$map_arg4_app_arg_2;
  logic [1599:0] block;
  logic [7:0] ds1_0;
  logic signed [63:0] c$ds1_app_arg_0;
  logic [7:0] coeffIdx_0;
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] state;
  logic [4:0] roundIdx;
  logic [0:0] c$bv;
  logic [0:0] c$bv_0;
  logic [0:0] c$bv_1;
  logic [0:0] c$bv_2;
  logic [0:0] c$bv_3;
  logic [0:0] c$bv_4;
  Component_SamplePolyCBD512_types::array_of_6_logic_vector_1 c$vec;
  logic [7:0] c$i_92;
  Component_SamplePolyCBD512_types::array_of_6_logic_vector_1 c$vec_0;
  Component_SamplePolyCBD512_types::Tuple2_3 result;
  Component_SamplePolyCBD512_types::AXI4Stream DIGEST_TDATA_0;

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {2'b00,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt.Tuple2_2_sel0;
    end
  end
  // register end

  assign result = c$case_alt.Tuple2_2_sel1;

  always_comb begin
    case(c$ds_app_arg[1617:1616])
      2'b00 : c$case_alt = {{2'b01,5'd0,8'd0,result_3,{1'b0,2'bxx}}
                           ,{{12'b000000000000,1'b0,1'b0},1'b1}};
      2'b01 : c$case_alt = result_2;
      2'b10 : c$case_alt = result_0;
      default : c$case_alt = {{2'b11,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                             ,{{12'b000000000000,1'b0,1'b0},1'b0}};
    endcase
  end

  assign result_0 = whichBlock_0[2:2] ? {c$app_arg
                                        ,{{result_1,1'b1,isLast},1'b0}} : c$case_alt_0;

  assign c$case_alt_0 = (coeffIdx_0 >= 8'd181) ? {{2'b01,5'd0,coeffIdx_0,block,{1'b1,c$map_arg4_app_arg_2[1087 : 1086]}}
                                                 ,{{12'b000000000000,1'b0,1'b0}
                                                  ,1'b0}} : {c$app_arg_0
                                                            ,{{result_1,1'b1,isLast},1'b0}};

  assign c$app_arg = c$case_scrut ? {2'b11,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : c$case_alt_1;

  assign c$case_alt_1 = DIGEST_TREADY ? {2'b10,c$app_arg_1,block,whichBlock_0,5'bxxxxx} : c$ds_app_arg;

  assign c$app_arg_0 = c$case_scrut ? {2'b11,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : c$case_alt_2;

  assign c$case_alt_2 = DIGEST_TREADY ? {2'b10,c$app_arg_1,block,{1'b0,2'bxx},5'bxxxxx} : c$ds_app_arg;

  assign c$case_scrut = DIGEST_TREADY & isLast;

  assign isLast = coeffIdx_0 == 8'd255;

  assign c$app_arg_1 = coeffIdx_0 + 8'd1;

  assign result_1 = (a >= b) ? ({9'b000000000,(((a - b)))}) : (12'b110100000001 - ({9'b000000000,(((b - a)))}));

  assign c$bv = ((c$b_app_arg[5 : 5]));

  assign c$bv_0 = ((c$b_app_arg[4 : 4]));

  assign c$bv_1 = ((c$b_app_arg[3 : 3]));

  assign a = (({{(3-1) {1'b0}},((c$b_app_arg[5 : 5]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[4 : 4]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[3 : 3]))});

  assign c$bv_2 = ((c$b_app_arg[2 : 2]));

  assign c$bv_3 = ((c$b_app_arg[1 : 1]));

  assign c$bv_4 = ((c$b_app_arg[0 : 0]));

  assign b = (({{(3-1) {1'b0}},((c$b_app_arg[2 : 2]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[1 : 1]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[0 : 0]))});

  assign c$b_app_arg = (({Component_SamplePolyCBD512_types::array_of_6_logic_vector_1_to_lv(result_9)}));

  assign result_2 = (roundIdx == 5'd23) ? {{2'b10,coeffIdx,c$keccakF1600_out,whichBlock,5'bxxxxx}
                                          ,{{12'b000000000000,1'b0,1'b0}
                                           ,1'b0}} : {{2'b01,roundIdx + 5'd1,coeffIdx,c$keccakF1600_out,whichBlock}
                                                     ,{{12'b000000000000,1'b0,1'b0},1'b0}};

  assign whichBlock = c$ds_app_arg[2:0];

  assign coeffIdx = c$ds_app_arg[1610:1603];

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_2;
    result_3[64'sd1087] = (~ (c$app_arg_2[64'sd1087]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_4;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_3;
    result_4[64'sd264] = (~ (c$app_arg_3[64'sd264]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_4;
    result_5[64'sd265] = (~ (c$app_arg_4[64'sd265]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_5;
    result_6[64'sd266] = (~ (c$app_arg_5[64'sd266]));
  end
  // replaceBit end

  assign c$app_arg_5 = result_7;

  // replaceBit start
  always_comb begin
    result_7 = c$app_arg_6;
    result_7[64'sd267] = (~ (c$app_arg_6[64'sd267]));
  end
  // replaceBit end

  assign c$app_arg_6 = result_8;

  // replaceBit start
  always_comb begin
    result_8 = c$app_arg_7;
    result_8[64'sd268] = (~ (c$app_arg_7[64'sd268]));
  end
  // replaceBit end

  assign c$app_arg_7 = ({1336'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,MSG_33B});

  // map begin
  genvar n;
  generate
  for (n=0; n < $size(result_9); n = n + 1) begin : map
    logic map_in;
    assign map_in = c$map_arg4[n];
    logic [0:0] map_out;
    assign map_out = (map_in);


    assign result_9[n] = map_out;
  end
  endgenerate
  // map end

  assign c$map_arg4 = whichBlock_0[2:2] ? c$map_arg4_case_alt : c$map_arg4_case_alt_73;

  // reverse begin
  genvar n_0;
  generate
    for (n_0 = 0; n_0 < $size(c$map_arg4_app_arg); n_0 = n_0 + 1) begin : reverse
      assign c$map_arg4_case_alt[$high(c$map_arg4_app_arg) - n_0] = c$map_arg4_app_arg[n_0];
    end
  endgenerate
  // reverse end

  assign c$vec = (Component_SamplePolyCBD512_types::array_of_6_logic_vector_1_from_lv(c$map_arg4_app_arg_0));

  // map begin
  genvar n_1;
  generate
  for (n_1=0; n_1 < $size(c$map_arg4_app_arg); n_1 = n_1 + 1) begin : map_0
    logic [0:0] map_in_0;
    assign map_in_0 = c$vec[n_1];
    logic map_out_0;
    assign map_out_0 = map_in_0;


    assign c$map_arg4_app_arg[n_1] = map_out_0;
  end
  endgenerate
  // map end

  assign c$map_arg4_app_arg_0 = (coeffIdx_0 == 8'd181) ? ({(c$map_arg4_app_arg_2[3 : 0]),tail2}) : result_10;

  assign tail2 = whichBlock_0[1:0];

  assign whichBlock_0 = c$ds_app_arg[7:5];

  assign result_10 = (ds1 == 7'd0) ? (c$map_arg4_app_arg_2[9 : 4]) : c$map_arg4_case_alt_0;

  assign c$map_arg4_case_alt_0 = (ds1 == 7'd1) ? (c$map_arg4_app_arg_2[15 : 10]) : c$map_arg4_case_alt_1;

  assign c$map_arg4_case_alt_1 = (ds1 == 7'd2) ? (c$map_arg4_app_arg_2[21 : 16]) : c$map_arg4_case_alt_2;

  assign c$map_arg4_case_alt_2 = (ds1 == 7'd3) ? (c$map_arg4_app_arg_2[27 : 22]) : c$map_arg4_case_alt_3;

  assign c$map_arg4_case_alt_3 = (ds1 == 7'd4) ? (c$map_arg4_app_arg_2[33 : 28]) : c$map_arg4_case_alt_4;

  assign c$map_arg4_case_alt_4 = (ds1 == 7'd5) ? (c$map_arg4_app_arg_2[39 : 34]) : c$map_arg4_case_alt_5;

  assign c$map_arg4_case_alt_5 = (ds1 == 7'd6) ? (c$map_arg4_app_arg_2[45 : 40]) : c$map_arg4_case_alt_6;

  assign c$map_arg4_case_alt_6 = (ds1 == 7'd7) ? (c$map_arg4_app_arg_2[51 : 46]) : c$map_arg4_case_alt_7;

  assign c$map_arg4_case_alt_7 = (ds1 == 7'd8) ? (c$map_arg4_app_arg_2[57 : 52]) : c$map_arg4_case_alt_8;

  assign c$map_arg4_case_alt_8 = (ds1 == 7'd9) ? (c$map_arg4_app_arg_2[63 : 58]) : c$map_arg4_case_alt_9;

  assign c$map_arg4_case_alt_9 = (ds1 == 7'd10) ? (c$map_arg4_app_arg_2[69 : 64]) : c$map_arg4_case_alt_10;

  assign c$map_arg4_case_alt_10 = (ds1 == 7'd11) ? (c$map_arg4_app_arg_2[75 : 70]) : c$map_arg4_case_alt_11;

  assign c$map_arg4_case_alt_11 = (ds1 == 7'd12) ? (c$map_arg4_app_arg_2[81 : 76]) : c$map_arg4_case_alt_12;

  assign c$map_arg4_case_alt_12 = (ds1 == 7'd13) ? (c$map_arg4_app_arg_2[87 : 82]) : c$map_arg4_case_alt_13;

  assign c$map_arg4_case_alt_13 = (ds1 == 7'd14) ? (c$map_arg4_app_arg_2[93 : 88]) : c$map_arg4_case_alt_14;

  assign c$map_arg4_case_alt_14 = (ds1 == 7'd15) ? (c$map_arg4_app_arg_2[99 : 94]) : c$map_arg4_case_alt_15;

  assign c$map_arg4_case_alt_15 = (ds1 == 7'd16) ? (c$map_arg4_app_arg_2[105 : 100]) : c$map_arg4_case_alt_16;

  assign c$map_arg4_case_alt_16 = (ds1 == 7'd17) ? (c$map_arg4_app_arg_2[111 : 106]) : c$map_arg4_case_alt_17;

  assign c$map_arg4_case_alt_17 = (ds1 == 7'd18) ? (c$map_arg4_app_arg_2[117 : 112]) : c$map_arg4_case_alt_18;

  assign c$map_arg4_case_alt_18 = (ds1 == 7'd19) ? (c$map_arg4_app_arg_2[123 : 118]) : c$map_arg4_case_alt_19;

  assign c$map_arg4_case_alt_19 = (ds1 == 7'd20) ? (c$map_arg4_app_arg_2[129 : 124]) : c$map_arg4_case_alt_20;

  assign c$map_arg4_case_alt_20 = (ds1 == 7'd21) ? (c$map_arg4_app_arg_2[135 : 130]) : c$map_arg4_case_alt_21;

  assign c$map_arg4_case_alt_21 = (ds1 == 7'd22) ? (c$map_arg4_app_arg_2[141 : 136]) : c$map_arg4_case_alt_22;

  assign c$map_arg4_case_alt_22 = (ds1 == 7'd23) ? (c$map_arg4_app_arg_2[147 : 142]) : c$map_arg4_case_alt_23;

  assign c$map_arg4_case_alt_23 = (ds1 == 7'd24) ? (c$map_arg4_app_arg_2[153 : 148]) : c$map_arg4_case_alt_24;

  assign c$map_arg4_case_alt_24 = (ds1 == 7'd25) ? (c$map_arg4_app_arg_2[159 : 154]) : c$map_arg4_case_alt_25;

  assign c$map_arg4_case_alt_25 = (ds1 == 7'd26) ? (c$map_arg4_app_arg_2[165 : 160]) : c$map_arg4_case_alt_26;

  assign c$map_arg4_case_alt_26 = (ds1 == 7'd27) ? (c$map_arg4_app_arg_2[171 : 166]) : c$map_arg4_case_alt_27;

  assign c$map_arg4_case_alt_27 = (ds1 == 7'd28) ? (c$map_arg4_app_arg_2[177 : 172]) : c$map_arg4_case_alt_28;

  assign c$map_arg4_case_alt_28 = (ds1 == 7'd29) ? (c$map_arg4_app_arg_2[183 : 178]) : c$map_arg4_case_alt_29;

  assign c$map_arg4_case_alt_29 = (ds1 == 7'd30) ? (c$map_arg4_app_arg_2[189 : 184]) : c$map_arg4_case_alt_30;

  assign c$map_arg4_case_alt_30 = (ds1 == 7'd31) ? (c$map_arg4_app_arg_2[195 : 190]) : c$map_arg4_case_alt_31;

  assign c$map_arg4_case_alt_31 = (ds1 == 7'd32) ? (c$map_arg4_app_arg_2[201 : 196]) : c$map_arg4_case_alt_32;

  assign c$map_arg4_case_alt_32 = (ds1 == 7'd33) ? (c$map_arg4_app_arg_2[207 : 202]) : c$map_arg4_case_alt_33;

  assign c$map_arg4_case_alt_33 = (ds1 == 7'd34) ? (c$map_arg4_app_arg_2[213 : 208]) : c$map_arg4_case_alt_34;

  assign c$map_arg4_case_alt_34 = (ds1 == 7'd35) ? (c$map_arg4_app_arg_2[219 : 214]) : c$map_arg4_case_alt_35;

  assign c$map_arg4_case_alt_35 = (ds1 == 7'd36) ? (c$map_arg4_app_arg_2[225 : 220]) : c$map_arg4_case_alt_36;

  assign c$map_arg4_case_alt_36 = (ds1 == 7'd37) ? (c$map_arg4_app_arg_2[231 : 226]) : c$map_arg4_case_alt_37;

  assign c$map_arg4_case_alt_37 = (ds1 == 7'd38) ? (c$map_arg4_app_arg_2[237 : 232]) : c$map_arg4_case_alt_38;

  assign c$map_arg4_case_alt_38 = (ds1 == 7'd39) ? (c$map_arg4_app_arg_2[243 : 238]) : c$map_arg4_case_alt_39;

  assign c$map_arg4_case_alt_39 = (ds1 == 7'd40) ? (c$map_arg4_app_arg_2[249 : 244]) : c$map_arg4_case_alt_40;

  assign c$map_arg4_case_alt_40 = (ds1 == 7'd41) ? (c$map_arg4_app_arg_2[255 : 250]) : c$map_arg4_case_alt_41;

  assign c$map_arg4_case_alt_41 = (ds1 == 7'd42) ? (c$map_arg4_app_arg_2[261 : 256]) : c$map_arg4_case_alt_42;

  assign c$map_arg4_case_alt_42 = (ds1 == 7'd43) ? (c$map_arg4_app_arg_2[267 : 262]) : c$map_arg4_case_alt_43;

  assign c$map_arg4_case_alt_43 = (ds1 == 7'd44) ? (c$map_arg4_app_arg_2[273 : 268]) : c$map_arg4_case_alt_44;

  assign c$map_arg4_case_alt_44 = (ds1 == 7'd45) ? (c$map_arg4_app_arg_2[279 : 274]) : c$map_arg4_case_alt_45;

  assign c$map_arg4_case_alt_45 = (ds1 == 7'd46) ? (c$map_arg4_app_arg_2[285 : 280]) : c$map_arg4_case_alt_46;

  assign c$map_arg4_case_alt_46 = (ds1 == 7'd47) ? (c$map_arg4_app_arg_2[291 : 286]) : c$map_arg4_case_alt_47;

  assign c$map_arg4_case_alt_47 = (ds1 == 7'd48) ? (c$map_arg4_app_arg_2[297 : 292]) : c$map_arg4_case_alt_48;

  assign c$map_arg4_case_alt_48 = (ds1 == 7'd49) ? (c$map_arg4_app_arg_2[303 : 298]) : c$map_arg4_case_alt_49;

  assign c$map_arg4_case_alt_49 = (ds1 == 7'd50) ? (c$map_arg4_app_arg_2[309 : 304]) : c$map_arg4_case_alt_50;

  assign c$map_arg4_case_alt_50 = (ds1 == 7'd51) ? (c$map_arg4_app_arg_2[315 : 310]) : c$map_arg4_case_alt_51;

  assign c$map_arg4_case_alt_51 = (ds1 == 7'd52) ? (c$map_arg4_app_arg_2[321 : 316]) : c$map_arg4_case_alt_52;

  assign c$map_arg4_case_alt_52 = (ds1 == 7'd53) ? (c$map_arg4_app_arg_2[327 : 322]) : c$map_arg4_case_alt_53;

  assign c$map_arg4_case_alt_53 = (ds1 == 7'd54) ? (c$map_arg4_app_arg_2[333 : 328]) : c$map_arg4_case_alt_54;

  assign c$map_arg4_case_alt_54 = (ds1 == 7'd55) ? (c$map_arg4_app_arg_2[339 : 334]) : c$map_arg4_case_alt_55;

  assign c$map_arg4_case_alt_55 = (ds1 == 7'd56) ? (c$map_arg4_app_arg_2[345 : 340]) : c$map_arg4_case_alt_56;

  assign c$map_arg4_case_alt_56 = (ds1 == 7'd57) ? (c$map_arg4_app_arg_2[351 : 346]) : c$map_arg4_case_alt_57;

  assign c$map_arg4_case_alt_57 = (ds1 == 7'd58) ? (c$map_arg4_app_arg_2[357 : 352]) : c$map_arg4_case_alt_58;

  assign c$map_arg4_case_alt_58 = (ds1 == 7'd59) ? (c$map_arg4_app_arg_2[363 : 358]) : c$map_arg4_case_alt_59;

  assign c$map_arg4_case_alt_59 = (ds1 == 7'd60) ? (c$map_arg4_app_arg_2[369 : 364]) : c$map_arg4_case_alt_60;

  assign c$map_arg4_case_alt_60 = (ds1 == 7'd61) ? (c$map_arg4_app_arg_2[375 : 370]) : c$map_arg4_case_alt_61;

  assign c$map_arg4_case_alt_61 = (ds1 == 7'd62) ? (c$map_arg4_app_arg_2[381 : 376]) : c$map_arg4_case_alt_62;

  assign c$map_arg4_case_alt_62 = (ds1 == 7'd63) ? (c$map_arg4_app_arg_2[387 : 382]) : c$map_arg4_case_alt_63;

  assign c$map_arg4_case_alt_63 = (ds1 == 7'd64) ? (c$map_arg4_app_arg_2[393 : 388]) : c$map_arg4_case_alt_64;

  assign c$map_arg4_case_alt_64 = (ds1 == 7'd65) ? (c$map_arg4_app_arg_2[399 : 394]) : c$map_arg4_case_alt_65;

  assign c$map_arg4_case_alt_65 = (ds1 == 7'd66) ? (c$map_arg4_app_arg_2[405 : 400]) : c$map_arg4_case_alt_66;

  assign c$map_arg4_case_alt_66 = (ds1 == 7'd67) ? (c$map_arg4_app_arg_2[411 : 406]) : c$map_arg4_case_alt_67;

  assign c$map_arg4_case_alt_67 = (ds1 == 7'd68) ? (c$map_arg4_app_arg_2[417 : 412]) : c$map_arg4_case_alt_68;

  assign c$map_arg4_case_alt_68 = (ds1 == 7'd69) ? (c$map_arg4_app_arg_2[423 : 418]) : c$map_arg4_case_alt_69;

  assign c$map_arg4_case_alt_69 = (ds1 == 7'd70) ? (c$map_arg4_app_arg_2[429 : 424]) : c$map_arg4_case_alt_70;

  assign c$map_arg4_case_alt_70 = (ds1 == 7'd71) ? (c$map_arg4_app_arg_2[435 : 430]) : c$map_arg4_case_alt_71;

  assign c$map_arg4_case_alt_71 = (ds1 == 7'd72) ? (c$map_arg4_app_arg_2[441 : 436]) : c$map_arg4_case_alt_72;

  assign c$map_arg4_case_alt_72 = (ds1 == 7'd73) ? (c$map_arg4_app_arg_2[447 : 442]) : ({6 {1'bx}});

  assign ds1 = $unsigned(c$ds1_app_arg[0+:7]);

  assign c$i_92 = (coeffIdx_0 - 8'd182);

  assign c$ds1_app_arg = $unsigned({{(64-8) {1'b0}},c$i_92});

  // reverse begin
  genvar n_2;
  generate
    for (n_2 = 0; n_2 < $size(c$map_arg4_app_arg_1); n_2 = n_2 + 1) begin : reverse_0
      assign c$map_arg4_case_alt_73[$high(c$map_arg4_app_arg_1) - n_2] = c$map_arg4_app_arg_1[n_2];
    end
  endgenerate
  // reverse end

  assign c$vec_0 = (Component_SamplePolyCBD512_types::array_of_6_logic_vector_1_from_lv(result_11));

  // map begin
  genvar n_3;
  generate
  for (n_3=0; n_3 < $size(c$map_arg4_app_arg_1); n_3 = n_3 + 1) begin : map_1
    logic [0:0] map_in_1;
    assign map_in_1 = c$vec_0[n_3];
    logic map_out_1;
    assign map_out_1 = map_in_1;


    assign c$map_arg4_app_arg_1[n_3] = map_out_1;
  end
  endgenerate
  // map end

  assign result_11 = (ds1_0 == 8'd0) ? (c$map_arg4_app_arg_2[5 : 0]) : c$map_arg4_case_alt_74;

  assign c$map_arg4_case_alt_74 = (ds1_0 == 8'd1) ? (c$map_arg4_app_arg_2[11 : 6]) : c$map_arg4_case_alt_75;

  assign c$map_arg4_case_alt_75 = (ds1_0 == 8'd2) ? (c$map_arg4_app_arg_2[17 : 12]) : c$map_arg4_case_alt_76;

  assign c$map_arg4_case_alt_76 = (ds1_0 == 8'd3) ? (c$map_arg4_app_arg_2[23 : 18]) : c$map_arg4_case_alt_77;

  assign c$map_arg4_case_alt_77 = (ds1_0 == 8'd4) ? (c$map_arg4_app_arg_2[29 : 24]) : c$map_arg4_case_alt_78;

  assign c$map_arg4_case_alt_78 = (ds1_0 == 8'd5) ? (c$map_arg4_app_arg_2[35 : 30]) : c$map_arg4_case_alt_79;

  assign c$map_arg4_case_alt_79 = (ds1_0 == 8'd6) ? (c$map_arg4_app_arg_2[41 : 36]) : c$map_arg4_case_alt_80;

  assign c$map_arg4_case_alt_80 = (ds1_0 == 8'd7) ? (c$map_arg4_app_arg_2[47 : 42]) : c$map_arg4_case_alt_81;

  assign c$map_arg4_case_alt_81 = (ds1_0 == 8'd8) ? (c$map_arg4_app_arg_2[53 : 48]) : c$map_arg4_case_alt_82;

  assign c$map_arg4_case_alt_82 = (ds1_0 == 8'd9) ? (c$map_arg4_app_arg_2[59 : 54]) : c$map_arg4_case_alt_83;

  assign c$map_arg4_case_alt_83 = (ds1_0 == 8'd10) ? (c$map_arg4_app_arg_2[65 : 60]) : c$map_arg4_case_alt_84;

  assign c$map_arg4_case_alt_84 = (ds1_0 == 8'd11) ? (c$map_arg4_app_arg_2[71 : 66]) : c$map_arg4_case_alt_85;

  assign c$map_arg4_case_alt_85 = (ds1_0 == 8'd12) ? (c$map_arg4_app_arg_2[77 : 72]) : c$map_arg4_case_alt_86;

  assign c$map_arg4_case_alt_86 = (ds1_0 == 8'd13) ? (c$map_arg4_app_arg_2[83 : 78]) : c$map_arg4_case_alt_87;

  assign c$map_arg4_case_alt_87 = (ds1_0 == 8'd14) ? (c$map_arg4_app_arg_2[89 : 84]) : c$map_arg4_case_alt_88;

  assign c$map_arg4_case_alt_88 = (ds1_0 == 8'd15) ? (c$map_arg4_app_arg_2[95 : 90]) : c$map_arg4_case_alt_89;

  assign c$map_arg4_case_alt_89 = (ds1_0 == 8'd16) ? (c$map_arg4_app_arg_2[101 : 96]) : c$map_arg4_case_alt_90;

  assign c$map_arg4_case_alt_90 = (ds1_0 == 8'd17) ? (c$map_arg4_app_arg_2[107 : 102]) : c$map_arg4_case_alt_91;

  assign c$map_arg4_case_alt_91 = (ds1_0 == 8'd18) ? (c$map_arg4_app_arg_2[113 : 108]) : c$map_arg4_case_alt_92;

  assign c$map_arg4_case_alt_92 = (ds1_0 == 8'd19) ? (c$map_arg4_app_arg_2[119 : 114]) : c$map_arg4_case_alt_93;

  assign c$map_arg4_case_alt_93 = (ds1_0 == 8'd20) ? (c$map_arg4_app_arg_2[125 : 120]) : c$map_arg4_case_alt_94;

  assign c$map_arg4_case_alt_94 = (ds1_0 == 8'd21) ? (c$map_arg4_app_arg_2[131 : 126]) : c$map_arg4_case_alt_95;

  assign c$map_arg4_case_alt_95 = (ds1_0 == 8'd22) ? (c$map_arg4_app_arg_2[137 : 132]) : c$map_arg4_case_alt_96;

  assign c$map_arg4_case_alt_96 = (ds1_0 == 8'd23) ? (c$map_arg4_app_arg_2[143 : 138]) : c$map_arg4_case_alt_97;

  assign c$map_arg4_case_alt_97 = (ds1_0 == 8'd24) ? (c$map_arg4_app_arg_2[149 : 144]) : c$map_arg4_case_alt_98;

  assign c$map_arg4_case_alt_98 = (ds1_0 == 8'd25) ? (c$map_arg4_app_arg_2[155 : 150]) : c$map_arg4_case_alt_99;

  assign c$map_arg4_case_alt_99 = (ds1_0 == 8'd26) ? (c$map_arg4_app_arg_2[161 : 156]) : c$map_arg4_case_alt_100;

  assign c$map_arg4_case_alt_100 = (ds1_0 == 8'd27) ? (c$map_arg4_app_arg_2[167 : 162]) : c$map_arg4_case_alt_101;

  assign c$map_arg4_case_alt_101 = (ds1_0 == 8'd28) ? (c$map_arg4_app_arg_2[173 : 168]) : c$map_arg4_case_alt_102;

  assign c$map_arg4_case_alt_102 = (ds1_0 == 8'd29) ? (c$map_arg4_app_arg_2[179 : 174]) : c$map_arg4_case_alt_103;

  assign c$map_arg4_case_alt_103 = (ds1_0 == 8'd30) ? (c$map_arg4_app_arg_2[185 : 180]) : c$map_arg4_case_alt_104;

  assign c$map_arg4_case_alt_104 = (ds1_0 == 8'd31) ? (c$map_arg4_app_arg_2[191 : 186]) : c$map_arg4_case_alt_105;

  assign c$map_arg4_case_alt_105 = (ds1_0 == 8'd32) ? (c$map_arg4_app_arg_2[197 : 192]) : c$map_arg4_case_alt_106;

  assign c$map_arg4_case_alt_106 = (ds1_0 == 8'd33) ? (c$map_arg4_app_arg_2[203 : 198]) : c$map_arg4_case_alt_107;

  assign c$map_arg4_case_alt_107 = (ds1_0 == 8'd34) ? (c$map_arg4_app_arg_2[209 : 204]) : c$map_arg4_case_alt_108;

  assign c$map_arg4_case_alt_108 = (ds1_0 == 8'd35) ? (c$map_arg4_app_arg_2[215 : 210]) : c$map_arg4_case_alt_109;

  assign c$map_arg4_case_alt_109 = (ds1_0 == 8'd36) ? (c$map_arg4_app_arg_2[221 : 216]) : c$map_arg4_case_alt_110;

  assign c$map_arg4_case_alt_110 = (ds1_0 == 8'd37) ? (c$map_arg4_app_arg_2[227 : 222]) : c$map_arg4_case_alt_111;

  assign c$map_arg4_case_alt_111 = (ds1_0 == 8'd38) ? (c$map_arg4_app_arg_2[233 : 228]) : c$map_arg4_case_alt_112;

  assign c$map_arg4_case_alt_112 = (ds1_0 == 8'd39) ? (c$map_arg4_app_arg_2[239 : 234]) : c$map_arg4_case_alt_113;

  assign c$map_arg4_case_alt_113 = (ds1_0 == 8'd40) ? (c$map_arg4_app_arg_2[245 : 240]) : c$map_arg4_case_alt_114;

  assign c$map_arg4_case_alt_114 = (ds1_0 == 8'd41) ? (c$map_arg4_app_arg_2[251 : 246]) : c$map_arg4_case_alt_115;

  assign c$map_arg4_case_alt_115 = (ds1_0 == 8'd42) ? (c$map_arg4_app_arg_2[257 : 252]) : c$map_arg4_case_alt_116;

  assign c$map_arg4_case_alt_116 = (ds1_0 == 8'd43) ? (c$map_arg4_app_arg_2[263 : 258]) : c$map_arg4_case_alt_117;

  assign c$map_arg4_case_alt_117 = (ds1_0 == 8'd44) ? (c$map_arg4_app_arg_2[269 : 264]) : c$map_arg4_case_alt_118;

  assign c$map_arg4_case_alt_118 = (ds1_0 == 8'd45) ? (c$map_arg4_app_arg_2[275 : 270]) : c$map_arg4_case_alt_119;

  assign c$map_arg4_case_alt_119 = (ds1_0 == 8'd46) ? (c$map_arg4_app_arg_2[281 : 276]) : c$map_arg4_case_alt_120;

  assign c$map_arg4_case_alt_120 = (ds1_0 == 8'd47) ? (c$map_arg4_app_arg_2[287 : 282]) : c$map_arg4_case_alt_121;

  assign c$map_arg4_case_alt_121 = (ds1_0 == 8'd48) ? (c$map_arg4_app_arg_2[293 : 288]) : c$map_arg4_case_alt_122;

  assign c$map_arg4_case_alt_122 = (ds1_0 == 8'd49) ? (c$map_arg4_app_arg_2[299 : 294]) : c$map_arg4_case_alt_123;

  assign c$map_arg4_case_alt_123 = (ds1_0 == 8'd50) ? (c$map_arg4_app_arg_2[305 : 300]) : c$map_arg4_case_alt_124;

  assign c$map_arg4_case_alt_124 = (ds1_0 == 8'd51) ? (c$map_arg4_app_arg_2[311 : 306]) : c$map_arg4_case_alt_125;

  assign c$map_arg4_case_alt_125 = (ds1_0 == 8'd52) ? (c$map_arg4_app_arg_2[317 : 312]) : c$map_arg4_case_alt_126;

  assign c$map_arg4_case_alt_126 = (ds1_0 == 8'd53) ? (c$map_arg4_app_arg_2[323 : 318]) : c$map_arg4_case_alt_127;

  assign c$map_arg4_case_alt_127 = (ds1_0 == 8'd54) ? (c$map_arg4_app_arg_2[329 : 324]) : c$map_arg4_case_alt_128;

  assign c$map_arg4_case_alt_128 = (ds1_0 == 8'd55) ? (c$map_arg4_app_arg_2[335 : 330]) : c$map_arg4_case_alt_129;

  assign c$map_arg4_case_alt_129 = (ds1_0 == 8'd56) ? (c$map_arg4_app_arg_2[341 : 336]) : c$map_arg4_case_alt_130;

  assign c$map_arg4_case_alt_130 = (ds1_0 == 8'd57) ? (c$map_arg4_app_arg_2[347 : 342]) : c$map_arg4_case_alt_131;

  assign c$map_arg4_case_alt_131 = (ds1_0 == 8'd58) ? (c$map_arg4_app_arg_2[353 : 348]) : c$map_arg4_case_alt_132;

  assign c$map_arg4_case_alt_132 = (ds1_0 == 8'd59) ? (c$map_arg4_app_arg_2[359 : 354]) : c$map_arg4_case_alt_133;

  assign c$map_arg4_case_alt_133 = (ds1_0 == 8'd60) ? (c$map_arg4_app_arg_2[365 : 360]) : c$map_arg4_case_alt_134;

  assign c$map_arg4_case_alt_134 = (ds1_0 == 8'd61) ? (c$map_arg4_app_arg_2[371 : 366]) : c$map_arg4_case_alt_135;

  assign c$map_arg4_case_alt_135 = (ds1_0 == 8'd62) ? (c$map_arg4_app_arg_2[377 : 372]) : c$map_arg4_case_alt_136;

  assign c$map_arg4_case_alt_136 = (ds1_0 == 8'd63) ? (c$map_arg4_app_arg_2[383 : 378]) : c$map_arg4_case_alt_137;

  assign c$map_arg4_case_alt_137 = (ds1_0 == 8'd64) ? (c$map_arg4_app_arg_2[389 : 384]) : c$map_arg4_case_alt_138;

  assign c$map_arg4_case_alt_138 = (ds1_0 == 8'd65) ? (c$map_arg4_app_arg_2[395 : 390]) : c$map_arg4_case_alt_139;

  assign c$map_arg4_case_alt_139 = (ds1_0 == 8'd66) ? (c$map_arg4_app_arg_2[401 : 396]) : c$map_arg4_case_alt_140;

  assign c$map_arg4_case_alt_140 = (ds1_0 == 8'd67) ? (c$map_arg4_app_arg_2[407 : 402]) : c$map_arg4_case_alt_141;

  assign c$map_arg4_case_alt_141 = (ds1_0 == 8'd68) ? (c$map_arg4_app_arg_2[413 : 408]) : c$map_arg4_case_alt_142;

  assign c$map_arg4_case_alt_142 = (ds1_0 == 8'd69) ? (c$map_arg4_app_arg_2[419 : 414]) : c$map_arg4_case_alt_143;

  assign c$map_arg4_case_alt_143 = (ds1_0 == 8'd70) ? (c$map_arg4_app_arg_2[425 : 420]) : c$map_arg4_case_alt_144;

  assign c$map_arg4_case_alt_144 = (ds1_0 == 8'd71) ? (c$map_arg4_app_arg_2[431 : 426]) : c$map_arg4_case_alt_145;

  assign c$map_arg4_case_alt_145 = (ds1_0 == 8'd72) ? (c$map_arg4_app_arg_2[437 : 432]) : c$map_arg4_case_alt_146;

  assign c$map_arg4_case_alt_146 = (ds1_0 == 8'd73) ? (c$map_arg4_app_arg_2[443 : 438]) : c$map_arg4_case_alt_147;

  assign c$map_arg4_case_alt_147 = (ds1_0 == 8'd74) ? (c$map_arg4_app_arg_2[449 : 444]) : c$map_arg4_case_alt_148;

  assign c$map_arg4_case_alt_148 = (ds1_0 == 8'd75) ? (c$map_arg4_app_arg_2[455 : 450]) : c$map_arg4_case_alt_149;

  assign c$map_arg4_case_alt_149 = (ds1_0 == 8'd76) ? (c$map_arg4_app_arg_2[461 : 456]) : c$map_arg4_case_alt_150;

  assign c$map_arg4_case_alt_150 = (ds1_0 == 8'd77) ? (c$map_arg4_app_arg_2[467 : 462]) : c$map_arg4_case_alt_151;

  assign c$map_arg4_case_alt_151 = (ds1_0 == 8'd78) ? (c$map_arg4_app_arg_2[473 : 468]) : c$map_arg4_case_alt_152;

  assign c$map_arg4_case_alt_152 = (ds1_0 == 8'd79) ? (c$map_arg4_app_arg_2[479 : 474]) : c$map_arg4_case_alt_153;

  assign c$map_arg4_case_alt_153 = (ds1_0 == 8'd80) ? (c$map_arg4_app_arg_2[485 : 480]) : c$map_arg4_case_alt_154;

  assign c$map_arg4_case_alt_154 = (ds1_0 == 8'd81) ? (c$map_arg4_app_arg_2[491 : 486]) : c$map_arg4_case_alt_155;

  assign c$map_arg4_case_alt_155 = (ds1_0 == 8'd82) ? (c$map_arg4_app_arg_2[497 : 492]) : c$map_arg4_case_alt_156;

  assign c$map_arg4_case_alt_156 = (ds1_0 == 8'd83) ? (c$map_arg4_app_arg_2[503 : 498]) : c$map_arg4_case_alt_157;

  assign c$map_arg4_case_alt_157 = (ds1_0 == 8'd84) ? (c$map_arg4_app_arg_2[509 : 504]) : c$map_arg4_case_alt_158;

  assign c$map_arg4_case_alt_158 = (ds1_0 == 8'd85) ? (c$map_arg4_app_arg_2[515 : 510]) : c$map_arg4_case_alt_159;

  assign c$map_arg4_case_alt_159 = (ds1_0 == 8'd86) ? (c$map_arg4_app_arg_2[521 : 516]) : c$map_arg4_case_alt_160;

  assign c$map_arg4_case_alt_160 = (ds1_0 == 8'd87) ? (c$map_arg4_app_arg_2[527 : 522]) : c$map_arg4_case_alt_161;

  assign c$map_arg4_case_alt_161 = (ds1_0 == 8'd88) ? (c$map_arg4_app_arg_2[533 : 528]) : c$map_arg4_case_alt_162;

  assign c$map_arg4_case_alt_162 = (ds1_0 == 8'd89) ? (c$map_arg4_app_arg_2[539 : 534]) : c$map_arg4_case_alt_163;

  assign c$map_arg4_case_alt_163 = (ds1_0 == 8'd90) ? (c$map_arg4_app_arg_2[545 : 540]) : c$map_arg4_case_alt_164;

  assign c$map_arg4_case_alt_164 = (ds1_0 == 8'd91) ? (c$map_arg4_app_arg_2[551 : 546]) : c$map_arg4_case_alt_165;

  assign c$map_arg4_case_alt_165 = (ds1_0 == 8'd92) ? (c$map_arg4_app_arg_2[557 : 552]) : c$map_arg4_case_alt_166;

  assign c$map_arg4_case_alt_166 = (ds1_0 == 8'd93) ? (c$map_arg4_app_arg_2[563 : 558]) : c$map_arg4_case_alt_167;

  assign c$map_arg4_case_alt_167 = (ds1_0 == 8'd94) ? (c$map_arg4_app_arg_2[569 : 564]) : c$map_arg4_case_alt_168;

  assign c$map_arg4_case_alt_168 = (ds1_0 == 8'd95) ? (c$map_arg4_app_arg_2[575 : 570]) : c$map_arg4_case_alt_169;

  assign c$map_arg4_case_alt_169 = (ds1_0 == 8'd96) ? (c$map_arg4_app_arg_2[581 : 576]) : c$map_arg4_case_alt_170;

  assign c$map_arg4_case_alt_170 = (ds1_0 == 8'd97) ? (c$map_arg4_app_arg_2[587 : 582]) : c$map_arg4_case_alt_171;

  assign c$map_arg4_case_alt_171 = (ds1_0 == 8'd98) ? (c$map_arg4_app_arg_2[593 : 588]) : c$map_arg4_case_alt_172;

  assign c$map_arg4_case_alt_172 = (ds1_0 == 8'd99) ? (c$map_arg4_app_arg_2[599 : 594]) : c$map_arg4_case_alt_173;

  assign c$map_arg4_case_alt_173 = (ds1_0 == 8'd100) ? (c$map_arg4_app_arg_2[605 : 600]) : c$map_arg4_case_alt_174;

  assign c$map_arg4_case_alt_174 = (ds1_0 == 8'd101) ? (c$map_arg4_app_arg_2[611 : 606]) : c$map_arg4_case_alt_175;

  assign c$map_arg4_case_alt_175 = (ds1_0 == 8'd102) ? (c$map_arg4_app_arg_2[617 : 612]) : c$map_arg4_case_alt_176;

  assign c$map_arg4_case_alt_176 = (ds1_0 == 8'd103) ? (c$map_arg4_app_arg_2[623 : 618]) : c$map_arg4_case_alt_177;

  assign c$map_arg4_case_alt_177 = (ds1_0 == 8'd104) ? (c$map_arg4_app_arg_2[629 : 624]) : c$map_arg4_case_alt_178;

  assign c$map_arg4_case_alt_178 = (ds1_0 == 8'd105) ? (c$map_arg4_app_arg_2[635 : 630]) : c$map_arg4_case_alt_179;

  assign c$map_arg4_case_alt_179 = (ds1_0 == 8'd106) ? (c$map_arg4_app_arg_2[641 : 636]) : c$map_arg4_case_alt_180;

  assign c$map_arg4_case_alt_180 = (ds1_0 == 8'd107) ? (c$map_arg4_app_arg_2[647 : 642]) : c$map_arg4_case_alt_181;

  assign c$map_arg4_case_alt_181 = (ds1_0 == 8'd108) ? (c$map_arg4_app_arg_2[653 : 648]) : c$map_arg4_case_alt_182;

  assign c$map_arg4_case_alt_182 = (ds1_0 == 8'd109) ? (c$map_arg4_app_arg_2[659 : 654]) : c$map_arg4_case_alt_183;

  assign c$map_arg4_case_alt_183 = (ds1_0 == 8'd110) ? (c$map_arg4_app_arg_2[665 : 660]) : c$map_arg4_case_alt_184;

  assign c$map_arg4_case_alt_184 = (ds1_0 == 8'd111) ? (c$map_arg4_app_arg_2[671 : 666]) : c$map_arg4_case_alt_185;

  assign c$map_arg4_case_alt_185 = (ds1_0 == 8'd112) ? (c$map_arg4_app_arg_2[677 : 672]) : c$map_arg4_case_alt_186;

  assign c$map_arg4_case_alt_186 = (ds1_0 == 8'd113) ? (c$map_arg4_app_arg_2[683 : 678]) : c$map_arg4_case_alt_187;

  assign c$map_arg4_case_alt_187 = (ds1_0 == 8'd114) ? (c$map_arg4_app_arg_2[689 : 684]) : c$map_arg4_case_alt_188;

  assign c$map_arg4_case_alt_188 = (ds1_0 == 8'd115) ? (c$map_arg4_app_arg_2[695 : 690]) : c$map_arg4_case_alt_189;

  assign c$map_arg4_case_alt_189 = (ds1_0 == 8'd116) ? (c$map_arg4_app_arg_2[701 : 696]) : c$map_arg4_case_alt_190;

  assign c$map_arg4_case_alt_190 = (ds1_0 == 8'd117) ? (c$map_arg4_app_arg_2[707 : 702]) : c$map_arg4_case_alt_191;

  assign c$map_arg4_case_alt_191 = (ds1_0 == 8'd118) ? (c$map_arg4_app_arg_2[713 : 708]) : c$map_arg4_case_alt_192;

  assign c$map_arg4_case_alt_192 = (ds1_0 == 8'd119) ? (c$map_arg4_app_arg_2[719 : 714]) : c$map_arg4_case_alt_193;

  assign c$map_arg4_case_alt_193 = (ds1_0 == 8'd120) ? (c$map_arg4_app_arg_2[725 : 720]) : c$map_arg4_case_alt_194;

  assign c$map_arg4_case_alt_194 = (ds1_0 == 8'd121) ? (c$map_arg4_app_arg_2[731 : 726]) : c$map_arg4_case_alt_195;

  assign c$map_arg4_case_alt_195 = (ds1_0 == 8'd122) ? (c$map_arg4_app_arg_2[737 : 732]) : c$map_arg4_case_alt_196;

  assign c$map_arg4_case_alt_196 = (ds1_0 == 8'd123) ? (c$map_arg4_app_arg_2[743 : 738]) : c$map_arg4_case_alt_197;

  assign c$map_arg4_case_alt_197 = (ds1_0 == 8'd124) ? (c$map_arg4_app_arg_2[749 : 744]) : c$map_arg4_case_alt_198;

  assign c$map_arg4_case_alt_198 = (ds1_0 == 8'd125) ? (c$map_arg4_app_arg_2[755 : 750]) : c$map_arg4_case_alt_199;

  assign c$map_arg4_case_alt_199 = (ds1_0 == 8'd126) ? (c$map_arg4_app_arg_2[761 : 756]) : c$map_arg4_case_alt_200;

  assign c$map_arg4_case_alt_200 = (ds1_0 == 8'd127) ? (c$map_arg4_app_arg_2[767 : 762]) : c$map_arg4_case_alt_201;

  assign c$map_arg4_case_alt_201 = (ds1_0 == 8'd128) ? (c$map_arg4_app_arg_2[773 : 768]) : c$map_arg4_case_alt_202;

  assign c$map_arg4_case_alt_202 = (ds1_0 == 8'd129) ? (c$map_arg4_app_arg_2[779 : 774]) : c$map_arg4_case_alt_203;

  assign c$map_arg4_case_alt_203 = (ds1_0 == 8'd130) ? (c$map_arg4_app_arg_2[785 : 780]) : c$map_arg4_case_alt_204;

  assign c$map_arg4_case_alt_204 = (ds1_0 == 8'd131) ? (c$map_arg4_app_arg_2[791 : 786]) : c$map_arg4_case_alt_205;

  assign c$map_arg4_case_alt_205 = (ds1_0 == 8'd132) ? (c$map_arg4_app_arg_2[797 : 792]) : c$map_arg4_case_alt_206;

  assign c$map_arg4_case_alt_206 = (ds1_0 == 8'd133) ? (c$map_arg4_app_arg_2[803 : 798]) : c$map_arg4_case_alt_207;

  assign c$map_arg4_case_alt_207 = (ds1_0 == 8'd134) ? (c$map_arg4_app_arg_2[809 : 804]) : c$map_arg4_case_alt_208;

  assign c$map_arg4_case_alt_208 = (ds1_0 == 8'd135) ? (c$map_arg4_app_arg_2[815 : 810]) : c$map_arg4_case_alt_209;

  assign c$map_arg4_case_alt_209 = (ds1_0 == 8'd136) ? (c$map_arg4_app_arg_2[821 : 816]) : c$map_arg4_case_alt_210;

  assign c$map_arg4_case_alt_210 = (ds1_0 == 8'd137) ? (c$map_arg4_app_arg_2[827 : 822]) : c$map_arg4_case_alt_211;

  assign c$map_arg4_case_alt_211 = (ds1_0 == 8'd138) ? (c$map_arg4_app_arg_2[833 : 828]) : c$map_arg4_case_alt_212;

  assign c$map_arg4_case_alt_212 = (ds1_0 == 8'd139) ? (c$map_arg4_app_arg_2[839 : 834]) : c$map_arg4_case_alt_213;

  assign c$map_arg4_case_alt_213 = (ds1_0 == 8'd140) ? (c$map_arg4_app_arg_2[845 : 840]) : c$map_arg4_case_alt_214;

  assign c$map_arg4_case_alt_214 = (ds1_0 == 8'd141) ? (c$map_arg4_app_arg_2[851 : 846]) : c$map_arg4_case_alt_215;

  assign c$map_arg4_case_alt_215 = (ds1_0 == 8'd142) ? (c$map_arg4_app_arg_2[857 : 852]) : c$map_arg4_case_alt_216;

  assign c$map_arg4_case_alt_216 = (ds1_0 == 8'd143) ? (c$map_arg4_app_arg_2[863 : 858]) : c$map_arg4_case_alt_217;

  assign c$map_arg4_case_alt_217 = (ds1_0 == 8'd144) ? (c$map_arg4_app_arg_2[869 : 864]) : c$map_arg4_case_alt_218;

  assign c$map_arg4_case_alt_218 = (ds1_0 == 8'd145) ? (c$map_arg4_app_arg_2[875 : 870]) : c$map_arg4_case_alt_219;

  assign c$map_arg4_case_alt_219 = (ds1_0 == 8'd146) ? (c$map_arg4_app_arg_2[881 : 876]) : c$map_arg4_case_alt_220;

  assign c$map_arg4_case_alt_220 = (ds1_0 == 8'd147) ? (c$map_arg4_app_arg_2[887 : 882]) : c$map_arg4_case_alt_221;

  assign c$map_arg4_case_alt_221 = (ds1_0 == 8'd148) ? (c$map_arg4_app_arg_2[893 : 888]) : c$map_arg4_case_alt_222;

  assign c$map_arg4_case_alt_222 = (ds1_0 == 8'd149) ? (c$map_arg4_app_arg_2[899 : 894]) : c$map_arg4_case_alt_223;

  assign c$map_arg4_case_alt_223 = (ds1_0 == 8'd150) ? (c$map_arg4_app_arg_2[905 : 900]) : c$map_arg4_case_alt_224;

  assign c$map_arg4_case_alt_224 = (ds1_0 == 8'd151) ? (c$map_arg4_app_arg_2[911 : 906]) : c$map_arg4_case_alt_225;

  assign c$map_arg4_case_alt_225 = (ds1_0 == 8'd152) ? (c$map_arg4_app_arg_2[917 : 912]) : c$map_arg4_case_alt_226;

  assign c$map_arg4_case_alt_226 = (ds1_0 == 8'd153) ? (c$map_arg4_app_arg_2[923 : 918]) : c$map_arg4_case_alt_227;

  assign c$map_arg4_case_alt_227 = (ds1_0 == 8'd154) ? (c$map_arg4_app_arg_2[929 : 924]) : c$map_arg4_case_alt_228;

  assign c$map_arg4_case_alt_228 = (ds1_0 == 8'd155) ? (c$map_arg4_app_arg_2[935 : 930]) : c$map_arg4_case_alt_229;

  assign c$map_arg4_case_alt_229 = (ds1_0 == 8'd156) ? (c$map_arg4_app_arg_2[941 : 936]) : c$map_arg4_case_alt_230;

  assign c$map_arg4_case_alt_230 = (ds1_0 == 8'd157) ? (c$map_arg4_app_arg_2[947 : 942]) : c$map_arg4_case_alt_231;

  assign c$map_arg4_case_alt_231 = (ds1_0 == 8'd158) ? (c$map_arg4_app_arg_2[953 : 948]) : c$map_arg4_case_alt_232;

  assign c$map_arg4_case_alt_232 = (ds1_0 == 8'd159) ? (c$map_arg4_app_arg_2[959 : 954]) : c$map_arg4_case_alt_233;

  assign c$map_arg4_case_alt_233 = (ds1_0 == 8'd160) ? (c$map_arg4_app_arg_2[965 : 960]) : c$map_arg4_case_alt_234;

  assign c$map_arg4_case_alt_234 = (ds1_0 == 8'd161) ? (c$map_arg4_app_arg_2[971 : 966]) : c$map_arg4_case_alt_235;

  assign c$map_arg4_case_alt_235 = (ds1_0 == 8'd162) ? (c$map_arg4_app_arg_2[977 : 972]) : c$map_arg4_case_alt_236;

  assign c$map_arg4_case_alt_236 = (ds1_0 == 8'd163) ? (c$map_arg4_app_arg_2[983 : 978]) : c$map_arg4_case_alt_237;

  assign c$map_arg4_case_alt_237 = (ds1_0 == 8'd164) ? (c$map_arg4_app_arg_2[989 : 984]) : c$map_arg4_case_alt_238;

  assign c$map_arg4_case_alt_238 = (ds1_0 == 8'd165) ? (c$map_arg4_app_arg_2[995 : 990]) : c$map_arg4_case_alt_239;

  assign c$map_arg4_case_alt_239 = (ds1_0 == 8'd166) ? (c$map_arg4_app_arg_2[1001 : 996]) : c$map_arg4_case_alt_240;

  assign c$map_arg4_case_alt_240 = (ds1_0 == 8'd167) ? (c$map_arg4_app_arg_2[1007 : 1002]) : c$map_arg4_case_alt_241;

  assign c$map_arg4_case_alt_241 = (ds1_0 == 8'd168) ? (c$map_arg4_app_arg_2[1013 : 1008]) : c$map_arg4_case_alt_242;

  assign c$map_arg4_case_alt_242 = (ds1_0 == 8'd169) ? (c$map_arg4_app_arg_2[1019 : 1014]) : c$map_arg4_case_alt_243;

  assign c$map_arg4_case_alt_243 = (ds1_0 == 8'd170) ? (c$map_arg4_app_arg_2[1025 : 1020]) : c$map_arg4_case_alt_244;

  assign c$map_arg4_case_alt_244 = (ds1_0 == 8'd171) ? (c$map_arg4_app_arg_2[1031 : 1026]) : c$map_arg4_case_alt_245;

  assign c$map_arg4_case_alt_245 = (ds1_0 == 8'd172) ? (c$map_arg4_app_arg_2[1037 : 1032]) : c$map_arg4_case_alt_246;

  assign c$map_arg4_case_alt_246 = (ds1_0 == 8'd173) ? (c$map_arg4_app_arg_2[1043 : 1038]) : c$map_arg4_case_alt_247;

  assign c$map_arg4_case_alt_247 = (ds1_0 == 8'd174) ? (c$map_arg4_app_arg_2[1049 : 1044]) : c$map_arg4_case_alt_248;

  assign c$map_arg4_case_alt_248 = (ds1_0 == 8'd175) ? (c$map_arg4_app_arg_2[1055 : 1050]) : c$map_arg4_case_alt_249;

  assign c$map_arg4_case_alt_249 = (ds1_0 == 8'd176) ? (c$map_arg4_app_arg_2[1061 : 1056]) : c$map_arg4_case_alt_250;

  assign c$map_arg4_case_alt_250 = (ds1_0 == 8'd177) ? (c$map_arg4_app_arg_2[1067 : 1062]) : c$map_arg4_case_alt_251;

  assign c$map_arg4_case_alt_251 = (ds1_0 == 8'd178) ? (c$map_arg4_app_arg_2[1073 : 1068]) : c$map_arg4_case_alt_252;

  assign c$map_arg4_case_alt_252 = (ds1_0 == 8'd179) ? (c$map_arg4_app_arg_2[1079 : 1074]) : c$map_arg4_case_alt_253;

  assign c$map_arg4_case_alt_253 = (ds1_0 == 8'd180) ? (c$map_arg4_app_arg_2[1085 : 1080]) : ({6 {1'bx}});

  assign c$map_arg4_app_arg_2 = block;

  assign block = c$ds_app_arg[1607:8];

  assign ds1_0 = $unsigned(c$ds1_app_arg_0[0+:8]);

  assign c$ds1_app_arg_0 = $unsigned({{(64-8) {1'b0}},coeffIdx_0});

  assign coeffIdx_0 = c$ds_app_arg[1615:1608];

  Component_SamplePolyCBD512_topEntity_keccakF1600 Component_SamplePolyCBD512_topEntity_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (roundIdx)
    , .x (state) );

  assign state = c$ds_app_arg[1602:3];

  assign roundIdx = c$ds_app_arg[1615:1611];

  assign DIGEST_TDATA_0 = result.Tuple2_3_sel0;

  assign DIGEST_TVALID = result.Tuple2_3_sel1;

  assign DIGEST_TDATA = DIGEST_TDATA_0;


endmodule

