/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_SamplePolyCBD512
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [263:0] MSG_33B
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [13:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    );
  logic [1757:0] c$ds_app_arg = {2'b00,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  Component_SamplePolyCBD512_types::Tuple2_2 c$case_alt;
  Component_SamplePolyCBD512_types::AXI4Stream c$app_arg;
  logic [11:0] result_0;
  logic [2:0] a;
  logic [2:0] b;
  logic [5:0] c$b_app_arg;
  Component_SamplePolyCBD512_types::array_of_6_logic_vector_1 c$app_arg_0;
  Component_SamplePolyCBD512_types::array_of_6_logic c$app_arg_1;
  Component_SamplePolyCBD512_types::array_of_6_logic c$app_arg_2;
  logic [1757:0] c$app_arg_3;
  logic [1757:0] result_1;
  logic [1757:0] c$case_alt_0;
  logic signed [63:0] ds2;
  logic signed [63:0] c$ds2_app_arg;
  logic [63:0] result_2;
  logic [63:0] c$karg_case_alt;
  logic [63:0] c$karg_case_alt_0;
  logic [63:0] c$karg_case_alt_1;
  logic [63:0] c$karg_case_alt_2;
  logic [63:0] c$karg_case_alt_3;
  logic [63:0] c$karg_case_alt_4;
  logic [63:0] c$karg_case_alt_5;
  logic [63:0] c$karg_case_alt_6;
  logic [63:0] c$karg_case_alt_7;
  logic [63:0] c$karg_case_alt_8;
  logic [63:0] c$karg_case_alt_9;
  logic [63:0] c$karg_case_alt_10;
  logic [63:0] c$karg_case_alt_11;
  logic [63:0] c$karg_case_alt_12;
  logic [63:0] c$karg_case_alt_13;
  logic [63:0] c$karg_case_alt_14;
  logic [4:0] ds2_0;
  logic [1599:0] c$karg_app_arg;
  logic [1599:0] state;
  logic signed [63:0] c$ds2_app_arg_0;
  logic signed [63:0] c$ds2_case_alt;
  logic signed [63:0] c$ds2_case_alt_0;
  logic needLoad;
  logic [0:0] blockIdx;
  logic [4:0] wordIdx;
  logic [7:0] \validBits' ;
  Component_SamplePolyCBD512_types::Tuple3_0 ds1;
  logic canOutput;
  logic [7:0] validBits;
  logic [127:0] buffer;
  logic isLast;
  logic [8:0] coeffIdx;
  Component_SamplePolyCBD512_types::Tuple2_2 result_3;
  logic [7:0] validBits_0;
  logic [127:0] buffer_0;
  logic [0:0] blockIdx_0;
  logic [4:0] wordIdx_0;
  logic [8:0] coeffIdx_0;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_4;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_5;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_6;
  logic [1599:0] result_7;
  logic [1599:0] c$app_arg_7;
  logic [1599:0] result_8;
  logic [1599:0] c$app_arg_8;
  logic [1599:0] result_9;
  logic [1599:0] c$app_arg_9;
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] state_0;
  logic [4:0] roundIdx;
  logic [0:0] c$bv;
  logic [0:0] c$bv_0;
  logic [0:0] c$bv_1;
  logic [0:0] c$bv_2;
  logic [0:0] c$bv_3;
  logic [0:0] c$bv_4;
  logic [127:0] c$bv_5;
  Component_SamplePolyCBD512_types::array_of_6_logic_vector_1 c$vec;
  logic [4:0] c$i_37;
  Component_SamplePolyCBD512_types::Tuple2_3 result;
  Component_SamplePolyCBD512_types::AXI4Stream DIGEST_TDATA_0;

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {2'b00,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt.Tuple2_2_sel0;
    end
  end
  // register end

  assign result = c$case_alt.Tuple2_2_sel1;

  always_comb begin
    case(c$ds_app_arg[1757:1756])
      2'b00 : c$case_alt = {{2'b01,5'd0,9'd0,5'd0,1'd0,128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,8'd0,result_4}
                           ,{{12'b000000000000,1'b0,1'b0},1'b1}};
      2'b01 : c$case_alt = result_3;
      2'b10 : c$case_alt = {c$app_arg_3
                           ,{c$app_arg,1'b0}};
      default : c$case_alt = {{2'b11,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                             ,{{12'b000000000000,1'b0,1'b0},1'b0}};
    endcase
  end

  assign c$app_arg = canOutput ? {result_0
                                 ,1'b1
                                 ,isLast} : {12'b000000000000,1'b0,1'b0};

  assign result_0 = (a >= b) ? ({9'b000000000,(((a - b)))}) : (12'b110100000001 - ({9'b000000000,(((b - a)))}));

  assign c$bv = ((c$b_app_arg[5 : 5]));

  assign c$bv_0 = ((c$b_app_arg[4 : 4]));

  assign c$bv_1 = ((c$b_app_arg[3 : 3]));

  assign a = (({{(3-1) {1'b0}},((c$b_app_arg[5 : 5]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[4 : 4]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[3 : 3]))});

  assign c$bv_2 = ((c$b_app_arg[2 : 2]));

  assign c$bv_3 = ((c$b_app_arg[1 : 1]));

  assign c$bv_4 = ((c$b_app_arg[0 : 0]));

  assign b = (({{(3-1) {1'b0}},((c$b_app_arg[2 : 2]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[1 : 1]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[0 : 0]))});

  assign c$b_app_arg = (({Component_SamplePolyCBD512_types::array_of_6_logic_vector_1_to_lv(c$app_arg_0)}));

  // map begin
  genvar n;
  generate
  for (n=0; n < $size(c$app_arg_0); n = n + 1) begin : map
    logic map_in;
    assign map_in = c$app_arg_1[n];
    logic [0:0] map_out;
    assign map_out = (map_in);


    assign c$app_arg_0[n] = map_out;
  end
  endgenerate
  // map end

  // reverse begin
  genvar n_0;
  generate
    for (n_0 = 0; n_0 < $size(c$app_arg_2); n_0 = n_0 + 1) begin : reverse
      assign c$app_arg_1[$high(c$app_arg_2) - n_0] = c$app_arg_2[n_0];
    end
  endgenerate
  // reverse end

  assign c$bv_5 = (buffer);

  assign c$vec = (Component_SamplePolyCBD512_types::array_of_6_logic_vector_1_from_lv((c$bv_5[5 : 0])));

  // map begin
  genvar n_1;
  generate
  for (n_1=0; n_1 < $size(c$app_arg_2); n_1 = n_1 + 1) begin : map_0
    logic [0:0] map_in_0;
    assign map_in_0 = c$vec[n_1];
    logic map_out_0;
    assign map_out_0 = map_in_0;


    assign c$app_arg_2[n_1] = map_out_0;
  end
  endgenerate
  // map end

  assign c$app_arg_3 = (canOutput & (DIGEST_TREADY & isLast)) ? {2'b11,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : result_1;

  assign result_1 = ((wordIdx == 5'd17) & ((blockIdx == 1'd0) & needLoad)) ? {2'b01,5'd0,ds1.Tuple3_0_sel0,wordIdx,1'd1,ds1.Tuple3_0_sel1,\validBits' ,state} : c$case_alt_0;

  assign c$case_alt_0 = needLoad ? {2'b10,ds1.Tuple3_0_sel0,wordIdx + 5'd1,blockIdx,ds1.Tuple3_0_sel1 | (({64'b0000000000000000000000000000000000000000000000000000000000000000,result_2}) << (ds2)),\validBits'  + 8'd64,state,5'bxxxxx} : {2'b10,ds1.Tuple3_0_sel0,wordIdx,blockIdx,ds1.Tuple3_0_sel1,\validBits' ,state,5'bxxxxx};

  assign ds2 = $signed(c$ds2_app_arg);

  assign c$ds2_app_arg = $unsigned({{(64-8) {1'b0}},\validBits' });

  assign result_2 = (ds2_0 == 5'd0) ? (c$karg_app_arg[63 : 0]) : c$karg_case_alt;

  assign c$karg_case_alt = (ds2_0 == 5'd1) ? (c$karg_app_arg[127 : 64]) : c$karg_case_alt_0;

  assign c$karg_case_alt_0 = (ds2_0 == 5'd2) ? (c$karg_app_arg[191 : 128]) : c$karg_case_alt_1;

  assign c$karg_case_alt_1 = (ds2_0 == 5'd3) ? (c$karg_app_arg[255 : 192]) : c$karg_case_alt_2;

  assign c$karg_case_alt_2 = (ds2_0 == 5'd4) ? (c$karg_app_arg[319 : 256]) : c$karg_case_alt_3;

  assign c$karg_case_alt_3 = (ds2_0 == 5'd5) ? (c$karg_app_arg[383 : 320]) : c$karg_case_alt_4;

  assign c$karg_case_alt_4 = (ds2_0 == 5'd6) ? (c$karg_app_arg[447 : 384]) : c$karg_case_alt_5;

  assign c$karg_case_alt_5 = (ds2_0 == 5'd7) ? (c$karg_app_arg[511 : 448]) : c$karg_case_alt_6;

  assign c$karg_case_alt_6 = (ds2_0 == 5'd8) ? (c$karg_app_arg[575 : 512]) : c$karg_case_alt_7;

  assign c$karg_case_alt_7 = (ds2_0 == 5'd9) ? (c$karg_app_arg[639 : 576]) : c$karg_case_alt_8;

  assign c$karg_case_alt_8 = (ds2_0 == 5'd10) ? (c$karg_app_arg[703 : 640]) : c$karg_case_alt_9;

  assign c$karg_case_alt_9 = (ds2_0 == 5'd11) ? (c$karg_app_arg[767 : 704]) : c$karg_case_alt_10;

  assign c$karg_case_alt_10 = (ds2_0 == 5'd12) ? (c$karg_app_arg[831 : 768]) : c$karg_case_alt_11;

  assign c$karg_case_alt_11 = (ds2_0 == 5'd13) ? (c$karg_app_arg[895 : 832]) : c$karg_case_alt_12;

  assign c$karg_case_alt_12 = (ds2_0 == 5'd14) ? (c$karg_app_arg[959 : 896]) : c$karg_case_alt_13;

  assign c$karg_case_alt_13 = (ds2_0 == 5'd15) ? (c$karg_app_arg[1023 : 960]) : c$karg_case_alt_14;

  assign c$karg_case_alt_14 = (ds2_0 == 5'd16) ? (c$karg_app_arg[1087 : 1024]) : ({64 {1'bx}});

  assign ds2_0 = $unsigned(c$ds2_app_arg_0[0+:5]);

  assign c$karg_app_arg = state;

  assign state = c$ds_app_arg[1604:5];

  assign c$ds2_app_arg_0 = (wordIdx < 5'd17) ? c$ds2_case_alt : c$ds2_case_alt_0;

  assign c$ds2_case_alt = $unsigned({{(64-5) {1'b0}},wordIdx});

  assign c$i_37 = (wordIdx - 5'd17);

  assign c$ds2_case_alt_0 = $unsigned({{(64-5) {1'b0}},c$i_37});

  assign needLoad = (\validBits'  <= 8'd64) & (wordIdx < 5'd24);

  assign blockIdx = c$ds_app_arg[1741:1741];

  assign wordIdx = c$ds_app_arg[1746:1742];

  assign \validBits'  = ds1.Tuple3_0_sel2;

  assign ds1 = (canOutput & DIGEST_TREADY) ? {coeffIdx + 9'd1
                                             ,buffer >> (64'sd6)
                                             ,validBits - 8'd6} : {coeffIdx
                                                                  ,buffer
                                                                  ,validBits};

  assign canOutput = validBits >= 8'd6;

  assign validBits = c$ds_app_arg[1612:1605];

  assign buffer = c$ds_app_arg[1740:1613];

  assign isLast = coeffIdx == 9'd255;

  assign coeffIdx = c$ds_app_arg[1755:1747];

  assign result_3 = (roundIdx == 5'd23) ? {{2'b10,coeffIdx_0,wordIdx_0,blockIdx_0,buffer_0,validBits_0,c$keccakF1600_out,5'bxxxxx}
                                          ,{{12'b000000000000,1'b0,1'b0}
                                           ,1'b0}} : {{2'b01,roundIdx + 5'd1,coeffIdx_0,wordIdx_0,blockIdx_0,buffer_0,validBits_0,c$keccakF1600_out}
                                                     ,{{12'b000000000000,1'b0,1'b0},1'b0}};

  assign validBits_0 = c$ds_app_arg[1607:1600];

  assign buffer_0 = c$ds_app_arg[1735:1608];

  assign blockIdx_0 = c$ds_app_arg[1736:1736];

  assign wordIdx_0 = c$ds_app_arg[1741:1737];

  assign coeffIdx_0 = c$ds_app_arg[1750:1742];

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_4;
    result_4[64'sd1087] = (~ (c$app_arg_4[64'sd1087]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_5;
    result_5[64'sd264] = (~ (c$app_arg_5[64'sd264]));
  end
  // replaceBit end

  assign c$app_arg_5 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_6;
    result_6[64'sd265] = (~ (c$app_arg_6[64'sd265]));
  end
  // replaceBit end

  assign c$app_arg_6 = result_7;

  // replaceBit start
  always_comb begin
    result_7 = c$app_arg_7;
    result_7[64'sd266] = (~ (c$app_arg_7[64'sd266]));
  end
  // replaceBit end

  assign c$app_arg_7 = result_8;

  // replaceBit start
  always_comb begin
    result_8 = c$app_arg_8;
    result_8[64'sd267] = (~ (c$app_arg_8[64'sd267]));
  end
  // replaceBit end

  assign c$app_arg_8 = result_9;

  // replaceBit start
  always_comb begin
    result_9 = c$app_arg_9;
    result_9[64'sd268] = (~ (c$app_arg_9[64'sd268]));
  end
  // replaceBit end

  assign c$app_arg_9 = ({1336'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,MSG_33B});

  Component_SamplePolyCBD512_topEntity_keccakF1600 Component_SamplePolyCBD512_topEntity_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (roundIdx)
    , .x (state_0) );

  assign state_0 = c$ds_app_arg[1599:0];

  assign roundIdx = c$ds_app_arg[1755:1751];

  assign DIGEST_TDATA_0 = result.Tuple2_3_sel0;

  assign DIGEST_TVALID = result.Tuple2_3_sel1;

  assign DIGEST_TDATA = DIGEST_TDATA_0;


endmodule

