/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_Dev
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [1599:0] STATE
    , input wire logic [63:0] BLOCK
    , input wire logic [4:0] BEAT

      // Outputs
    , output logic [1599:0] STATE_OUT
    );
  logic [1599:0] state;
  logic [63:0] block;
  logic [4:0] beat;
  logic [1599:0] c$case_alt;
  logic [1599:0] c$case_alt_0;
  logic [1599:0] c$case_alt_1;
  logic [1599:0] c$case_alt_2;
  logic [1599:0] c$case_alt_3;
  logic [1599:0] c$case_alt_4;
  logic [1599:0] c$case_alt_5;
  logic [1599:0] c$case_alt_6;
  logic [1599:0] c$case_alt_7;
  logic [1599:0] c$case_alt_8;
  logic [1599:0] c$case_alt_9;
  logic [1599:0] c$case_alt_10;
  logic [1599:0] c$case_alt_11;
  logic [1599:0] c$case_alt_12;
  logic [1599:0] c$case_alt_13;
  logic [1599:0] c$case_alt_14;
  logic [1599:0] c$case_alt_15;
  logic [1599:0] c$case_alt_16;
  logic [1599:0] c$case_alt_17;
  logic [1599:0] c$case_alt_18;
  logic [1599:0] c$case_alt_19;
  logic [1599:0] c$case_alt_20;
  logic [1599:0] c$case_alt_21;
  logic [1599:0] c$case_alt_22;
  logic [1599:0] c$case_alt_23;
  logic [1599:0] c$case_alt_24;
  logic [1599:0] c$case_alt_25;
  logic [1599:0] c$case_alt_26;
  logic [1599:0] c$case_alt_27;
  logic [1599:0] c$case_alt_28;
  logic [1599:0] c$case_alt_29;
  logic [1599:0] c$case_alt_30;
  logic [1599:0] c$case_alt_31;
  logic [1599:0] c$app_arg;
  Component_Dev_types::Tuple3 eta;

  assign eta = {STATE,BLOCK,BEAT};

  assign state = eta.Tuple3_sel0;

  assign block = eta.Tuple3_sel1;

  assign beat = eta.Tuple3_sel2;

  assign STATE_OUT = (beat == 5'd0) ? c$case_alt : c$case_alt_0;

  // setSlice begin
  always_comb begin
    c$case_alt = c$app_arg;
    c$case_alt[63 : 0] = ((c$app_arg[63 : 0]) ^ block);
  end
  // setSlice end

  assign c$case_alt_0 = (beat == 5'd1) ? c$case_alt_1 : c$case_alt_2;

  // setSlice begin
  always_comb begin
    c$case_alt_1 = c$app_arg;
    c$case_alt_1[127 : 64] = ((c$app_arg[127 : 64]) ^ block);
  end
  // setSlice end

  assign c$case_alt_2 = (beat == 5'd2) ? c$case_alt_3 : c$case_alt_4;

  // setSlice begin
  always_comb begin
    c$case_alt_3 = c$app_arg;
    c$case_alt_3[191 : 128] = ((c$app_arg[191 : 128]) ^ block);
  end
  // setSlice end

  assign c$case_alt_4 = (beat == 5'd3) ? c$case_alt_5 : c$case_alt_6;

  // setSlice begin
  always_comb begin
    c$case_alt_5 = c$app_arg;
    c$case_alt_5[255 : 192] = ((c$app_arg[255 : 192]) ^ block);
  end
  // setSlice end

  assign c$case_alt_6 = (beat == 5'd4) ? c$case_alt_7 : c$case_alt_8;

  // setSlice begin
  always_comb begin
    c$case_alt_7 = c$app_arg;
    c$case_alt_7[319 : 256] = ((c$app_arg[319 : 256]) ^ block);
  end
  // setSlice end

  assign c$case_alt_8 = (beat == 5'd5) ? c$case_alt_9 : c$case_alt_10;

  // setSlice begin
  always_comb begin
    c$case_alt_9 = c$app_arg;
    c$case_alt_9[383 : 320] = ((c$app_arg[383 : 320]) ^ block);
  end
  // setSlice end

  assign c$case_alt_10 = (beat == 5'd6) ? c$case_alt_11 : c$case_alt_12;

  // setSlice begin
  always_comb begin
    c$case_alt_11 = c$app_arg;
    c$case_alt_11[447 : 384] = ((c$app_arg[447 : 384]) ^ block);
  end
  // setSlice end

  assign c$case_alt_12 = (beat == 5'd7) ? c$case_alt_13 : c$case_alt_14;

  // setSlice begin
  always_comb begin
    c$case_alt_13 = c$app_arg;
    c$case_alt_13[511 : 448] = ((c$app_arg[511 : 448]) ^ block);
  end
  // setSlice end

  assign c$case_alt_14 = (beat == 5'd8) ? c$case_alt_15 : c$case_alt_16;

  // setSlice begin
  always_comb begin
    c$case_alt_15 = c$app_arg;
    c$case_alt_15[575 : 512] = ((c$app_arg[575 : 512]) ^ block);
  end
  // setSlice end

  assign c$case_alt_16 = (beat == 5'd9) ? c$case_alt_17 : c$case_alt_18;

  // setSlice begin
  always_comb begin
    c$case_alt_17 = c$app_arg;
    c$case_alt_17[639 : 576] = ((c$app_arg[639 : 576]) ^ block);
  end
  // setSlice end

  assign c$case_alt_18 = (beat == 5'd10) ? c$case_alt_19 : c$case_alt_20;

  // setSlice begin
  always_comb begin
    c$case_alt_19 = c$app_arg;
    c$case_alt_19[703 : 640] = ((c$app_arg[703 : 640]) ^ block);
  end
  // setSlice end

  assign c$case_alt_20 = (beat == 5'd11) ? c$case_alt_21 : c$case_alt_22;

  // setSlice begin
  always_comb begin
    c$case_alt_21 = c$app_arg;
    c$case_alt_21[767 : 704] = ((c$app_arg[767 : 704]) ^ block);
  end
  // setSlice end

  assign c$case_alt_22 = (beat == 5'd12) ? c$case_alt_23 : c$case_alt_24;

  // setSlice begin
  always_comb begin
    c$case_alt_23 = c$app_arg;
    c$case_alt_23[831 : 768] = ((c$app_arg[831 : 768]) ^ block);
  end
  // setSlice end

  assign c$case_alt_24 = (beat == 5'd13) ? c$case_alt_25 : c$case_alt_26;

  // setSlice begin
  always_comb begin
    c$case_alt_25 = c$app_arg;
    c$case_alt_25[895 : 832] = ((c$app_arg[895 : 832]) ^ block);
  end
  // setSlice end

  assign c$case_alt_26 = (beat == 5'd14) ? c$case_alt_27 : c$case_alt_28;

  // setSlice begin
  always_comb begin
    c$case_alt_27 = c$app_arg;
    c$case_alt_27[959 : 896] = ((c$app_arg[959 : 896]) ^ block);
  end
  // setSlice end

  assign c$case_alt_28 = (beat == 5'd15) ? c$case_alt_29 : c$case_alt_30;

  // setSlice begin
  always_comb begin
    c$case_alt_29 = c$app_arg;
    c$case_alt_29[1023 : 960] = ((c$app_arg[1023 : 960]) ^ block);
  end
  // setSlice end

  assign c$case_alt_30 = (beat == 5'd16) ? c$case_alt_31 : state;

  // setSlice begin
  always_comb begin
    c$case_alt_31 = c$app_arg;
    c$case_alt_31[1087 : 1024] = ((c$app_arg[1087 : 1024]) ^ block);
  end
  // setSlice end

  assign c$app_arg = state;


endmodule

