/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_Dev_topEntity_read
    ( // Inputs
      input wire logic [4:0] ds
    , input wire logic [1599:0] bv

      // Outputs
    , output logic [63:0] result
    );
  logic [63:0] c$case_alt;
  logic [63:0] c$case_alt_0;
  logic [63:0] c$case_alt_1;
  logic [63:0] c$case_alt_2;
  logic [63:0] c$case_alt_3;
  logic [63:0] c$case_alt_4;
  logic [63:0] c$case_alt_5;
  logic [63:0] c$case_alt_6;
  logic [63:0] c$case_alt_7;
  logic [63:0] c$case_alt_8;
  logic [63:0] c$case_alt_9;
  logic [63:0] c$case_alt_10;
  logic [63:0] c$case_alt_11;
  logic [63:0] c$case_alt_12;
  logic [63:0] c$case_alt_13;
  logic [63:0] c$case_alt_14;
  logic [63:0] c$case_alt_15;
  logic [63:0] c$case_alt_16;
  logic [63:0] c$case_alt_17;
  logic [63:0] c$case_alt_18;
  logic [63:0] c$case_alt_19;
  logic [63:0] c$case_alt_20;
  logic [63:0] c$case_alt_21;
  logic [1599:0] c$app_arg;

  assign result = (ds == 5'd0) ? (c$app_arg[63 : 0]) : c$case_alt;

  assign c$case_alt = (ds == 5'd1) ? (c$app_arg[127 : 64]) : c$case_alt_0;

  assign c$case_alt_0 = (ds == 5'd2) ? (c$app_arg[191 : 128]) : c$case_alt_1;

  assign c$case_alt_1 = (ds == 5'd3) ? (c$app_arg[255 : 192]) : c$case_alt_2;

  assign c$case_alt_2 = (ds == 5'd4) ? (c$app_arg[319 : 256]) : c$case_alt_3;

  assign c$case_alt_3 = (ds == 5'd5) ? (c$app_arg[383 : 320]) : c$case_alt_4;

  assign c$case_alt_4 = (ds == 5'd6) ? (c$app_arg[447 : 384]) : c$case_alt_5;

  assign c$case_alt_5 = (ds == 5'd7) ? (c$app_arg[511 : 448]) : c$case_alt_6;

  assign c$case_alt_6 = (ds == 5'd8) ? (c$app_arg[575 : 512]) : c$case_alt_7;

  assign c$case_alt_7 = (ds == 5'd9) ? (c$app_arg[639 : 576]) : c$case_alt_8;

  assign c$case_alt_8 = (ds == 5'd10) ? (c$app_arg[703 : 640]) : c$case_alt_9;

  assign c$case_alt_9 = (ds == 5'd11) ? (c$app_arg[767 : 704]) : c$case_alt_10;

  assign c$case_alt_10 = (ds == 5'd12) ? (c$app_arg[831 : 768]) : c$case_alt_11;

  assign c$case_alt_11 = (ds == 5'd13) ? (c$app_arg[895 : 832]) : c$case_alt_12;

  assign c$case_alt_12 = (ds == 5'd14) ? (c$app_arg[959 : 896]) : c$case_alt_13;

  assign c$case_alt_13 = (ds == 5'd15) ? (c$app_arg[1023 : 960]) : c$case_alt_14;

  assign c$case_alt_14 = (ds == 5'd16) ? (c$app_arg[1087 : 1024]) : c$case_alt_15;

  assign c$case_alt_15 = (ds == 5'd17) ? (c$app_arg[1151 : 1088]) : c$case_alt_16;

  assign c$case_alt_16 = (ds == 5'd18) ? (c$app_arg[1215 : 1152]) : c$case_alt_17;

  assign c$case_alt_17 = (ds == 5'd19) ? (c$app_arg[1279 : 1216]) : c$case_alt_18;

  assign c$case_alt_18 = (ds == 5'd20) ? (c$app_arg[1343 : 1280]) : c$case_alt_19;

  assign c$case_alt_19 = (ds == 5'd21) ? (c$app_arg[1407 : 1344]) : c$case_alt_20;

  assign c$case_alt_20 = (ds == 5'd22) ? (c$app_arg[1471 : 1408]) : c$case_alt_21;

  assign c$case_alt_21 = (ds == 5'd23) ? (c$app_arg[1535 : 1472]) : (c$app_arg[1599 : 1536]);

  assign c$app_arg = bv;


endmodule

